# Generated by Django 4.2.23 on 2026-03-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbashop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sbaproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
