# Generated by Django 5.2.13 on 2026-04-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbashop', '0002_alter_category_slug_alter_sbaproduct_slug'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sbaproduct',
            new_name='sbashop_sba_id_68820f_idx',
            old_fields=('id', 'slug'),
        ),
    ]
