# Generated by Django 4.2.23 on 2025-08-31 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='desde',
        ),
        migrations.RemoveField(
            model_name='category',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='category',
            name='salidas',
        ),
        migrations.RemoveField(
            model_name='category',
            name='terms',
        ),
    ]
