# Generated by Django 4.2.23 on 2025-08-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria de Producto', 'verbose_name_plural': 'Categorias de Productos'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='automatizacion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='inteligencia_artificial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='latencia_aproximada',
            field=models.CharField(blank=True, choices=[('500-800', '500-800 ms'), ('300-500', '300-500 ms'), ('100-300', '100-300 ms'), ('50-100', '50-100 ms'), ('20-50', '20-50 ms'), ('10-20', '10-20 ms')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='nombre',
            field=models.CharField(blank=True, choices=[('SaaS', 'Software como Servicio'), ('PaaS', 'Plataforma como Servicio'), ('IaaS', 'Infraestructura como Servicio')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='numero_procesos',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='usuarios_simultaneos',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
