# Generated by Django 4.2.23 on 2025-08-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0002_alter_category_options_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='usuarios_simultaneos',
            field=models.CharField(blank=True, choices=[('100-150', '100-150'), ('150-250', '150-250'), ('250-350', '250-350'), ('350-450', '350-450'), ('450-550', '450-550'), ('550-650', '550-650'), ('650-750', '650-750'), ('750-850', '750-850'), ('850-950', '850-950'), ('950-1000', '950-1000'), ('1000+', 'Más de 1000')], max_length=10, null=True),
        ),
    ]
