# Generated by Django 4.2.23 on 2025-08-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0002_remove_category_description_remove_category_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(blank=True, choices=[('SaaS', 'Software como Servicio'), ('PaaS', 'Plataforma como Servicio'), ('IaaS', 'Infraestructura como Servicio')], max_length=100, null=True),
        ),
    ]
