# Generated by Django 4.2.23 on 2025-08-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0003_alter_category_usuarios_simultaneos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='numero_procesos',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('20', '20'), ('40', '40'), ('80', '80'), ('100', '100'), ('200+', 'Más de 200')], default='5', max_length=5, null=True),
        ),
    ]
