# Generated by Django 4.2.23 on 2025-08-31 03:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0003_alter_category_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SaaS', 'Software como Servicio'), ('PaaS', 'Plataforma como Servicio'), ('IaaS', 'Infraestructura como Servicio')], max_length=100, null=True),
        ),
    ]
