# Generated by Django 4.2.23 on 2025-08-21 23:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0004_alter_category_numero_procesos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='inteligencia_artificial',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('prediccion', 'Agente de IA de predicción'), ('segmentacion', 'Agente de IA de segmentación'), ('recomendacion', 'Agente de IA de recomendación')], max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='latencia_aproximada',
            field=models.CharField(blank=True, choices=[('500-800', 'Alta latencia (500–800 ms)'), ('300-500', 'Latencia elevada (300–500 ms)'), ('100-300', 'Latencia aceptable (100–300 ms)'), ('50-100', 'Baja latencia (50–100 ms)'), ('20-50', 'Muy baja latencia (20–50 ms)'), ('10-20', 'Latencia óptima (10–20 ms)')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='numero_procesos',
            field=models.CharField(blank=True, choices=[('5', '5 procesos'), ('10', '10 procesos'), ('20', '20 procesos'), ('40', '40 procesos'), ('80', '80 procesos'), ('100', '100 procesos'), ('200+', 'Más de 200 procesos')], default='5', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='usuarios_simultaneos',
            field=models.CharField(blank=True, choices=[('10-50', 'Baja concurrencia (10–50 usuarios)'), ('50-150', 'Carga ligera (50–150 usuarios)'), ('150-500', 'Carga media (150–500 usuarios)'), ('500-1000', 'Alta concurrencia (500–1000 usuarios)'), ('1000-5000', 'Carga crítica (1000–5000 usuarios)'), ('5000+', 'Alta disponibilidad (>5000 usuarios simultáneos)')], max_length=10, null=True),
        ),
    ]
