# Generated by Django 4.2.23 on 2025-08-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0005_category_slug_alter_category_automatizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nombre_en',
            field=models.CharField(blank=True, choices=[('SaaS', 'Software como Servicio'), ('PaaS', 'Plataforma como Servicio'), ('IaaS', 'Infraestructura como Servicio')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='nombre_es',
            field=models.CharField(blank=True, choices=[('SaaS', 'Software como Servicio'), ('PaaS', 'Plataforma como Servicio'), ('IaaS', 'Infraestructura como Servicio')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_es',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
