# Generated by Django 4.2.23 on 2025-08-23 02:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0005_alter_category_inteligencia_artificial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='plataforma',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ecommerce', 'Plataforma de Comercio Electrónico'), ('educacional', 'Plataforma Educativa Digital'), ('cadena_suministro', 'Sistema de Gestión de la Cadena de Suministro'), ('medico', 'Plataforma de Gestión Médica y Salud'), ('administracion_recursos', 'Plataforma de Administración de Recursos Empresariales'), ('gastronomia', 'Plataforma para Gestión de Recursos Gastronómicos')], max_length=82, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='software',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('crm', 'SmartBusinessMedia - CRM'), ('erp', 'SmartBusinessAnalytics - ERP')], max_length=7, null=True),
        ),
    ]
