# Generated by Django 4.2.23 on 2025-08-23 02:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0006_category_plataforma_category_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='automatizacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('chatbots', 'Automatización mediante Chatbots'), ('email_marketing', 'Envío Automático de Correos Electrónicos'), ('facturacion', 'Facturación Electrónica Automatizada'), ('crm_automatizado', 'Automatización de CRM (Gestión de Clientes)'), ('reserva_online', 'Gestión Automatizada de Reservas o Citas'), ('notificaciones', 'Notificaciones Automatizadas en Tiempo Real'), ('reportes', 'Generación Automática de Reportes'), ('seguimiento_clientes', 'Seguimiento Automático de Clientes'), ('procesamiento_pedidos', 'Automatización del Procesamiento de Pedidos'), ('sistemas_alertas', 'Sistemas de Alertas Automatizadas')], max_length=152, null=True),
        ),
    ]
