# Generated by Django 4.2.23 on 2025-08-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0006_category_nombre_en_category_nombre_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='automatizacion_en',
            field=models.CharField(blank=True, choices=[('chatbots', 'Automatización mediante Chatbots'), ('email_marketing', 'Envío Automático de Correos Electrónicos'), ('facturacion', 'Facturación Electrónica Automatizada'), ('crm_automatizado', 'Automatización de CRM'), ('reserva_online', 'Gestión de Reservas o Citas'), ('notificaciones', 'Notificaciones en Tiempo Real'), ('reportes', 'Generación de Reportes'), ('seguimiento_clientes', 'Seguimiento de Clientes'), ('procesamiento_pedidos', 'Procesamiento de Pedidos'), ('sistemas_alertas', 'Sistemas de Alertas')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='automatizacion_es',
            field=models.CharField(blank=True, choices=[('chatbots', 'Automatización mediante Chatbots'), ('email_marketing', 'Envío Automático de Correos Electrónicos'), ('facturacion', 'Facturación Electrónica Automatizada'), ('crm_automatizado', 'Automatización de CRM'), ('reserva_online', 'Gestión de Reservas o Citas'), ('notificaciones', 'Notificaciones en Tiempo Real'), ('reportes', 'Generación de Reportes'), ('seguimiento_clientes', 'Seguimiento de Clientes'), ('procesamiento_pedidos', 'Procesamiento de Pedidos'), ('sistemas_alertas', 'Sistemas de Alertas')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='inteligencia_artificial_en',
            field=models.CharField(blank=True, choices=[('prediccion', 'IA de predicción'), ('segmentacion', 'IA de segmentación'), ('recomendacion', 'IA de recomendación')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='inteligencia_artificial_es',
            field=models.CharField(blank=True, choices=[('prediccion', 'IA de predicción'), ('segmentacion', 'IA de segmentación'), ('recomendacion', 'IA de recomendación')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='latencia_aproximada_en',
            field=models.CharField(blank=True, choices=[('500-800', 'Alta latencia (500–800 ms)'), ('300-500', 'Latencia elevada (300–500 ms)'), ('100-300', 'Latencia aceptable (100–300 ms)'), ('50-100', 'Baja latencia (50–100 ms)'), ('20-50', 'Muy baja latencia (20–50 ms)'), ('10-20', 'Latencia óptima (10–20 ms)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='latencia_aproximada_es',
            field=models.CharField(blank=True, choices=[('500-800', 'Alta latencia (500–800 ms)'), ('300-500', 'Latencia elevada (300–500 ms)'), ('100-300', 'Latencia aceptable (100–300 ms)'), ('50-100', 'Baja latencia (50–100 ms)'), ('20-50', 'Muy baja latencia (20–50 ms)'), ('10-20', 'Latencia óptima (10–20 ms)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='numero_procesos_en',
            field=models.CharField(blank=True, choices=[('5', '5 procesos'), ('10', '10 procesos'), ('20', '20 procesos'), ('40', '40 procesos'), ('80', '80 procesos'), ('100', '100 procesos'), ('200+', 'Más de 200 procesos')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='numero_procesos_es',
            field=models.CharField(blank=True, choices=[('5', '5 procesos'), ('10', '10 procesos'), ('20', '20 procesos'), ('40', '40 procesos'), ('80', '80 procesos'), ('100', '100 procesos'), ('200+', 'Más de 200 procesos')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='plataforma_en',
            field=models.CharField(blank=True, choices=[('ecommerce', 'Plataforma de Comercio Electrónico'), ('educacional', 'Plataforma Educativa Digital'), ('cadena_suministro', 'Sistema de Gestión de la Cadena de Suministro'), ('medico', 'Plataforma de Gestión Médica y Salud'), ('administracion_recursos', 'Plataforma de Administración de Recursos Empresariales'), ('gastronomia', 'Plataforma para Gestión de Recursos Gastronómicos')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='plataforma_es',
            field=models.CharField(blank=True, choices=[('ecommerce', 'Plataforma de Comercio Electrónico'), ('educacional', 'Plataforma Educativa Digital'), ('cadena_suministro', 'Sistema de Gestión de la Cadena de Suministro'), ('medico', 'Plataforma de Gestión Médica y Salud'), ('administracion_recursos', 'Plataforma de Administración de Recursos Empresariales'), ('gastronomia', 'Plataforma para Gestión de Recursos Gastronómicos')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='software_en',
            field=models.CharField(blank=True, choices=[('crm', 'SmartBusinessMedia - CRM'), ('erp', 'SmartBusinessAnalytics - ERP')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='software_es',
            field=models.CharField(blank=True, choices=[('crm', 'SmartBusinessMedia - CRM'), ('erp', 'SmartBusinessAnalytics - ERP')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='usuarios_simultaneos_en',
            field=models.CharField(blank=True, choices=[('10-50', 'Baja concurrencia (10–50 usuarios)'), ('50-150', 'Carga ligera (50–150 usuarios)'), ('150-500', 'Carga media (150–500 usuarios)'), ('500-1000', 'Alta concurrencia (500–1000 usuarios)'), ('1000-5000', 'Carga crítica (1000–5000 usuarios)'), ('5000+', 'Alta disponibilidad (>5000 usuarios simultáneos)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='usuarios_simultaneos_es',
            field=models.CharField(blank=True, choices=[('10-50', 'Baja concurrencia (10–50 usuarios)'), ('50-150', 'Carga ligera (50–150 usuarios)'), ('150-500', 'Carga media (150–500 usuarios)'), ('500-1000', 'Alta concurrencia (500–1000 usuarios)'), ('1000-5000', 'Carga crítica (1000–5000 usuarios)'), ('5000+', 'Alta disponibilidad (>5000 usuarios simultáneos)')], max_length=20, null=True),
        ),
    ]
