# Generated by Django 4.2.23 on 2025-08-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0007_category_automatizacion_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='automatizacion_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='automatizacion_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='inteligencia_artificial_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='inteligencia_artificial_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='latencia_aproximada_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='latencia_aproximada_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='nombre_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='nombre_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='numero_procesos_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='numero_procesos_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='plataforma_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='plataforma_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='software_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='software_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='usuarios_simultaneos_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='usuarios_simultaneos_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_es',
        ),
    ]
