# Generated by Django 4.2.23 on 2025-08-23 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0007_alter_category_automatizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Costo por Proceso', 'verbose_name_plural': 'Costos por Procesos'},
        ),
        migrations.AddField(
            model_name='product',
            name='almacenamiento_gb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Almacenamiento (GB)'),
        ),
        migrations.AddField(
            model_name='product',
            name='cloud_service_shared',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cloud Service Shared (Proveedor)'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_balanceador_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo/Mes Balanceador de Carga'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_bucket_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo/Mes por Bucket'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_cpu_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo/Mes por vCPU'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_hora_arquitectura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo/Hr Arquitectura'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_hora_desarrollo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo/Hr Desarrollo (D)'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_hora_implementacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo/Hr Implementación (I)'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_project_management',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo de PM (COSTO PM)'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_sre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo SRE'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_total_desarrollo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo Total Desarrollo (COSTO DEV)'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_total_nube',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costo Total en la Nube'),
        ),
        migrations.AddField(
            model_name='product',
            name='disponibilidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuarios Simultáneos / Disponibilidad / Nodo'),
        ),
        migrations.AddField(
            model_name='product',
            name='latencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latencia Aproximada'),
        ),
        migrations.AddField(
            model_name='product',
            name='margen_sq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Margen SQ (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='margen_sq_arch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Margen SQ Arquitectura (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='margen_sq_nube',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Margen SQ Nube (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='memoria_gb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Memoria (GB)'),
        ),
        migrations.AddField(
            model_name='product',
            name='numero_procesos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Procesos'),
        ),
        migrations.AddField(
            model_name='product',
            name='tiempo_arquitectura',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo Arquitectura (horas)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tiempo_desarrollo',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo Desarrollo (D) en horas'),
        ),
        migrations.AddField(
            model_name='product',
            name='tiempo_implementacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo Implementación (I) en horas'),
        ),
        migrations.AddField(
            model_name='product',
            name='tipo_arquitectura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Arquitectura'),
        ),
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total sin IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_arch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Arquitectura sin IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_arch_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Arquitectura con IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total con IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_nube',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Nube sin IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_nube_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Nube con IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='vcpu',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de vCPU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='SQShop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
