# Generated by Django 4.2.23 on 2025-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0009_product_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numero_procesos',
            field=models.CharField(blank=True, choices=[('5', '5 procesos'), ('10', '10 procesos'), ('20', '20 procesos'), ('40', '40 procesos'), ('80', '80 procesos'), ('100', '100 procesos'), ('200+', 'Más de 200 procesos')], default='5', max_length=5, null=True),
        ),
    ]
