# Generated by Django 4.2.23 on 2025-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0010_alter_product_numero_procesos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Impuesto al Valor agregado'),
        ),
    ]
