# Generated by Django 4.2.23 on 2025-08-28 15:53

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0014_product_costo_hora_desarrollo_paas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='almacenamiento_gb',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cloud_service_shared',
        ),
        migrations.RemoveField(
            model_name='product',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='product',
            name='latencia',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memoria_gb',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo_arquitectura',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vcpu',
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_balanceador_mes',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Costo Balanceador/Mes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_bucket_mes',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Costo Bucket/Mes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_cpu_mes',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Costo CPU/Mes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_hora_desarrollo',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Costo/Hr Desarrollo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_hora_implementacion',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Costo/Hr Implementación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_project_management',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Costo PM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_total_desarrollo',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Costo Total Desarrollo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_total_nube',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Costo Total Nube'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margen_sq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Margen Desarrollo (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margen_sq_arch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Margen Arquitectura (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margen_sq_nube',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Margen Nube (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margen_sq_paas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Margen PaaS (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tiempo_desarrollo',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo Desarrollo (horas)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tiempo_implementacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo Implementación (horas)'),
        ),
    ]
