# Generated by Django 4.2.23 on 2025-08-28 16:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0015_remove_product_almacenamiento_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='automatizacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('chatbots', 'Automatización mediante Chatbots'), ('email_marketing', 'Envío Automático de Correos Electrónicos'), ('facturacion', 'Facturación Electrónica Automatizada'), ('crm_automatizado', 'Automatización de CRM (Gestión de Clientes)'), ('reserva_online', 'Gestión Automatizada de Reservas o Citas'), ('notificaciones', 'Notificaciones Automatizadas en Tiempo Real'), ('reportes', 'Generación Automática de Reportes'), ('seguimiento_clientes', 'Seguimiento Automático de Clientes'), ('procesamiento_pedidos', 'Automatización del Procesamiento de Pedidos'), ('sistemas_alertas', 'Sistemas de Alertas Automatizadas')], max_length=152, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inteligencia_artificial',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('prediccion', 'Agente de IA de predicción'), ('segmentacion', 'Agente de IA de segmentación'), ('recomendacion', 'Agente de IA de recomendación')], max_length=37, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='latencia_aproximada',
            field=models.CharField(blank=True, choices=[('500-800', 'Alta latencia (500–800 ms)'), ('300-500', 'Latencia elevada (300–500 ms)'), ('100-300', 'Latencia aceptable (100–300 ms)'), ('50-100', 'Baja latencia (50–100 ms)'), ('20-50', 'Muy baja latencia (20–50 ms)'), ('10-20', 'Latencia óptima (10–20 ms)')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='plataforma',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ecommerce', 'Plataforma de Comercio Electrónico'), ('educacional', 'Plataforma Educativa Digital'), ('cadena_suministro', 'Sistema de Gestión de la Cadena de Suministro'), ('medico', 'Plataforma de Gestión Médica y Salud'), ('administracion_recursos', 'Plataforma de Administración de Recursos Empresariales'), ('gastronomia', 'Plataforma para Gestión de Recursos Gastronómicos')], max_length=82, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='software',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('crm', 'SmartBusinessMedia - CRM'), ('erp', 'SmartBusinessAnalytics - ERP')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usuarios_simultaneos',
            field=models.CharField(blank=True, choices=[('10-50', 'Baja concurrencia (10–50 usuarios)'), ('50-150', 'Carga ligera (50–150 usuarios)'), ('150-500', 'Carga media (150–500 usuarios)'), ('500-1000', 'Alta concurrencia (500–1000 usuarios)'), ('1000-5000', 'Carga crítica (1000–5000 usuarios)'), ('5000+', 'Alta disponibilidad (>5000 usuarios simultáneos)')], max_length=10, null=True),
        ),
    ]
