# Generated by Django 4.2.23 on 2025-08-28 17:50

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SQShop', '0016_product_automatizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='product',
            name='creado',
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_balanceador_mes',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_bucket_mes',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_cpu_mes',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_hora_arquitectura',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_hora_desarrollo',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_hora_desarrollo_paas',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_hora_implementacion',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_hora_implementacion_paas',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_project_management',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_sre',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_total_desarrollo',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_total_desarrollo_paas',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_total_implementacion_paas',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_total_nube',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='horas_implementacion_paas',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas Implementación PaaS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margen_sq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='margen_sq_arch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='margen_sq_nube',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='margen_sq_paas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tiempo_arquitectura',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas Arquitectura'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tiempo_desarrollo',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas Desarrollo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tiempo_implementacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas Implementación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_arch',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_arch_iva',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_iva',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_nube',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_nube_iva',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_paas',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_paas_iva',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
    ]
