# Generated by Django 4.2.30 on 2026-05-11 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_profile_tamano_empresa'),
        ('paas_orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paasorder',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='usuarios.smartquailcrew'),
        ),
    ]
