# Generated by Django 4.2.30 on 2026-05-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paas_orders', '0003_paasorder_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='paasorder',
            name='vence_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paasorder',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
