# Generated by Django 4.2.23 on 2025-10-16 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('progress', models.IntegerField(help_text='Progreso del 0 al 100 (%)')),
                ('has_automation', models.BooleanField(default=False)),
                ('automation_description', models.TextField(blank=True, null=True)),
                ('has_ai', models.BooleanField(default=False)),
                ('ai_model_description', models.TextField(blank=True, help_text='Describe el modelo de IA y su implementación en el proceso', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSystemProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QATest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('result', models.CharField(choices=[('passed', 'Aprobado'), ('failed', 'Fallido'), ('pending', 'Pendiente')], max_length=50)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.CharField(max_length=100)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_tests', to='business_customer_projects.businessprocess')),
            ],
        ),
        migrations.CreateModel(
            name='CloudResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('compute', 'Compute (VM, EC2, etc.)'), ('storage', 'Almacenamiento'), ('database', 'Base de Datos'), ('network', 'Red'), ('other', 'Otro')], max_length=50)),
                ('provider', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=100)),
                ('monthly_cost_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monitoring_tool', models.CharField(blank=True, max_length=100, null=True)),
                ('monitoring_status', models.CharField(choices=[('healthy', 'Operativo'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='healthy', max_length=50)),
                ('alert_summary', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_resources', to='business_customer_projects.businesssystemproject')),
            ],
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='business_customer_projects.businesssystemproject'),
        ),
    ]
