# Generated by Django 4.2.23 on 2026-02-11 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas_orders', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas_shop', '0001_initial'),
        ('business_customer_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qatest',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_tests', to='business_customer_projects.businessprocess'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='productos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas_shop.product', verbose_name='Producto asociado'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_customer_projects.businesssystemproject', verbose_name='Proyecto asociado'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='noticiametricas',
            name='noticia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='business_customer_projects.noticia'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='business_customer_projects.categorianoticia'),
        ),
        migrations.AddField(
            model_name='monthlysystemmetrics',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_metrics', to='business_customer_projects.businesssystemproject'),
        ),
        migrations.AddField(
            model_name='comentarionoticia',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='business_customer_projects.noticia'),
        ),
        migrations.AddField(
            model_name='comentarionoticia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cloudresource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_resources', to='business_customer_projects.businesssystemproject'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='crew_members',
            field=models.ManyToManyField(blank=True, related_name='projects', to='usuarios.smartquailcrew', verbose_name='Equipo asignado'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_projects', to='saas_shop.product', verbose_name='Producto asociado'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='saas_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_project', to='saas_orders.saasorder', verbose_name='Orden SaaS relacionada'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='assigned_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_processes', to='usuarios.smartquailcrew', verbose_name='Desarrollador asignado'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='business_customer_projects.businesssystemproject'),
        ),
        migrations.AddField(
            model_name='businessintelligent',
            name='assigned_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_intelligences', to='usuarios.smartquailcrew', verbose_name='Desarrollador asignado'),
        ),
        migrations.AddField(
            model_name='businessintelligent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligents', to='business_customer_projects.businesssystemproject'),
        ),
        migrations.AddField(
            model_name='businesscontracts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='business_customer_projects.businesssystemproject'),
        ),
        migrations.AddField(
            model_name='businessautomation',
            name='assigned_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_automations', to='usuarios.smartquailcrew', verbose_name='Desarrollador asignado'),
        ),
        migrations.AddField(
            model_name='businessautomation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='business_customer_projects.businesssystemproject'),
        ),
    ]
