# Generated by Django 4.2.23 on 2025-10-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_smartquailcrew_profile_picture'),
        ('business_customer_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='crew_members',
            field=models.ManyToManyField(blank=True, related_name='projects', to='usuarios.smartquailcrew', verbose_name='Equipo asignado'),
        ),
    ]
