# Generated by Django 4.2.23 on 2025-10-19 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_smartquailcrew_profile_picture'),
        ('business_customer_projects', '0002_businesssystemproject_crew_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='assigned_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_processes', to='usuarios.smartquailcrew', verbose_name='Desarrollador asignado'),
        ),
    ]
