# Generated by Django 4.2.23 on 2026-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen_informativo',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/informativo/'),
        ),
    ]
