# Generated by Django 4.2.30 on 2026-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='nombre_delegado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del delegado de proteccion de datos personales'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='nombre_encargado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de encargado de tratamiento de datos'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='nombre_responsable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de resposable de datos personales'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='politicas_privacidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de dominio privado'),
        ),
    ]
