# Generated by Django 4.2.23 on 2026-03-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0003_noticia_imagen_informativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='refencia_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='refencia_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='refencia_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='refencia_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
