# Generated by Django 4.2.30 on 2026-05-12 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paas_orders', '0003_paasorder_project_manager'),
        ('saas_orders', '0002_initial'),
        ('business_customer_projects', '0003_businesssystemproject_nombre_delegado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='paas_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_project_paas', to='paas_orders.paasorder', verbose_name='Asiganar licencia Platforms'),
        ),
        migrations.AlterField(
            model_name='businesssystemproject',
            name='logo_cuadrado',
            field=models.ImageField(blank=True, help_text='Formato recomendado: 4:1 (ancho:alto)', null=True, upload_to='business/logos/cuadrado/', verbose_name='Logotipo rectangular'),
        ),
        migrations.AlterField(
            model_name='businesssystemproject',
            name='logo_rectangular',
            field=models.ImageField(blank=True, help_text='Formato recomendado: 2:4 (ancho:alto)', null=True, upload_to='business/logos/rectangular/', verbose_name='Banner rectangular'),
        ),
        migrations.AlterField(
            model_name='businesssystemproject',
            name='saas_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_project', to='saas_orders.saasorder', verbose_name='Asignar licencia Apps'),
        ),
    ]
