# Generated by Django 4.2.23 on 2025-10-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0003_businessprocess_assigned_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='approved_by_client',
            field=models.BooleanField(default=False, verbose_name='¿Aprobado por cliente?'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='process_class',
            field=models.CharField(blank=True, choices=[('interview', 'Entrevistas'), ('erp_impl', 'Implementación ERP'), ('crm_impl', 'Implementación CRM'), ('uiux_dev', 'Desarrollo Interfase UI/UX'), ('architecture_dev', 'Desarrollo de Arquitectura')], max_length=30, null=True, verbose_name='Clase del proceso'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='process_type',
            field=models.CharField(blank=True, choices=[('I', 'Investigación'), ('D', 'Desarrollo')], max_length=1, null=True, verbose_name='Tipo de proceso'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='total_development_days',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Días de desarrollo'),
        ),
    ]
