# Generated by Django 4.2.23 on 2025-10-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0004_businessprocess_approved_by_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='technology_type',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=10, null=True, verbose_name='Tipo de Tecnología'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='process_class',
            field=models.CharField(blank=True, choices=[('interview', 'Entrevistas'), ('erp_impl', 'Implementación SmartBusinessAnalytics®-ERP'), ('crm_impl', 'Implementación SmartBusinessMedia®-CRM'), ('uiux_dev', 'Desarrollo Interfase UI/UX'), ('architecture_dev', 'Desarrollo de Arquitectura')], max_length=30, null=True, verbose_name='Clase del proceso'),
        ),
    ]
