# Generated by Django 4.2.23 on 2026-03-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0004_noticia_refencia_1_noticia_refencia_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprocess',
            old_name='total_storege_available',
            new_name='total_storage_available',
        ),
        migrations.RemoveField(
            model_name='businessprocess',
            name='store_consumption',
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='storage_consumption',
            field=models.FloatField(default=0, verbose_name='Consumo de almacenamiento (GB)'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='process_class',
            field=models.CharField(blank=True, choices=[('Investigación', 'Investigación'), ('Desarrollo', 'Desarrollo')], max_length=20, null=True, verbose_name='Clase del proceso'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='process_event',
            field=models.CharField(blank=True, choices=[('Entrevistas', 'Entrevistas'), ('Implementación SmartBusinessAnalytics®-ERP', 'Implementación SmartBusinessAnalytics®-ERP'), ('Implementación SmartBusinessMedia®-CRM', 'Implementación SmartBusinessMedia®-CRM'), ('Desarrollo Interfase UI/UX', 'Desarrollo Interfase UI/UX'), ('Desarrollo de Arquitectura', 'Desarrollo de Arquitectura')], max_length=120, null=True, verbose_name='Evento del proceso'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='storage_percent_used',
            field=models.FloatField(default=0, editable=False, verbose_name='Porcentaje de almacenamiento usado (%)'),
        ),
    ]
