# Generated by Django 4.2.30 on 2026-05-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paas_shop', '0004_remove_product_suite_product_suite'),
        ('saas_shop', '0002_alter_category_tamano_empresa'),
        ('business_customer_projects', '0005_businesssystemproject_product_paas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssystemproject',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='saas_shop.product', verbose_name='Asociar Aplicativo'),
        ),
        migrations.AlterField(
            model_name='businesssystemproject',
            name='product_paas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_paas', to='paas_shop.product', verbose_name='Asociar Plataforma'),
        ),
    ]
