# Generated by Django 4.2.23 on 2025-10-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0005_businessprocess_technology_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='final_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL final'),
        ),
    ]
