# Generated by Django 4.2.23 on 2026-04-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0005_rename_total_storege_available_businessprocess_total_storage_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='porcentaje_almacenamiento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='porcentaje_memoria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='porcentaje_procesamiento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
