# Generated by Django 4.2.23 on 2026-04-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0006_businesssystemproject_porcentaje_almacenamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='has_llm',
            field=models.BooleanField(default=False, verbose_name='¿Incluye LLM?'),
        ),
    ]
