# Generated by Django 4.2.23 on 2025-10-19 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_smartquailcrew_profile_picture'),
        ('business_customer_projects', '0006_businessprocess_final_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('progress', models.IntegerField(help_text='Progreso del 0 al 100 (%)')),
                ('automation_type', models.CharField(blank=True, choices=[('email', 'Email'), ('auto_auth', 'Autoidentificación'), ('report_gen', 'Generación de reportes'), ('chatbot', 'Chatbot para negocios'), ('data_sync', 'Sincronización de datos'), ('notification', 'Notificaciones automáticas'), ('workflow', 'Automatización de flujos de trabajo')], max_length=20, null=True, verbose_name='Tipo de automatización')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('approved_by_client', models.BooleanField(default=False, verbose_name='¿Aprobado por cliente?')),
                ('final_url', models.URLField(blank=True, null=True, verbose_name='URL final')),
                ('total_development_days', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Días de desarrollo')),
                ('assigned_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_automations', to='usuarios.smartquailcrew', verbose_name='Desarrollador asignado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='business_customer_projects.businesssystemproject')),
            ],
        ),
    ]
