# Generated by Django 4.2.23 on 2026-04-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0007_businesssystemproject_has_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='db_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de Base de datos'),
        ),
    ]
