# Generated by Django 4.2.23 on 2025-10-19 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_smartquailcrew_profile_picture'),
        ('business_customer_projects', '0007_businessautomation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIntelligent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('progress', models.IntegerField(help_text='Progreso del 0 al 100 (%)')),
                ('ai_type', models.CharField(blank=True, choices=[('binary_classification', 'Predicción por clasificación binaria'), ('regression', 'Predicción por regresión'), ('clustering', 'Clustering'), ('nlp', 'Procesamiento de Lenguaje Natural (NLP)'), ('image_recognition', 'Reconocimiento de imágenes'), ('recommendation', 'Sistemas de recomendación'), ('reinforcement_learning', 'Aprendizaje por refuerzo'), ('deep_learning', 'Deep Learning'), ('time_series', 'Series temporales')], max_length=30, null=True, verbose_name='Tipo de Inteligencia Artificial')),
                ('requires_gpu', models.BooleanField(default=False, help_text='Indica si el proyecto necesita procesamiento con GPU', verbose_name='¿Requiere GPU?')),
                ('model_accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='Precisión o métrica relevante del modelo', max_digits=5, null=True, verbose_name='Precisión del modelo (%)')),
                ('decision_maps', models.TextField(blank=True, help_text='Descripción o links a mapas de decisión, diagramas de árbol, u otras visualizaciones', null=True, verbose_name='Mapas de decisión / diagramas')),
                ('technical_notes', models.TextField(blank=True, help_text='Información técnica para garantizar la escalabilidad y confiabilidad del modelo', null=True, verbose_name='Notas técnicas adicionales')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('approved_by_client', models.BooleanField(default=False, verbose_name='¿Aprobado por cliente?')),
                ('final_url', models.URLField(blank=True, null=True, verbose_name='URL final')),
                ('total_development_days', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Días de desarrollo')),
                ('assigned_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_intelligences', to='usuarios.smartquailcrew', verbose_name='Desarrollador asignado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligences', to='business_customer_projects.businesssystemproject')),
            ],
        ),
    ]
