# Generated by Django 4.2.23 on 2026-04-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0008_businessprocess_db_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprocess',
            name='db_name',
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='db_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de base de datos'),
        ),
    ]
