# Generated by Django 4.2.23 on 2025-10-19 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0008_businessintelligent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessintelligent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligents', to='business_customer_projects.businesssystemproject'),
        ),
    ]
