# Generated by Django 4.2.23 on 2025-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0009_alter_businessintelligent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='business_sector',
            field=models.CharField(choices=[('gastronomico', 'Gastronómico'), ('servicios', 'Servicios'), ('administrativo', 'Administrativo'), ('finanzas', 'Finanzas'), ('banca', 'Banca'), ('gubernamental', 'Organización Gubernamental'), ('no_gubernamental', 'No Gubernamental'), ('comercio_electronico', 'Comercio Electrónico'), ('marketing_publicidad', 'Marketing y Publicidad'), ('educativo', 'Educativo'), ('medico_salud', 'Médico y Salud'), ('transporte', 'Transporte'), ('cadena_suministros', 'Cadena de Suministros'), ('agricultura', 'Agricultura')], default='gastronomico', max_length=50, verbose_name='Sector de Negocio'),
        ),
    ]
