# Generated by Django 4.2.23 on 2025-10-19 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0001_initial'),
        ('business_customer_projects', '0010_businesssystemproject_business_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_projects', to='saas_shop.product', verbose_name='Producto asociado'),
        ),
    ]
