# Generated by Django 4.2.23 on 2025-11-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0011_businesssystemproject_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='logo_cuadrado',
            field=models.ImageField(blank=True, null=True, upload_to='business/logos/cuadrado/', verbose_name='Logotipo cuadrado'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='logo_rectangular',
            field=models.ImageField(blank=True, null=True, upload_to='business/logos/rectangular/', verbose_name='Logotipo rectangular'),
        ),
    ]
