# Generated by Django 4.2.23 on 2025-11-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0012_businesssystemproject_logo_cuadrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progreso del 0 al 100 (%)'),
        ),
        migrations.AlterField(
            model_name='businesssystemproject',
            name='logo_cuadrado',
            field=models.ImageField(blank=True, help_text='Formato recomendado: 1:1 (ancho:alto)', null=True, upload_to='business/logos/cuadrado/', verbose_name='Logotipo cuadrado'),
        ),
        migrations.AlterField(
            model_name='businesssystemproject',
            name='logo_rectangular',
            field=models.ImageField(blank=True, help_text='Formato recomendado: 4:1 (ancho:alto)', null=True, upload_to='business/logos/rectangular/', verbose_name='Logotipo rectangular'),
        ),
        migrations.AlterField(
            model_name='businesssystemproject',
            name='name',
            field=models.CharField(help_text='Nombre del proyecto de sistema empresarial', max_length=200),
        ),
    ]
