# Generated by Django 4.2.23 on 2025-12-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0013_businesssystemproject_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qatest',
            name='executed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
