# Generated by Django 4.2.23 on 2025-12-03 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0007_category_tamano_empresa'),
        ('saas_orders', '0004_saasorder_email_sent'),
        ('business_customer_projects', '0014_alter_qatest_executed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='domain_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de dominio privado'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Proyecto activo?'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='is_domain_configured',
            field=models.BooleanField(default=False, verbose_name='¿Dispone de dominio privado?'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='public_domain',
            field=models.URLField(blank=True, null=True, verbose_name='Dominio público asignado'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='saas_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_project', to='saas_orders.saasorder', verbose_name='Orden SaaS relacionada'),
        ),
        migrations.AlterField(
            model_name='businesssystemproject',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_projects', to='saas_shop.product', verbose_name='Producto asociado'),
        ),
    ]
