# Generated by Django 4.2.23 on 2025-12-03 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0007_category_tamano_empresa'),
        ('business_customer_projects', '0015_businesssystemproject_domain_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssystemproject',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_projects', to='saas_shop.product', verbose_name='Producto asociado'),
        ),
    ]
