# Generated by Django 4.2.23 on 2025-12-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0016_alter_businesssystemproject_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='qatest',
            name='GPUs_used',
            field=models.CharField(blank=True, help_text='GPUs usadas milicore', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qatest',
            name='TPUs_used',
            field=models.CharField(blank=True, help_text='Tensor usadas milicore', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qatest',
            name='date_reviewed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qatest',
            name='latency_ms',
            field=models.FloatField(blank=True, help_text='Latencia en milisegundos', null=True),
        ),
        migrations.AddField(
            model_name='qatest',
            name='max_users',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='qatest',
            name='ram_used_gb',
            field=models.FloatField(blank=True, help_text='RAM usada en GB', null=True),
        ),
        migrations.AddField(
            model_name='qatest',
            name='server_type',
            field=models.CharField(blank=True, choices=[('dedicated', 'Servidor privado Dedicado'), ('shared', 'Servidor hibrido Compartido'), ('cloud', 'Servidor público en la Nube')], help_text='Tipo de servidor utilizado', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qatest',
            name='sketch_notes_stores',
            field=models.CharField(blank=True, help_text='Cronograma de backups DataBase', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qatest',
            name='storage_used_gb',
            field=models.FloatField(blank=True, help_text='Almacenamiento usado en GB', null=True),
        ),
        migrations.AddField(
            model_name='qatest',
            name='update_resources_used_pocentage',
            field=models.FloatField(blank=True, help_text='Porcentaje de uso de recursos durante la prueba', null=True),
        ),
        migrations.AddField(
            model_name='qatest',
            name='uptime_percentage',
            field=models.FloatField(blank=True, help_text='Porcentaje de tiempo activo durante la prueba', null=True),
        ),
        migrations.AddField(
            model_name='qatest',
            name='vCPUs_used',
            field=models.IntegerField(blank=True, help_text='vCPUs usadas milicore', null=True),
        ),
        migrations.AlterField(
            model_name='qatest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qatest',
            name='test_case',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
