# Generated by Django 4.2.23 on 2025-12-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0017_qatest_gpus_used_qatest_tpus_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudresource',
            name='GPUs_used',
            field=models.CharField(blank=True, help_text='GPUs usadas milicore', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cloudresource',
            name='TPUs_used',
            field=models.CharField(blank=True, help_text='Tensor usadas milicore', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cloudresource',
            name='ram_used_gb',
            field=models.FloatField(blank=True, help_text='RAM usada en GB', null=True),
        ),
        migrations.AddField(
            model_name='cloudresource',
            name='storage_used_gb',
            field=models.FloatField(blank=True, help_text='Almacenamiento usado en GB', null=True),
        ),
        migrations.AddField(
            model_name='cloudresource',
            name='update_resources_used_pocentage',
            field=models.FloatField(blank=True, help_text='Porcentaje de uso de recursos durante la prueba final', null=True),
        ),
        migrations.AddField(
            model_name='cloudresource',
            name='vCPUs_used',
            field=models.IntegerField(blank=True, help_text='vCPUs usadas milicore', null=True),
        ),
    ]
