# Generated by Django 4.2.23 on 2025-12-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0018_cloudresource_gpus_used_cloudresource_tpus_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='numero_maximo_procesos',
            field=models.IntegerField(default=1),
        ),
    ]
