# Generated by Django 4.2.23 on 2025-12-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0020_alter_businessintelligent_ai_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssystemproject',
            name='name',
            field=models.CharField(default='ITC Busibess in progress', help_text='Nombre del proyecto de sistema empresarial', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesssystemproject',
            name='progress',
            field=models.IntegerField(default=10, help_text='Progreso del 0 al 100 (%)'),
        ),
    ]
