# Generated by Django 4.2.23 on 2025-12-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0021_alter_businesssystemproject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssystemproject',
            name='name',
            field=models.CharField(default='Iniciando ITC Business', help_text='Nombre del proyecto de sistema empresarial', max_length=200),
        ),
    ]
