# Generated by Django 4.2.23 on 2025-12-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0022_alter_businesssystemproject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='has_ai',
            field=models.BooleanField(default=False, verbose_name='¿Incluye inteligencia artificial?'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='has_automation',
            field=models.BooleanField(default=False, verbose_name='¿Incluye automatización?'),
        ),
        migrations.AlterField(
            model_name='businesssystemproject',
            name='name',
            field=models.CharField(default='Iniciando', help_text='Nombre del proyecto de sistema empresarial', max_length=200),
        ),
    ]
