# Generated by Django 4.2.23 on 2025-12-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0023_businesssystemproject_has_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='almacenamiento_aproximado_gb',
            field=models.IntegerField(blank=True, help_text='Almacenamiento estimado en GB', null=True, verbose_name='Almacenamiento aproximado (GB)'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='latencia_aproximada_ms',
            field=models.IntegerField(blank=True, help_text='Latencia estimada del sistema en milisegundos', null=True, verbose_name='Latencia aproximada (ms)'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='memoria_aproximada_gb',
            field=models.IntegerField(blank=True, help_text='Memoria estimada en GB', null=True, verbose_name='Memoria aproximada (GB)'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='procesamiento_aproximado_vcpu',
            field=models.IntegerField(blank=True, help_text='Procesamiento estimado en vCPU milicore', null=True, verbose_name='Procesamiento aproximado (vCPU milicore)'),
        ),
    ]
