# Generated by Django 4.2.23 on 2025-12-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0024_businesssystemproject_almacenamiento_aproximado_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='usuarios_max',
            field=models.IntegerField(default=1, verbose_name='Número máximo de usuarios simultáneos'),
        ),
    ]
