# Generated by Django 4.2.23 on 2025-12-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0025_businesssystemproject_usuarios_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='active_processes_aproximados',
            field=models.IntegerField(blank=True, help_text='Número estimado de procesos activos', null=True, verbose_name='Procesos activos aproximados'),
        ),
    ]
