# Generated by Django 4.2.23 on 2025-12-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0026_businesssystemproject_active_processes_aproximados'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='almacenamiento_total_mb',
            field=models.IntegerField(blank=True, help_text='Almacenamiento total en GB', null=True, verbose_name='Almacenamiento total (GB)'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='memoria_total',
            field=models.IntegerField(blank=True, help_text='Memoria total en MB', null=True, verbose_name='Memoria total (MB)'),
        ),
        migrations.AddField(
            model_name='businesssystemproject',
            name='procesamiento_total_aproximado_millicore',
            field=models.IntegerField(blank=True, help_text='Procesamiento total estimado en millicore', null=True, verbose_name='Procesamiento total aproximado (millicore)'),
        ),
    ]
