# Generated by Django 4.2.23 on 2025-12-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0027_businesssystemproject_almacenamiento_total_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemproject',
            name='velocity_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Puntuación de velocidad del sistema'),
        ),
    ]
