# Generated by Django 4.2.23 on 2025-12-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0028_businesssystemproject_velocity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprocess',
            name='process_type',
            field=models.CharField(blank=True, choices=[('Administrativo', 'Administrativo'), ('Financiero', 'Financiero'), ('Recursos Humanos', 'Recursos Humanos'), ('Ventas', 'Ventas'), ('Marketing', 'Marketing'), ('Operaciones', 'Operaciones'), ('Cadena de Suministros', 'Cadena de Suministros'), ('Productos y Servicios', 'Productos y Servicios')], max_length=32, null=True, verbose_name='Tipo de proceso'),
        ),
    ]
