# Generated by Django 4.2.23 on 2025-12-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0029_alter_businessprocess_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='process_event',
            field=models.CharField(blank=True, choices=[('Entrevistas', 'Entrevistas'), ('Implementación SmartBusinessAnalytics®-ERP', 'Implementación SmartBusinessAnalytics®-ERP'), ('Implementación SmartBusinessMedia®-CRM', 'Implementación SmartBusinessMedia®-CRM'), ('Desarrollo Interfase UI/UX', 'Desarrollo Interfase UI/UX'), ('Desarrollo de Arquitectura', 'Desarrollo de Arquitectura')], max_length=120, null=True, verbose_name='Clase del proceso'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='process_class',
            field=models.CharField(blank=True, choices=[('Investigación', 'Investigación'), ('Desarrollo', 'Desarrollo')], max_length=20, null=True, verbose_name='Tipo de proceso'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='technology_type',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=60, null=True, verbose_name='Tipo de Tecnología'),
        ),
    ]
