# Generated by Django 4.2.23 on 2025-12-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0030_businessprocess_process_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='cpu_consumption_cores',
            field=models.FloatField(blank=True, help_text='Cantidad estimada de núcleos de CPU consumidos por el proceso', null=True, verbose_name='Consumo de CPU (Cores)'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='memory_consumption_mb',
            field=models.FloatField(blank=True, help_text='Cantidad estimada de memoria consumida por el proceso en MB', null=True, verbose_name='Consumo de memoria (MB)'),
        ),
    ]
