# Generated by Django 4.2.23 on 2025-12-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0031_businessprocess_cpu_consumption_cores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprocess',
            name='cpu_consumption_cores',
        ),
        migrations.RemoveField(
            model_name='businessprocess',
            name='memory_consumption_mb',
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='cpu_consumption',
            field=models.FloatField(default=0, verbose_name='Consumo de procesamiento (Cores)'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='memory_consumption',
            field=models.FloatField(default=0, verbose_name='Consumo de memoria (MB)'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='total_cpu_available',
            field=models.FloatField(default=8, verbose_name='Procesamiento total disponible (Cores)'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='total_memory_available',
            field=models.FloatField(default=1024, verbose_name='Memoria total disponible (MB)'),
        ),
    ]
