# Generated by Django 4.2.23 on 2025-12-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0032_remove_businessprocess_cpu_consumption_cores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='cpu_percent_used',
            field=models.FloatField(default=0, editable=False, verbose_name='Porcentaje de CPU usada (%)'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='memory_percent_used',
            field=models.FloatField(default=0, editable=False, verbose_name='Porcentaje de memoria usada (%)'),
        ),
    ]
