# Generated by Django 4.2.23 on 2025-12-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0033_businessprocess_cpu_percent_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessautomation',
            name='automation_category',
            field=models.CharField(blank=True, choices=[('communication', 'Automatización de comunicación'), ('workflow', 'Flujos de trabajo'), ('integration', 'Integraciones entre sistemas'), ('monitoring', 'Monitoreo y alertas'), ('security', 'Seguridad y autenticación'), ('data_ops', 'Operaciones de datos'), ('business_ops', 'Operaciones de negocio'), ('etl', 'Pipelines ETL')], max_length=40, null=True, verbose_name='Categoría de automatización'),
        ),
        migrations.AddField(
            model_name='businessautomation',
            name='microservice_type',
            field=models.CharField(blank=True, choices=[('django_task', 'Microservicio Django / Celery'), ('n8n', 'Workflow n8n'), ('rabbitmq', 'Colas RabbitMQ'), ('redis_queue', 'Redis Queue / Pub-Sub'), ('kafka', 'Apache Kafka — Streaming de datos'), ('elasticsearch', 'Elasticsearch — Logs y monitoreo'), ('logstash', 'Logstash — Procesamiento de logs'), ('kibana', 'Kibana — Dashboards'), ('postfix', 'Postfix — Servidor SMTP'), ('dovecot', 'Dovecot — Servidor IMAP'), ('cron_service', 'Sistema de cron / scheduler'), ('external_api', 'Microservicio de automatización externo'), ('standalone_service', 'Servicio independiente'), ('hybrid', 'Híbrido Django + n8n + colas')], max_length=40, null=True, verbose_name='Microservicio utilizado'),
        ),
        migrations.AddField(
            model_name='businessautomation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título de la automatización'),
        ),
        migrations.AlterField(
            model_name='businessautomation',
            name='automation_type',
            field=models.CharField(blank=True, choices=[('email_auto', 'Envío automático de emails'), ('sms_auto', 'Envío automático de SMS'), ('whatsapp_bot', 'Bot automatizado de WhatsApp'), ('push_notifications', 'Notificaciones push'), ('email_marketing', 'Email marketing'), ('task_automation', 'Automatización de tareas'), ('approval_workflow', 'Flujos de aprobación'), ('document_workflow', 'Flujos de documentos'), ('cron_job', 'Tareas programadas'), ('user_onboarding', 'Onboarding de usuarios'), ('api_sync', 'Sincronización con APIs'), ('crm_sync', 'Integración con CRM'), ('erp_sync', 'Integración con ERP'), ('webhook_forward', 'Enrutamiento de webhooks'), ('slack_integration', 'Integración con Slack'), ('teams_integration', 'Integración con Teams'), ('uptime_monitor', 'Monitoreo de disponibilidad'), ('error_alerts', 'Alertas de errores'), ('system_logs', 'Procesamiento de logs'), ('two_factor_flow', 'Flujos 2FA'), ('data_import', 'Importación de datos'), ('data_export', 'Exportación de datos'), ('db_backup', 'Backups automáticos'), ('csv_processing', 'Procesamiento de CSV/Excel'), ('pipeline_etl', 'ETL Pipelines'), ('data_cleaning', 'Limpieza de datos'), ('invoice_automation', 'Automatización de facturación'), ('inventory_update', 'Actualización de inventario'), ('order_processing', 'Procesamiento de pedidos'), ('contract_generation', 'Generación automática de documentos'), ('reminders', 'Recordatorios automáticos')], max_length=50, null=True, verbose_name='Tipo de automatización'),
        ),
        migrations.AlterField(
            model_name='businessautomation',
            name='description',
            field=models.TextField(verbose_name='Descripción de la automatización'),
        ),
        migrations.AlterField(
            model_name='businessautomation',
            name='progress',
            field=models.IntegerField(help_text='Valor entre 0 y 100', verbose_name='Progreso (%)'),
        ),
    ]
