# Generated by Django 4.2.23 on 2025-12-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0034_businessautomation_automation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessautomation',
            name='integration_type',
            field=models.CharField(blank=True, choices=[('gov_api', 'APIs gubernamentales'), ('social_media', 'Redes sociales'), ('electronic_billing', 'Facturación electrónica'), ('contract_certification', 'Certificación de contratos')], max_length=50, null=True, verbose_name='Tipo de integración a terceros'),
        ),
    ]
