# Generated by Django 4.2.23 on 2025-12-11 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0035_businessautomation_integration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Contrato')),
                ('tipo', models.CharField(choices=[('ip', 'Contrato de Propiedad Intelectual'), ('cloud_services', 'Contrato de Servicios de Nube'), ('development', 'Contrato de Desarrollo e Implementación de Procesos')], max_length=50, verbose_name='Tipo de Contrato')),
                ('archivo', models.FileField(upload_to='contracts/', verbose_name='Archivo del Contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='business_customer_projects.businesssystemproject')),
            ],
        ),
    ]
