# Generated by Django 4.2.23 on 2025-12-12 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0007_category_tamano_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_customer_projects', '0036_businesscontracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('company_ruc', models.CharField(max_length=20, verbose_name='RUC')),
                ('service_type', models.CharField(choices=[('cloud_services', 'Servicios de Nube'), ('consulting_ticket', 'Ticket de Consulta'), ('strategic_agreement', 'Convenio Estratégico'), ('infrastructure', 'Infraestructura'), ('monitoring', 'Monitoreo'), ('security_support', 'Seguridad y Soporte')], max_length=50, verbose_name='Tipo de Servicio')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IVA (%)')),
                ('date_issued', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('expiration_date', models.DateField(verbose_name='Fecha de Expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas_shop.product', verbose_name='Producto asociado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden de Pago',
                'verbose_name_plural': 'Órdenes de Pago',
            },
        ),
    ]
