# Generated by Django 4.2.23 on 2025-12-12 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_customer_projects', '0037_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_customer_projects.businesssystemproject', verbose_name='Proyecto asociado'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
