# Generated by Django 4.2.23 on 2025-12-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0038_paymentorder_project_alter_paymentorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='pago_verificado',
            field=models.BooleanField(default=False, verbose_name='¿Pago Verificado en Bancos?'),
        ),
    ]
