# Generated by Django 4.2.23 on 2025-12-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0039_paymentorder_pago_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Archivo de Factura'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Serie de Factura'),
        ),
    ]
