# Generated by Django 4.2.23 on 2025-12-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0040_paymentorder_invoice_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='noticias/portadas/')),
                ('imagen_comercial', models.ImageField(blank=True, null=True, upload_to='noticias/comercial/')),
                ('imagen_datos_estadisticos', models.ImageField(blank=True, null=True, upload_to='noticias/estadisticas/')),
                ('titulo_1', models.CharField(max_length=255)),
                ('titulo_2', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo_3', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo_1', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo_2', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo_3', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo_4', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo_5', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo_6', models.CharField(blank=True, max_length=255, null=True)),
                ('cuerpo_1', models.TextField()),
                ('cuerpo_2', models.TextField(blank=True, null=True)),
                ('cuerpo_3', models.TextField(blank=True, null=True)),
                ('cuerpo_4', models.TextField(blank=True, null=True)),
                ('cuerpo_5', models.TextField(blank=True, null=True)),
                ('cuerpo_6', models.TextField(blank=True, null=True)),
                ('cuerpo_7', models.TextField(blank=True, null=True)),
                ('cuerpo_8', models.TextField(blank=True, null=True)),
                ('cuerpo_9', models.TextField(blank=True, null=True)),
                ('autor_nombre', models.CharField(max_length=150)),
                ('autor_bio', models.TextField(blank=True, null=True)),
                ('autor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('autor_foto', models.ImageField(blank=True, null=True, upload_to='noticias/autores/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
