# Generated by Django 4.2.23 on 2025-12-19 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0042_comentarionoticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaMetricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('compartidos_redes', models.PositiveIntegerField(default=0)),
                ('compartidos_email', models.PositiveIntegerField(default=0)),
                ('descargas', models.PositiveIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('noticia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='business_customer_projects.noticia')),
            ],
        ),
    ]
