# Generated by Django 4.2.23 on 2025-12-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0043_noticiametricas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ITC', 'ITC – Tecnologías de Información y Comunicación en la Nube'), ('ID', 'I+D – Investigación y Desarrollo'), ('AUT', '+A – Automatización de Procesos de Información'), ('IA', '+AI – Inteligencia Artificial y Machine Learning')], max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Noticia',
                'verbose_name_plural': 'Categorías de Noticias',
                'ordering': ['nombre'],
            },
        ),
    ]
