# Generated by Django 4.2.23 on 2025-12-22 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_customer_projects', '0045_noticia_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('cloud', 'Computación en la nube'), ('courses', 'Talleres y cursos de arquitectura cloud'), ('design', 'Diseño de soluciones'), ('security', 'Respaldo y seguridad'), ('ai', 'Inteligencia Artificial'), ('ml', 'Machine Learning')], max_length=20)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('has_cost', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categorianoticia',
            name='nombre',
            field=models.CharField(choices=[('ITC', 'Tecnologías de Información y Comunicación en la Nube'), ('ID', 'Investigación y Desarrollo'), ('AUT', 'Automatización de Procesos de Información'), ('IA', 'Inteligencia Artificial y Machine Learning'), ('SAFE', 'Seguridad'), ('monitoring', 'monitoring'), ('privacidad', 'privacidad')], max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('cloud_free', 'Consulta sobre tecnologías cloud (Sin costo)'), ('courses_free', 'Consultas sobre talleres y cursos cloud (Sin costo)'), ('design_paid', 'Diseño de arquitecturas cloud (Con costo)'), ('security_paid', 'Respaldo y seguridad (Con costo)'), ('ai_paid', 'Inteligencia Artificial (Con costo)'), ('ml_paid', 'Machine Learning (Con costo)')], max_length=30)),
                ('area', models.CharField(choices=[('cloud', 'Computación en la nube'), ('courses', 'Talleres y cursos'), ('design', 'Diseño de soluciones'), ('security', 'Respaldo y seguridad'), ('ai', 'Inteligencia Artificial'), ('ml', 'Machine Learning')], max_length=20)),
                ('question', models.CharField(choices=[('q_cloud_1', '¿Qué proveedor de nube es más conveniente según mi presupuesto?'), ('q_cloud_2', '¿Cómo migrar una aplicación local a la nube?'), ('q_cloud_3', '¿Qué diferencia hay entre IaaS, PaaS y SaaS?'), ('q_cloud_4', '¿Cómo escalar automáticamente una aplicación en la nube?'), ('q_cloud_5', '¿Cómo reducir costos en infraestructura cloud?'), ('q_cloud_6', '¿Qué región de nube debo elegir y por qué?'), ('q_course_1', '¿Qué conocimientos previos necesito para tomar un curso de arquitectura cloud?'), ('q_course_2', '¿Los talleres incluyen prácticas reales?'), ('q_course_3', '¿Qué certificaciones cloud recomiendan después del curso?'), ('q_course_4', '¿Los cursos están orientados a AWS, Azure o Google Cloud?'), ('q_course_5', '¿Se entregan materiales o grabaciones de las sesiones?'), ('q_course_6', '¿Los cursos sirven para certificaciones oficiales?'), ('q_design_1', '¿Cómo diseñar una arquitectura altamente disponible?'), ('q_design_2', '¿Qué patrón de arquitectura es adecuado para mi aplicación?'), ('q_design_3', '¿Cómo implementar balanceo de carga y alta disponibilidad?'), ('q_design_4', '¿Cómo diseñar una solución cloud segura y escalable?'), ('q_security_1', '¿Cómo implementar un plan de respaldo y recuperación ante desastres?'), ('q_security_2', '¿Cómo proteger datos sensibles en la nube?'), ('q_security_3', '¿Cómo cifrar datos en tránsito y en reposo?'), ('q_security_4', '¿Cómo detectar y responder a incidentes de seguridad?'), ('q_ai_1', '¿Cómo aplicar inteligencia artificial a mi negocio?'), ('q_ai_2', '¿Qué datos necesito para implementar un sistema de IA?'), ('q_ai_3', '¿Qué servicios cloud ofrecen IA preentrenada?'), ('q_ml_1', '¿Qué diferencia hay entre IA y Machine Learning?'), ('q_ml_2', '¿Cómo entrenar un modelo de machine learning en la nube?'), ('q_ml_3', '¿Cómo desplegar un modelo de ML en producción?')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_datetime', models.DateTimeField(help_text='Fecha y hora seleccionada por el usuario para la consulta')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('finished', 'Terminado')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
