# Generated by Django 4.2.23 on 2025-12-23 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0046_consultationquestion_consultationtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('almacenamiento_gb', models.FloatField(blank=True, null=True)),
                ('procesamiento_millicore', models.FloatField(blank=True, null=True)),
                ('memoria_gb', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_metrics', to='business_customer_projects.businesssystemproject')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
