# Generated by Django 4.2.23 on 2025-12-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0047_monthlysystemmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysystemmetrics',
            name='date_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysystemmetrics',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
