# Generated by Django 4.2.23 on 2025-12-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0048_monthlysystemmetrics_date_final_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlysystemmetrics',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='monthlysystemmetrics',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='monthlysystemmetrics',
            name='date_final',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
