# Generated by Django 4.2.23 on 2025-12-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_customer_projects', '0052_alter_monthlysystemmetrics_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='storage_percent_used',
            field=models.FloatField(default=0, editable=False, verbose_name='Porcentaje de CPU usada (%)'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='store_consumption',
            field=models.FloatField(default=0, verbose_name='Consumo de Almacenamiento (GB)'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='total_storege_available',
            field=models.FloatField(default=8, verbose_name='Almacenamiento total disponible (GB)'),
        ),
    ]
