# Generated by Django 5.2.13 on 2026-04-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbtshop', '0002_alter_category_slug_alter_sbtproduct_slug'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sbtproduct',
            new_name='sbtshop_sbt_id_468585_idx',
            old_fields=('id', 'slug'),
        ),
    ]
