# Generated by Django 4.2.23 on 2025-09-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_ruc', models.CharField(max_length=13)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('xml_signed', models.TextField(blank=True, null=True)),
                ('sri_status', models.CharField(default='pendiente', max_length=50)),
                ('access_key', models.CharField(max_length=49, unique=True)),
            ],
        ),
    ]
