# Generated by Django 4.2.30 on 2026-04-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('amount_without_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_with_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_file', models.FileField(upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ManyToManyField(related_name='invoices', to='saas_shop.product')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturación',
                'ordering': ['-created_at'],
            },
        ),
    ]
