# Generated by Django 5.2.13 on 2026-04-26 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('business_customer_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='business_customer_projects.businesssystemproject'),
        ),
    ]
