# Generated by Django 4.2.23 on 2026-02-11 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('business_customer_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='business_customer_projects.businesssystemproject'),
        ),
    ]
