# Generated by Django 4.2.23 on 2025-08-31 22:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sbmcoupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('sbmmodels_p1', ckeditor.fields.RichTextField(blank=True)),
                ('sbmmodels_p2', ckeditor.fields.RichTextField(blank=True)),
                ('sbmmodels_p3', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SBMProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/bannering/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/scren1/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/scren2/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/scren3/%Y/%m/%d')),
                ('background', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/background/%Y/%m/%d')),
                ('item1', models.TextField(blank=True, null=True)),
                ('item2', models.TextField(blank=True, null=True)),
                ('item3', models.TextField(blank=True, null=True)),
                ('item4', models.TextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('datasheet', models.TextField(blank=True)),
                ('terms_policies', ckeditor.fields.RichTextField(blank=True)),
                ('cloud_requirements', ckeditor.fields.RichTextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(blank=True, choices=[('icofont-legal', 'icofont-legal'), ('icofont-law-book', 'icofont-law-book'), ('icofont-ebook', 'icofont-ebook'), ('icofont-ui-office', 'icofont-ui-office'), ('icofont-list', 'icofont-list'), ('icofont-key', 'icofont-key')], db_index=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, choices=[('rgb(133, 54, 140)', 'SBM-CRM+AI+I+D'), ('#262625', 'SBM-CRM'), ('#662d14', 'SBM-CRM+A'), ('#247832', 'SBM-CRM+I+D'), ('#7c7a21', 'SBM-CRM+A+I+D'), ('#283f75', 'SBM-CRM+AI'), ('#388e86', 'SBM-CRM+A+AI'), ('#251f25', 'SBM-CRM+A+AI+I+D')], db_index=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sbmshop.category')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='sbmcoupons.coupon')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SBMTechnologiesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('Node_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('App_type', models.CharField(blank=True, choices=[('Simple IT Cloud Web App+CRM', 'Simple IT Cloud Web App+CRM'), ('Simple IT Cloud Web App+CRM+I+D', 'Simple IT Cloud Web App+CRM+I+D'), ('Simple IT Cloud Web App+CRM+I+D+A', 'Simple IT Cloud Web App+CRM+I+D+A'), ('Simple IT Cloud Web App+CRM+A', 'Simple IT Cloud Web App+CRM+A'), ('Simple IT Cloud Web App+CRM+AI', 'Simple IT Cloud Web App+CRM+AI'), ('Simple IT Cloud Web App+CRM+AI+A', 'Simple IT Cloud Web App+CRM+AI+A'), ('Simple IT Cloud Web App+CRM+AI+I+D', 'Simple IT Cloud Web App+CRM+AI+I+D'), ('Simple IT Cloud Web App+CRM+AI+A+I+D', 'Simple IT Cloud Web App+CRM+AI+A+I+D')], db_index=True, max_length=500, null=True)),
                ('Domain', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('Types_reliable_systems', models.CharField(blank=True, choices=[('Low ', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, max_length=500, null=True)),
                ('procesing_resourse', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('memory_resourse', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('storge_resourse', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sbmproductstechno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies_products', to='sbmshop.sbmproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SBMStaffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_name', models.CharField(db_index=True, max_length=200)),
                ('ceo_lastname', models.CharField(db_index=True, max_length=200)),
                ('ceo_sector', models.CharField(choices=[('SmartBusinessMedia Community Manager', 'SmartBusinessMedia Community Manager'), ('Chief Officer of Technologies', 'Chief Officer of Technologies'), ('SmartBusinessMedia Project Manager', 'SmartBusinessMedia Project Manager'), ('Chief Officer SmartBusinessMedia', 'Chief Officer SmartBusinessMedia ')], db_index=True, max_length=200)),
                ('ceo_profile_img', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/sbmstaff/%Y/%m/%d')),
                ('sbmproducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffproducts', to='sbmshop.sbmproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SBMProductManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/background/%Y/%m/%d')),
                ('bg_image', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/background/%Y/%m/%d')),
                ('color', models.CharField(blank=True, choices=[('rgb(133, 54, 140)', 'SBM-CRM+AI+I+D'), ('#0d0d0d', 'SBM-CRM'), ('#662d14', 'SBM-CRM+A'), ('#247832', 'SBM-CRM+I+D'), ('#7c7a21', 'SBM-CRM+A+I+D'), ('#283f75', 'SBM-CRM+AI'), ('#388e86', 'SBM-CRM+A+AI'), ('#251f25', 'SBM-CRM+A+AI+I+D')], db_index=True, max_length=200, null=True)),
                ('title_intro', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('subtitle_title_intro', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sbmshop.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sbmshop.sbmproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ManualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_intro', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('subtitle_title_intro', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True)),
                ('manuales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sbmshop.sbmproductmanual')),
            ],
        ),
    ]
