# Generated by Django 4.2.23 on 2025-10-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tech_type',
            field=models.CharField(blank=True, choices=[('Investigación y Desarollo', '(I+D)'), ('Automatizacion', '(+A)+(I+D)'), ('Inteligencia Artificial', '(+AI)+(I+D)'), ('Automatizacion y Inteligencia Artificial', '(+A)+(+AI)+(I+D)')], db_index=True, max_length=200, null=True),
        ),
    ]
