# Generated by Django 4.2.23 on 2025-10-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0002_category_tech_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbmtechnologiesitem',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='products/smartbusinessmedia/sbmtechnologies/%Y/%m/%d'),
        ),
    ]
