# Generated by Django 4.2.23 on 2026-03-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbmproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
