# Generated by Django 5.2.13 on 2026-04-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0003_alter_sbmproduct_slug'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sbmproduct',
            new_name='sbmshop_sbm_id_ff0f13_idx',
            old_fields=('id', 'slug'),
        ),
    ]
