# Generated by Django 4.2.23 on 2026-03-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iaasorder',
            name='is_progress',
            field=models.BooleanField(default=False, verbose_name='Esta en Progreso'),
        ),
    ]
