# Generated by Django 5.2.13 on 2026-04-26 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iaas_orders', '0001_initial'),
        ('iaas_shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iaasorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iaas_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iaasorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='iaas_orders.iaasorder'),
        ),
        migrations.AddField(
            model_name='iaasorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_order_items', to='iaas_shop.product'),
        ),
    ]
