# Generated by Django 4.2.30 on 2026-06-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbpshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbpstaffitem',
            old_name='sbmproducts',
            new_name='sbpproducts',
        ),
        migrations.RenameField(
            model_name='sbptechnologiesitem',
            old_name='sbmproductstechno',
            new_name='sbpproductstechno',
        ),
        migrations.AlterField(
            model_name='sbpproduct',
            name='background',
            field=models.ImageField(blank=True, upload_to='products/smartbusinessplatforms/background/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sbpproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/smartbusinessplatforms/bannering/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sbpproduct',
            name='image1',
            field=models.ImageField(blank=True, upload_to='products/smartbusinessplatforms/scren1/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sbpproduct',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/smartbusinessplatforms/scren2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sbpproduct',
            name='image3',
            field=models.ImageField(blank=True, upload_to='products/smartbusinessplatforms/scren3/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sbpstaffitem',
            name='ceo_profile_img',
            field=models.ImageField(blank=True, upload_to='products/smartbusinessmedia/sbpstaff/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sbptechnologiesitem',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='products/smartbusinessmedia/sbptechnologies/%Y/%m/%d'),
        ),
    ]
