# Generated by Django 5.2.13 on 2026-04-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbpshop', '0002_alter_category_slug_alter_sbpproduct_slug'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sbpproduct',
            new_name='sbpshop_sbp_id_037e76_idx',
            old_fields=('id', 'slug'),
        ),
    ]
