# Generated by Django 4.2.23 on 2025-09-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('saas_shop', '0001_initial'),
        ('saas_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='SaaSOrder',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='SaaSOrderItem',
        ),
        migrations.AlterField(
            model_name='saasorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_order_items', to='saas_shop.product'),
        ),
    ]
