# Generated by Django 4.2.23 on 2026-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='is_progress',
            field=models.BooleanField(default=False, verbose_name='Esta en Progreso'),
        ),
    ]
