# Generated by Django 4.2.23 on 2025-11-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Acepta términos y condiciones'),
        ),
    ]
