# Generated by Django 4.2.30 on 2026-05-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='vence_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
