# Generated by Django 4.2.23 on 2025-09-20 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasorder',
            name='telefono',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese solo los 9 dígitos del número de teléfono, sin el prefijo +593.', regex='^\\d{9}$')]),
        ),
    ]
