# Generated by Django 4.2.30 on 2026-05-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_customuser_telefono'),
        ('paas_shop', '0004_remove_product_suite_product_suite'),
        ('paas_coupons', '0004_alter_coupon_credito'),
        ('saas_orders', '0003_saasorder_vence_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saasorder',
            options={'ordering': ('-created',), 'verbose_name': 'Software As Service Order', 'verbose_name_plural': 'PaaS Orders'},
        ),
        migrations.RemoveField(
            model_name='saasorder',
            name='vence_en',
        ),
        migrations.AddField(
            model_name='saasorder',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager_saas', to='usuarios.smartquailcrew'),
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_orders', to='paas_coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='saasorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_order_items', to='paas_shop.product'),
        ),
    ]
