# Generated by Django 4.2.23 on 2025-11-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0003_saasorder_is_active_saasorder_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
