# Generated by Django 4.2.23 on 2025-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0003_saasorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasorder',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last name'),
        ),
    ]
