# Generated by Django 4.2.23 on 2025-09-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0004_alter_saasorder_first_name_alter_saasorder_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasorder',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='e-mail'),
        ),
    ]
