# Generated by Django 4.2.23 on 2026-01-08 03:30

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0004_saasorder_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasorder',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono convencional de contacto'),
        ),
    ]
