# Generated by Django 4.2.30 on 2026-05-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0004_alter_saasorder_options_remove_saasorder_vence_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='vence_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
