# Generated by Django 4.2.23 on 2025-09-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0005_alter_saasorder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasorder',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
    ]
