# Generated by Django 4.2.30 on 2026-05-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas_coupons', '0004_alter_coupon_discount_alter_coupon_valid_from_and_more'),
        ('saas_shop', '0007_alter_category_tamano_empresa_alter_product_category'),
        ('saas_orders', '0005_saasorder_vence_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saasorder',
            options={'ordering': ('-created',), 'verbose_name': 'Software As Service Order', 'verbose_name_plural': 'SaaS Orders'},
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_orders', to='saas_coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='saasorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_order_items', to='saas_shop.product'),
        ),
    ]
