# Generated by Django 4.2.23 on 2026-01-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0006_alter_saasorder_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='contract_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
