# Generated by Django 4.2.30 on 2026-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0006_alter_saasorder_options_alter_saasorder_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
