# Generated by Django 4.2.23 on 2025-09-02 21:26

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0006_alter_saasorder_email_alter_saasorder_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saasorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='saasorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='saasorder',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='saasorder',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='ruc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Registro Único de Contribuyente'),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='sector',
            field=models.CharField(blank=True, choices=[('G', 'Gastronómico'), ('T', 'Turismo'), ('Th', 'Tecnología'), ('I', 'Industrial'), ('AG', 'Agricola'), ('I', 'Coorporativo'), ('E', 'Educativo'), ('A', 'Administrativo'), ('A', 'Finaciero'), ('M', 'Medico & Salud'), ('C', 'Contructivo'), ('Co', 'Comercial'), ('L', 'Legal'), ('ET', 'Entretenimiento'), ('M', 'Marketing & Publicitario'), ('GO', 'Gubernamental'), ('ONG', 'Organicion sin fines de lucro'), ('O', 'Otro')], max_length=100, null=True, verbose_name='Sector de Negocios'),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono de persona a cargo'),
        ),
    ]
