# Generated by Django 4.2.23 on 2025-09-02 21:30

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0007_remove_saasorder_address_remove_saasorder_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasorder',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='R.U.C/C.I'),
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
    ]
