# Generated by Django 4.2.23 on 2026-01-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0007_saasorder_contract_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='contract_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='contract_verified',
            field=models.BooleanField(default=False, verbose_name='Contrato verificado'),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='signed_contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed/'),
        ),
    ]
