# Generated by Django 4.2.23 on 2025-09-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0008_alter_saasorder_ruc_alter_saasorder_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saasorder',
            options={'ordering': ('-created',), 'verbose_name': 'Software As Service Order', 'verbose_name_plural': 'SaaS Orders'},
        ),
        migrations.AlterModelOptions(
            name='saasorderitem',
            options={'verbose_name': 'Software As Service Order', 'verbose_name_plural': 'SaaS Orders'},
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
