# Generated by Django 4.2.23 on 2026-01-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0008_saasorder_contract_signed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='contract_hash_dev',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='contract_signed_at_dev',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='contract_verified_dev',
            field=models.BooleanField(default=False, verbose_name='Contrato verificado'),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='signed_contract_dev',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed/'),
        ),
    ]
