# Generated by Django 4.2.23 on 2026-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0009_saasorder_contract_hash_dev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='contract_hash_cloud',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='contract_signed_at_cloud',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='contract_verified_cloud',
            field=models.BooleanField(default=False, verbose_name='Contrato verificado'),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='signed_contract_cloud',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed/'),
        ),
    ]
