# Generated by Django 4.2.23 on 2026-01-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0010_saasorder_contract_hash_cloud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saasorder',
            old_name='contract_signed_at',
            new_name='contract_signed_at_ip',
        ),
        migrations.RenameField(
            model_name='saasorder',
            old_name='signed_contract',
            new_name='signed_contract_ip',
        ),
        migrations.RemoveField(
            model_name='saasorder',
            name='contract_hash',
        ),
        migrations.RemoveField(
            model_name='saasorder',
            name='contract_verified',
        ),
        migrations.AddField(
            model_name='saasorder',
            name='contract_hash_ip',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='saasorder',
            name='contract_verified_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='contract_hash_cloud',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='contract_hash_dev',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='contract_verified_cloud',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='saasorder',
            name='contract_verified_dev',
            field=models.BooleanField(default=False),
        ),
    ]
