# Generated by Django 4.2.23 on 2026-01-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_orders', '0011_rename_contract_signed_at_saasorder_contract_signed_at_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasorder',
            name='force_paid',
            field=models.BooleanField(default=False, verbose_name='Forzar estado pagado'),
        ),
    ]
