# Generated by Django 4.2.23 on 2025-10-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_automatitation',
            field=models.BooleanField(default=True, verbose_name='Tiene automatización'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_intelligent',
            field=models.BooleanField(default=True, verbose_name='Tiene inteligencia artificial'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_reaserch',
            field=models.BooleanField(default=True, verbose_name='Tiene investigación Y Desarollo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
