# Generated by Django 4.2.30 on 2026-08-19 19:57

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='costo_project_management',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Costo PM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costo_total_desarrollo',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Costo DeV'),
        ),
    ]
