# Generated by Django 4.2.23 on 2025-09-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='software',
            field=models.CharField(blank=True, choices=[('Baja', 'disponibilidad Baja'), ('Mediana', 'disponibilidad Mediana'), ('Alta', 'disponibilidad Alta'), ('Muy Alta', 'disponibilidad Muy Alta')], max_length=200, null=True),
        ),
    ]
