# Generated by Django 4.2.23 on 2025-11-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0002_product_is_automatitation_product_is_intelligent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='almacenamiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Almacenamiento (GB)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ancho_banda',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ancho de Banda (Mbps)'),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.IntegerField(blank=True, null=True, verbose_name='vCPU'),
        ),
        migrations.AddField(
            model_name='product',
            name='memoria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Memoria (GB)'),
        ),
    ]
