# Generated by Django 4.2.23 on 2025-09-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0002_alter_product_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True),
        ),
    ]
