# Generated by Django 4.2.30 on 2026-05-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0002_alter_category_tamano_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='saas_shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usuarios_simultaneos',
            field=models.CharField(blank=True, choices=[('1K', 'Baja concurrencia (10–50 usuarios)'), ('3K', 'Carga ligera (50–150 usuarios)'), ('5K', 'Carga media (150–500 usuarios)'), ('8K', 'Alta concurrencia (500–1000 usuarios)'), ('1M', 'Carga crítica (1000–5000 usuarios)'), ('+5M', 'Alta disponibilidad (>5000 usuarios simultáneos)')], max_length=10, null=True),
        ),
    ]
