# Generated by Django 4.2.23 on 2025-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0003_product_almacenamiento_product_ancho_banda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operativo'),
        ),
    ]
