# Generated by Django 4.2.30 on 2026-05-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0003_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='usuarios_simultaneos',
            field=models.CharField(blank=True, choices=[('100', 'Baja concurrencia (10–50 usuarios)'), ('300', 'Carga ligera (50–150 usuarios)'), ('500', 'Carga media (150–500 usuarios)'), ('800', 'Alta concurrencia (500–1000 usuarios)'), ('1K', 'Carga crítica (1000–5000 usuarios)'), ('+5K', 'Alta disponibilidad (>5000 usuarios simultáneos)')], max_length=10, null=True),
        ),
    ]
