# Generated by Django 4.2.23 on 2026-03-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0003_product_costo_memory_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_gpu',
            field=models.BooleanField(default=True, verbose_name='Usa procesamiento Grafico'),
        ),
    ]
