# Generated by Django 4.2.23 on 2026-03-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0004_product_is_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inteligencia_artificial',
            field=models.CharField(blank=True, choices=[('prediccion', 'Agente de IA de predicción'), ('segmentacion', 'Agente de IA de segmentación'), ('recomendacion', 'Agente de IA de recomendación'), ('generativa', 'IA Generativa')], max_length=200, null=True),
        ),
    ]
