# Generated by Django 4.2.30 on 2026-05-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0004_alter_product_usuarios_simultaneos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloud_type',
            field=models.CharField(blank=True, choices=[('Publica y Compartida', 'Publica y Compartida'), ('Publica y Dedicada', 'Publica y Dedicada'), ('Hibrida', 'Hibrida'), ('Privada y Dedicada', 'Privada y Dedicada')], max_length=200, null=True),
        ),
    ]
