# Generated by Django 4.2.23 on 2025-11-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0004_product_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPU'),
        ),
    ]
