# Generated by Django 4.2.30 on 2026-05-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0005_product_cloud_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cloud_type',
            field=models.CharField(blank=True, choices=[('pública y compartida', 'pública y compartida'), ('pública  y Dedicada', 'pública  y Dedicada'), ('Híbrida', 'Híbrida'), ('Privada y Dedicada', 'Privada y Dedicada')], max_length=200, null=True),
        ),
    ]
