# Generated by Django 4.2.23 on 2026-03-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0005_alter_product_inteligencia_artificial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tiempo_implementacion_a',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas Implementación automatización'),
        ),
        migrations.AddField(
            model_name='product',
            name='tiempo_implementacion_ai',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas Implementación inteligencia'),
        ),
    ]
