# Generated by Django 4.2.30 on 2026-05-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0006_alter_product_cloud_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tamano_empresa',
            field=models.CharField(blank=True, choices=[('1-10 usuarios', 'PYMES'), ('11-50 usuarios', ' STARTUP'), ('51-200 usuarios', 'ENTERPRISE'), ('200+ usuarios', 'INDUSTRIAL')], help_text='Selecciona el tamaño de tu empresa.', max_length=255, null=True, verbose_name='Tamaño organizacional'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='saas_shop.category'),
        ),
    ]
