# Generated by Django 4.2.23 on 2025-11-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0006_product_costo_conectores_terceros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tamano_empresa',
            field=models.CharField(blank=True, choices=[('1-10 usuarios', '1-10 usuarios'), ('11-50 usuarios', '11-50 usuarios'), ('51-200 usuarios', '51-200 usuarios'), ('200+ usuarios', 'Más de 200 usuarios')], max_length=255, null=True, verbose_name='Tamaño de la Empresa'),
        ),
    ]
