# Generated by Django 4.2.23 on 2026-03-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0006_product_tiempo_implementacion_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_horas_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
