# Generated by Django 4.2.23 on 2026-03-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0007_product_total_horas_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_tiempo',
            field=models.DecimalField(blank=True, decimal_places=2, default=6.3, max_digits=5, null=True, verbose_name='Tiempo de Entrega'),
        ),
    ]
