# Generated by Django 4.2.23 on 2026-01-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0008_product_kushki_credit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_method',
            field=models.CharField(choices=[('credit', 'Tarjeta de Crédito'), ('debit', 'Tarjeta de Débito')], default='credit', max_length=10),
        ),
    ]
