# Generated by Django 4.2.23 on 2026-03-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0009_product_valor_total_iva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_currency',
        ),
    ]
