# Generated by Django 4.2.23 on 2026-03-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0010_remove_product_iva_remove_product_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='IVA (%)'),
        ),
    ]
