# Generated by Django 4.2.23 on 2026-03-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0013_product_subtotal_product_subtotal_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
