# Generated by Django 4.2.23 on 2026-04-24 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Define una categoría disponible para los posts.', max_length=50, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_size', models.CharField(choices=[('square', 'Cuadrado (1:1)'), ('vertical', 'Vertical (4:5)'), ('horizontal', 'Horizontal (16:9)'), ('story', 'Story (9:16)')], help_text='Selecciona el formato del post según el tipo de contenido.', max_length=20, verbose_name='Tamaño de imagen')),
                ('caption', models.TextField(help_text='Texto principal del post visible en Instagram.', verbose_name='Caption')),
                ('copy', models.TextField(blank=True, help_text='Texto adicional o guía creativa.', verbose_name='Copy')),
                ('hashtags', models.TextField(help_text='Separar por espacios o comas. Ej: #marketing #ventas', verbose_name='Hashtags')),
                ('scheduled_date', models.DateTimeField(help_text='Fecha y hora de publicación.', verbose_name='Fecha programada')),
                ('categories', models.ManyToManyField(blank=True, help_text='Selecciona una o varias categorías definidas en Settings.', to='social_media_ID.categoryitem', verbose_name='Categorías')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario responsable del post.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('image', models.ForeignKey(help_text='Imagen principal del post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
            ],
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='settings',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='social_media_ID.instagramsettings'),
        ),
    ]
