# Generated by Django 4.2.23 on 2026-04-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_ID', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'verbose_name': 'Instagram Post', 'verbose_name_plural': 'Instagram Post'},
        ),
    ]
