# Generated by Django 4.2.23 on 2026-04-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_ID', '0002_alter_instagrampost_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryitem',
            name='settings',
        ),
        migrations.DeleteModel(
            name='InstagramSettings',
        ),
    ]
