# Generated by Django 4.2.23 on 2026-04-24 22:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_ID', '0003_remove_categoryitem_settings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='settings',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='social_media_ID.instagramsettings'),
        ),
    ]
