# Generated by Django 4.2.23 on 2026-04-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_ID', '0004_instagramsettings_categoryitem_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='categories',
        ),
        migrations.DeleteModel(
            name='CategoryItem',
        ),
        migrations.DeleteModel(
            name='InstagramSettings',
        ),
    ]
