# Generated by Django 4.2.23 on 2026-04-24 23:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_ID', '0005_remove_instagrampost_categories_delete_categoryitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Define una categoría disponible para los posts.', max_length=50, verbose_name='Nombre')),
                ('settings', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='social_media_ID.instagramsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Selecciona una o varias categorías definidas en Settings.', to='social_media_ID.categoryitem', verbose_name='Categorías'),
        ),
    ]
