# Generated by Django 4.2.23 on 2026-04-24 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_ID', '0006_instagramsettings_categoryitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='categories',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='categories',
            field=models.ForeignKey(blank=True, help_text='Selecciona una única categoría para este post.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_media_ID.categoryitem', verbose_name='Categoría'),
        ),
    ]
