# Generated by Django 4.2.23 on 2026-04-25 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0027_image_description'),
        ('social_media_ID', '0007_remove_instagrampost_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramCarouselPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_size', models.CharField(choices=[('square', 'Cuadrado (1:1)'), ('vertical', 'Vertical (4:5)'), ('horizontal', 'Horizontal (16:9)'), ('story', 'Story (9:16)')], help_text='Formato general del carousel.', max_length=20, verbose_name='Tamaño de imagen')),
                ('caption', models.TextField(verbose_name='Caption')),
                ('copy', models.TextField(blank=True, verbose_name='Copy')),
                ('hashtags', models.TextField(verbose_name='Hashtags')),
                ('scheduled_date', models.DateTimeField(verbose_name='Fecha programada')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_media_ID.categoryitem', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Carousel Post',
                'verbose_name_plural': 'Instagram Carousels Post',
            },
        ),
        migrations.CreateModel(
            name='InstagramCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Texto opcional por imagen', max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('post', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social_media_ID.instagramcarouselpost')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
