# Generated by Django 4.2.23 on 2026-04-25 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_media_ID', '0008_instagramcarouselpost_instagramcarouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('link', 'Enlace'), ('video', 'Video'), ('carousel', 'Carousel')], help_text='Define el formato del post para Facebook.', max_length=20, verbose_name='Tipo de publicación')),
                ('message', models.TextField(help_text='Texto principal del post en Facebook.', verbose_name='Mensaje')),
                ('link', models.URLField(blank=True, help_text='URL si el post es tipo link.', null=True, verbose_name='Enlace')),
                ('scheduled_date', models.DateTimeField(help_text='Fecha de publicación en Facebook Page.', verbose_name='Fecha programada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
            ],
            options={
                'verbose_name': 'Facebook Post',
                'verbose_name_plural': 'Facebook Posts',
            },
        ),
    ]
