# Generated by Django 4.2.23 on 2026-04-25 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0005_alter_media_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_media_ID', '0010_facebookpostimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre interno del reel para organización.', max_length=255, verbose_name='Título del Reel')),
                ('caption', models.TextField(help_text='Texto del reel en Instagram.', verbose_name='Caption')),
                ('hashtags', models.TextField(blank=True, help_text='Ej: #reels #marketing #viral', verbose_name='Hashtags')),
                ('scheduled_date', models.DateTimeField(help_text='Fecha de publicación del reel.', verbose_name='Fecha programada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('video', models.ForeignKey(blank=True, help_text='Selecciona o sube un video (MP4 recomendado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Video del Reel')),
            ],
            options={
                'verbose_name': 'Instagram Reel',
                'verbose_name_plural': 'Instagram Reels',
            },
        ),
    ]
