# Generated by Django 4.2.23 on 2026-04-25 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0005_alter_media_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0027_image_description'),
        ('social_media_ID', '0011_instagramreel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookCarouselPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('scheduled_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Texto principal del post en Facebook.', verbose_name='Mensaje')),
                ('link', models.URLField(blank=True, help_text='Opcional: enlace adjunto al post.', null=True, verbose_name='Enlace')),
                ('scheduled_date', models.DateTimeField(verbose_name='Fecha programada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, help_text='Imagen principal del post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('scheduled_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, help_text='Selecciona un video desde Media Library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='facebookpostimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='facebookpostimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='FacebookPost',
        ),
        migrations.DeleteModel(
            name='FacebookPostImage',
        ),
        migrations.AddField(
            model_name='facebookcarouselimage',
            name='post',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social_media_ID.facebookcarouselpost'),
        ),
    ]
