# Generated by Django 4.2.23 on 2025-09-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo adicional fijo del servicio (en USD)', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estimacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios_estimados', models.PositiveIntegerField()),
                ('tipo_uso', models.CharField(choices=[('transaccional', 'Transaccional'), ('analitico', 'Analítico'), ('mixto', 'Mixto')], max_length=50)),
                ('proveedor', models.CharField(choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vcpu', models.FloatField()),
                ('ram_gb', models.FloatField()),
                ('almacenamiento_gb', models.FloatField()),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudcalc.servicio')),
            ],
        ),
    ]
