# Generated by Django 4.2.20 on 2025-08-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='costo_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo adicional fijo del servicio (en USD)', max_digits=10),
        ),
    ]
