[uwsgi]
virtualenv = /py/
env = DJANGO_SETTINGS_MODULE=qnd041app.settings.pro
wsgi-file = /qnd041app/qnd041app/qnd041app/wsgi.py

# Configuración ligera y segura de procesos
master = true
processes = 1
threads = 2
enable-threads = true
no-orphans = true

# Control de memoria y reinicio preventivo
reload-on-rss = 350
max-requests = 500
harakiri = 30

# Red y limpieza
vacuum = true
buffer-size = 65535
http = 0.0.0.0:9000

# Logs y cierre controlado
logto = /var/log/uwsgi/uwsgi.log  
log-reopen = true         
die-on-term = true