# Generated by Django 4.2.30 on 2026-04-26 02:17

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Define el nombre principal de la campaña.', max_length=50, verbose_name='Nombre')),
                ('style', models.CharField(blank=True, choices=[('minimal', 'Minimalista'), ('modern', 'Moderno'), ('retro', 'Retro / Vintage'), ('illustrative', 'Ilustrativo / Vectorial'), ('photorealistic', 'Fotorealista'), ('cinematic', 'Cinemático / Dramático')], help_text='Elija el estilo visual de la campaña', max_length=50)),
                ('brand_1', models.TextField(blank=True, help_text='Escriba el brand principal de la campaña', null=True, verbose_name='Brand Principal')),
                ('brand_2', models.TextField(blank=True, help_text='Escriba el brand secundario de la campaña', null=True, verbose_name='Brand Secundario')),
                ('image_url_1', models.URLField(blank=True, editable=False, null=True)),
                ('image_url_2', models.URLField(blank=True, editable=False, null=True)),
                ('color_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Paleta de color primaria')),
                ('color_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Paleta de color secundaria')),
                ('color_palette', models.CharField(blank=True, choices=[('pastel', 'Tonos pastel'), ('vibrant', 'Colores vibrantes'), ('monochrome', 'Monocromo'), ('dark_mode', 'Tonos oscuros'), ('light_mode', 'Tonos claros')], max_length=50, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookCarouselPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramCarouselPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_size', models.CharField(max_length=20)),
                ('caption', models.TextField()),
                ('copy', models.TextField(blank=True)),
                ('hashtags', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_size', models.CharField(blank=True, choices=[('square', 'Cuadrado'), ('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('story', 'Story')], help_text='Elija un formato para este post', max_length=20, null=True, verbose_name='Formato Visual')),
                ('prompt', wagtail.fields.RichTextField(blank=True, help_text='Describa un contexto de acuerdo a la campaña y post', null=True, verbose_name='AI Agentic Creator')),
                ('caption', models.TextField(blank=True, null=True)),
                ('copy', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, help_text='URL de la imagen post generada por IA', max_length=1000, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('hashtags', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=280)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
