# Generated by Django 4.2.30 on 2026-05-25 18:19

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Define el nombre principal de la campaña.', max_length=50, verbose_name='Nombre')),
                ('style', models.CharField(blank=True, choices=[('minimal', 'Minimalista'), ('futuristic', 'Futurista'), ('modern', 'Moderno'), ('retro', 'Retro / Vintage'), ('illustrative', 'Ilustrativo / Vectorial'), ('photorealistic', 'Fotorealista'), ('cinematic', 'Cinemático / Dramático'), ('Estilo visual inspirado en el manga japonés Akira:ilustración de tipo vectorial, con enfoque minimalista, líneas limpias y definidas, alto contraste y composición simple.La estética debe evocar un cómic japonés clásico, con detalles cuidadosamente seleccionados, uso limitado de colores y una atmósfera moderna y elegante.', 'Art Akira')], help_text='Elija el estilo visual de la campaña', max_length=450)),
                ('brand_1', models.TextField(blank=True, help_text='Escriba el brand principal de la campaña', null=True, verbose_name='Brand Principal')),
                ('brand_2', models.TextField(blank=True, help_text='Escriba el brand secundario de la campaña', null=True, verbose_name='Brand Secundario')),
                ('acting', models.TextField(blank=True, help_text='Describa la escena y elementos de la campaña', null=True, verbose_name='Acting')),
                ('image_url_1', models.URLField(blank=True, editable=False, max_length=500, null=True)),
                ('image_url_2', models.URLField(blank=True, editable=False, max_length=500, null=True)),
                ('color_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Paleta de color primaria')),
                ('color_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Paleta de color secundaria')),
                ('color_palette', models.CharField(blank=True, choices=[('pastel', 'Tonos pastel'), ('vibrant', 'Colores vibrantes'), ('monochrome', 'Monocromo'), ('dark_mode', 'Tonos oscuros'), ('light_mode', 'Tonos claros')], max_length=50, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookCarouselPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('copy', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramCarouselPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slides', models.PositiveIntegerField(default=1, help_text='Cantidad de imágenes/slides del carrusel', verbose_name='Número de slides')),
                ('image_size', models.CharField(blank=True, choices=[('square', 'Cuadrado'), ('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('story', 'Story')], help_text='Elija un formato para este carrusel', max_length=20, null=True, verbose_name='Formato Visual')),
                ('prompt', wagtail.fields.RichTextField(blank=True, help_text='Describa un contexto de acuerdo a la campaña', null=True, verbose_name='AI Agentic Instagram Carousel Creator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_size', models.CharField(blank=True, choices=[('square', 'Cuadrado'), ('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('story', 'Story')], help_text='Elija un formato para este post', max_length=20, null=True, verbose_name='Formato Visual')),
                ('prompt', wagtail.fields.RichTextField(blank=True, help_text='Describa un contexto de acuerdo a la campaña y post', null=True, verbose_name='AI Agentic Instagram Post Creator')),
                ('caption', models.TextField(blank=True, null=True)),
                ('copy', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, help_text='URL de la imagen post generada por IA', max_length=1000, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(choices=[(5, '5 segundos - Pruebas'), (7, '7 segundos - Viral (Quick Hook)'), (15, '15 segundos - Viral (Fast Pace)'), (30, '30 segundos - Tendencia (Standard)'), (60, '60 segundos - Promocional (Detailed)'), (90, '90 segundos - Promocional (Long Form)')], default=15, help_text='Duración en segundos. Los videos de 7-15s suelen tener mayor viralidad.', verbose_name='Duración del Video')),
                ('prompt', wagtail.fields.RichTextField(blank=True, help_text='Describa el contexto o guion base para la IA', null=True, verbose_name='AI Agentic Instagram Reel Creator')),
                ('generated_video_url', models.URLField(blank=True, help_text='URL externa para previsualización antes del guardado físico.', max_length=1000, null=True, verbose_name='URL de n8n (Preview)')),
                ('caption', models.TextField(blank=True)),
                ('copy', models.TextField(blank=True, verbose_name='Texto en Video (Copy)')),
                ('hashtags', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Instagram Reel',
                'verbose_name_plural': 'Instagram Reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=280)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
