# Generated by Django 4.2.23 on 2026-04-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='categories',
            field=models.ForeignKey(blank=True, help_text='Elija la campaña para este post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_media_AI.categoryitem', verbose_name='Campaña'),
        ),
    ]
