# Generated by Django 4.2.30 on 2026-04-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='image_url_1',
            field=models.URLField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='image_url_2',
            field=models.URLField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
