# Generated by Django 4.2.23 on 2026-04-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0002_alter_instagrampost_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='prompt',
            field=models.TextField(blank=True, help_text='Describa un contexto de acuerdo a la campaña y post', null=True, verbose_name='AI Agentic Creator'),
        ),
    ]
