# Generated by Django 4.2.30 on 2026-04-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0003_alter_categoryitem_image_url_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='style',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimalista'), ('futuristic', 'Futurista'), ('modern', 'Moderno'), ('retro', 'Retro / Vintage'), ('illustrative', 'Ilustrativo / Vectorial'), ('photorealistic', 'Fotorealista'), ('cinematic', 'Cinemático / Dramático')], help_text='Elija el estilo visual de la campaña', max_length=50),
        ),
    ]
