# Generated by Django 4.2.23 on 2026-04-25 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('social_media_AI', '0003_instagrampost_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitem',
            name='brand_1',
            field=models.TextField(blank=True, help_text='Escriba el brand principal de la campaña', null=True, verbose_name='Brand Principal'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='brand_2',
            field=models.TextField(blank=True, help_text='Escriba el brand secundario de la campaña', null=True, verbose_name='Brand Secundario'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='color_1',
            field=models.CharField(blank=True, help_text='Escriba el codigo RGB o HEX de color primario', max_length=50, null=True, verbose_name='Paleta de color primaria'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='color_2',
            field=models.CharField(blank=True, help_text='Escriba el codigo RGB o HEX de color primario', max_length=50, null=True, verbose_name='Paleta de color secundaria'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='color_palette',
            field=models.CharField(blank=True, choices=[('pastel', 'Tonos pastel'), ('vibrant', 'Colores vibrantes'), ('monochrome', 'Monocromo'), ('dark_mode', 'Tonos oscuros'), ('light_mode', 'Tonos claros')], help_text='Elija la  tonalidad de la campaña', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='logo_1',
            field=models.ForeignKey(help_text='Elija la marca principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='logo_2',
            field=models.ForeignKey(help_text='Elija la marca secundaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='style',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimalista'), ('modern', 'Moderno'), ('retro', 'Retro / Vintage'), ('illustrative', 'Ilustrativo / Vectorial'), ('photorealistic', 'Fotorealista'), ('cinematic', 'Cinemático / Dramático')], help_text='Elija el estilo visual de la campaña', max_length=50),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='name',
            field=models.CharField(help_text='Define el nombre principal de la campaña.', max_length=50, verbose_name='Nombre'),
        ),
    ]
