# Generated by Django 4.2.30 on 2026-04-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0004_alter_categoryitem_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcarouselpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación'),
        ),
        migrations.AlterField(
            model_name='facebookimagepost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación'),
        ),
        migrations.AlterField(
            model_name='facebookvideopost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación'),
        ),
        migrations.AlterField(
            model_name='instagramcarouselpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación'),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación'),
        ),
        migrations.AlterField(
            model_name='linkedinpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación'),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora de Publicación'),
        ),
    ]
