# Generated by Django 4.2.23 on 2026-04-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0004_categoryitem_brand_1_categoryitem_brand_2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstagramSettings',
            new_name='SocialMediaSettings',
        ),
    ]
