# Generated by Django 4.2.23 on 2026-04-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0005_rename_instagramsettings_socialmediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcarouselpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='facebookimagepost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='facebookvideopost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='instagramcarouselpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image_size',
            field=models.CharField(choices=[('square', 'Cuadrado'), ('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('story', 'Story')], help_text='Elija un formato para este post', max_length=20, verbose_name='Formato Visual'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='linkedinpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Asigne una fecha y hora para publicacion automatica', null=True, verbose_name='Fecha/Hora'),
        ),
    ]
