# Generated by Django 4.2.30 on 2026-04-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0005_alter_facebookcarouselpost_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='copy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
