# Generated by Django 4.2.30 on 2026-04-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0006_alter_instagrampost_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcarouselpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo  campaña', max_length=100),
        ),
        migrations.AddField(
            model_name='facebookimagepost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo  campaña', max_length=100),
        ),
        migrations.AddField(
            model_name='facebookvideopost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo  campaña', max_length=100),
        ),
        migrations.AddField(
            model_name='instagramcarouselpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo  campaña', max_length=100),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo  campaña', max_length=100),
        ),
        migrations.AddField(
            model_name='instagramreel',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo  campaña', max_length=100),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo  campaña', max_length=100),
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo  campaña', max_length=100),
        ),
        migrations.AlterField(
            model_name='facebookcarouselpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='facebookimagepost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='facebookvideopost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='instagramcarouselpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='linkedinpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='scheduled', max_length=20),
        ),
    ]
