# Generated by Django 5.2.13 on 2026-04-25 20:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0006_alter_facebookcarouselpost_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='prompt',
            field=wagtail.fields.RichTextField(blank=True, help_text='Describa un contexto de acuerdo a la campaña y post', null=True, verbose_name='AI Agentic Creator'),
        ),
    ]
