# Generated by Django 4.2.30 on 2026-04-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0007_facebookcarouselpost_post_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcarouselpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100),
        ),
        migrations.AlterField(
            model_name='facebookimagepost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100),
        ),
        migrations.AlterField(
            model_name='facebookvideopost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100),
        ),
        migrations.AlterField(
            model_name='instagramcarouselpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100),
        ),
        migrations.AlterField(
            model_name='linkedinpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Product', 'Producto'), ('Lunch', 'Lanzamiento'), ('Publicitario', 'Publishing'), ('Informativo', 'info')], help_text='Elija el tipo de post', max_length=100),
        ),
    ]
