# Generated by Django 5.2.13 on 2026-04-25 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0007_alter_instagrampost_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='categories',
            field=models.ForeignKey(help_text='Elija la campaña para este post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_media_AI.categoryitem', verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image_size',
            field=models.CharField(blank=True, choices=[('square', 'Cuadrado'), ('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('story', 'Story')], help_text='Elija un formato para este post', max_length=20, null=True, verbose_name='Formato Visual'),
        ),
    ]
