# Generated by Django 5.2.13 on 2026-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0008_alter_instagrampost_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='image',
            field=models.URLField(blank=True, help_text='URL de la imagen generada por IA', max_length=1000, null=True),
        ),
    ]
