# Generated by Django 4.2.30 on 2026-04-30 01:46

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0008_alter_facebookcarouselpost_post_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramcarouselpost',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='instagramcarouselpost',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='instagramcarouselpost',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='instagramcarouselimage',
            name='copy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramcarouselimage',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramcarouselpost',
            name='prompt',
            field=wagtail.fields.RichTextField(blank=True, help_text='Describa un contexto de acuerdo a la campaña y post', null=True, verbose_name='AI Agentic Instagram Post Creator'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='prompt',
            field=wagtail.fields.RichTextField(blank=True, help_text='Describa un contexto de acuerdo a la campaña y post', null=True, verbose_name='AI Agentic Instagram Post Creator'),
        ),
    ]
