# Generated by Django 4.2.30 on 2026-04-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0009_remove_instagramcarouselpost_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramcarouselpost',
            old_name='category',
            new_name='categories',
        ),
    ]
