# Generated by Django 5.2.13 on 2026-04-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0009_alter_instagrampost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='image',
            field=models.URLField(blank=True, help_text='URL de la imagen post generada por IA', max_length=1000, null=True),
        ),
    ]
