# Generated by Django 4.2.30 on 2026-04-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0011_alter_instagramcarouselpost_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcarouselimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
