# Generated by Django 4.2.30 on 2026-04-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0012_alter_instagramcarouselimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcarouselpost',
            name='slides',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de imágenes/slides del carrusel', verbose_name='Número de slides'),
        ),
    ]
