# Generated by Django 4.2.30 on 2026-04-30 22:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0014_alter_instagramcarouselimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramreel',
            name='title',
        ),
        migrations.AddField(
            model_name='instagramreel',
            name='categories',
            field=models.ForeignKey(blank=True, help_text='Elija la campaña para este carrusel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_media_AI.categoryitem', verbose_name='Campaña'),
        ),
        migrations.AddField(
            model_name='instagramreel',
            name='prompt',
            field=wagtail.fields.RichTextField(blank=True, help_text='Describa un contexto de acuerdo a la campaña', null=True, verbose_name='AI Agentic Instagram Carousel Creator'),
        ),
    ]
