# Generated by Django 4.2.30 on 2026-04-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0015_remove_instagramreel_title_instagramreel_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramreel',
            name='duration',
            field=models.PositiveIntegerField(choices=[(5, '5 segundos - Pruebas'), (7, '7 segundos - Viral (Quick Hook)'), (15, '15 segundos - Viral (Fast Pace)'), (30, '30 segundos - Tendencia (Standard)'), (60, '60 segundos - Promocional (Detailed)'), (90, '90 segundos - Promocional (Long Form)')], default=15, help_text='Duración en segundos. Los videos de 7-15s suelen tener mayor viralidad.', verbose_name='Duración del Video'),
        ),
    ]
