# Generated by Django 4.2.30 on 2026-04-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0016_instagramreel_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramreel',
            name='video',
        ),
        migrations.AddField(
            model_name='instagramreel',
            name='generated_video_url',
            field=models.URLField(blank=True, help_text='URL externa para la previsualización del contenido de video generado en n8n antes de ser guardado en Wagtail media.', max_length=1000, null=True, verbose_name='URL del Video Generado (Previsualización)'),
        ),
    ]
