# Generated by Django 4.2.30 on 2026-05-01 00:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0005_alter_media_options'),
        ('social_media_AI', '0017_remove_instagramreel_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramreel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Instagram Reel', 'verbose_name_plural': 'Instagram Reels'},
        ),
        migrations.AddField(
            model_name='instagramreel',
            name='copy',
            field=models.TextField(blank=True, verbose_name='Texto en Video (Copy)'),
        ),
        migrations.AddField(
            model_name='instagramreel',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Video Final'),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='categories',
            field=models.ForeignKey(blank=True, help_text='Elija la campaña para este Reel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_media_AI.categoryitem', verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='generated_video_url',
            field=models.URLField(blank=True, help_text='URL externa para previsualización antes del guardado físico.', max_length=1000, null=True, verbose_name='URL de n8n (Preview)'),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='prompt',
            field=wagtail.fields.RichTextField(blank=True, help_text='Describa el contexto o guion base para la IA', null=True, verbose_name='AI Agentic Instagram Reel Creator'),
        ),
    ]
