# Generated by Django 4.2.30 on 2026-05-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0018_alter_instagramreel_options_instagramreel_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitem',
            name='acting',
            field=models.TextField(blank=True, help_text='Describa la escena y elementos de la campaña', null=True, verbose_name='Acting'),
        ),
    ]
