# Generated by Django 4.2.30 on 2026-05-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0019_categoryitem_acting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='style',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimalista'), ('futuristic', 'Futurista'), ('modern', 'Moderno'), ('retro', 'Retro / Vintage'), ('illustrative', 'Ilustrativo / Vectorial'), ('photorealistic', 'Fotorealista'), ('cinematic', 'Cinemático / Dramático'), ('Art Akira', 'Ilustrativo / Vectorial/ Minismalista/Estetica de comic japones AKIRA')], help_text='Elija el estilo visual de la campaña', max_length=50),
        ),
    ]
