# Generated by Django 4.2.30 on 2026-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_AI', '0020_alter_categoryitem_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='style',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimalista'), ('futuristic', 'Futurista'), ('modern', 'Moderno'), ('retro', 'Retro / Vintage'), ('illustrative', 'Ilustrativo / Vectorial'), ('photorealistic', 'Fotorealista'), ('cinematic', 'Cinemático / Dramático'), ('Estilo visual inspirado en el manga japonés Akira:ilustración de tipo vectorial, con enfoque minimalista, líneas limpias y definidas, alto contraste y composición simple.La estética debe evocar un cómic japonés clásico, con detalles cuidadosamente seleccionados, uso limitado de colores y una atmósfera moderna y elegante.', 'Art Akira')], help_text='Elija el estilo visual de la campaña', max_length=450),
        ),
    ]
