# Generated by Django 4.2.30 on 2026-05-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('social_media_AI', '0021_alter_categoryitem_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcarouselimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
