# Generated by Django 4.2.29 on 2026-06-24 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartbusinessanalytics_demo', '0002_movimientofinanciero_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ingresos_financieros', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
    ]
