# Generated by Django 4.2.29 on 2026-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_demo', '0005_activos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='asset_code',
            field=models.CharField(blank=True, help_text='Identificador único interno del activo.', max_length=50, null=True, verbose_name='Código del activo'),
        ),
        migrations.AlterField(
            model_name='activos',
            name='code',
            field=models.CharField(blank=True, help_text='Identificador único interno del pasivo.', max_length=50, null=True, verbose_name='Código del pasivo'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='codigo_referencia',
            field=models.CharField(help_text='Identificador único del egreso, como número de factura o comprobante.', max_length=50, verbose_name='Código de referencia'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='codigo_referencia',
            field=models.CharField(help_text='Identificador único del ingreso, como número de factura o recibo.', max_length=50, verbose_name='Código de referencia'),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='hash_registro',
            field=models.CharField(blank=True, editable=False, help_text='Hash único del movimiento financiero, generado automáticamente para trazabilidad.', max_length=64, null=True),
        ),
    ]
