# Generated by Django 4.2.29 on 2026-06-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_demo', '0006_alter_activos_asset_code_alter_activos_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activos',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Movimiento Patrimonial', 'verbose_name_plural': 'Movimientos Patrimoniales'},
        ),
        migrations.AlterModelOptions(
            name='estadofinanciero',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Estado de Resultados', 'verbose_name_plural': 'Estados de Resultados'},
        ),
    ]
