# Generated by Django 4.2.30 on 2026-05-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nivel_experiencia_cloud',
            field=models.CharField(blank=True, choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50, null=True, verbose_name='Nivel de experiencia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Escriba su nombre completo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tamano_empresa',
            field=models.CharField(blank=True, choices=[('1-10 usuarios', '100 usuarios'), ('11-50 usuarios', '500 usuarios'), ('51-200 usuarios', '1000 usuarios'), ('200+ usuarios', 'Más de 2000 usuarios')], help_text='Selecciona el tamaño de tu empresa.', max_length=255, null=True, verbose_name='Tamaño organizacional'),
        ),
    ]
