# Generated by Django 4.2.23 on 2026-03-09 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(choices=[('proyecto', 'Proyecto'), ('objetivo', 'Objetivo'), ('tarea', 'Tarea'), ('accion', 'Acción'), ('comentario', 'Comentario')], help_text='Tipo de registro dentro del sistema: proyecto, objetivo, tarea, acción o comentario.', max_length=20)),
                ('proyecto', models.CharField(help_text='Nombre del proyecto al que pertenece esta actividad.', max_length=255)),
                ('objetivo', models.CharField(blank=True, help_text='Objetivo del proyecto relacionado con la actividad.', max_length=255)),
                ('tarea', models.CharField(blank=True, help_text='Nombre de la tarea o actividad específica.', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la actividad, tarea o acción.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('bloqueado', 'Bloqueado'), ('completado', 'Completado')], default='pendiente', help_text='Estado actual de la tarea o actividad.', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', help_text='Nivel de prioridad de la actividad.', max_length=10)),
                ('porcentaje_progreso', models.IntegerField(default=0, help_text='Porcentaje de avance de la tarea u objetivo (0 a 100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('objetivo_cumplido', models.BooleanField(default=False, help_text='Indica si el objetivo o tarea fue completado exitosamente.')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha en la que inicia la tarea o actividad.', null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, help_text='Fecha límite para completar la tarea.', null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, help_text='Fecha en la que se completó la tarea o actividad.', null=True)),
                ('canal_slack', models.CharField(blank=True, help_text='Canal de Slack relacionado con la actividad.', max_length=255)),
                ('usuario_slack', models.CharField(blank=True, help_text='Identificador del usuario en Slack que generó la acción.', max_length=255)),
                ('timestamp_slack', models.CharField(blank=True, help_text='Timestamp del mensaje en Slack para rastrear el hilo de conversación.', max_length=100)),
                ('metadatos', models.JSONField(blank=True, help_text='Información adicional en formato JSON para registrar cambios, estados anteriores u otros datos.', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró la actividad.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización del registro.')),
            ],
        ),
    ]
