# Generated by Django 4.2.30 on 2026-10-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sector_negocios',
            field=models.CharField(blank=True, choices=[('G', 'Gastronómico'), ('T', 'Turismo'), ('Th', 'Tecnología'), ('I', 'Industrial'), ('AG', 'Agricola'), ('I', 'Coorporativo'), ('E', 'Educativo'), ('A', 'Administrativo'), ('F', 'Finaciero'), ('M', 'Medico & Salud'), ('C', 'Contructivo'), ('Co', 'Comercial'), ('L', 'Legal'), ('ET', 'Entretenimiento'), ('M', 'Marketing & Publicitario'), ('GO', 'Gubernamental'), ('ONG', 'Organicion sin fines de lucro'), ('O', 'Otro')], max_length=100, null=True),
        ),
    ]
