# Generated by Django 4.2.30 on 2026-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_profile_nivel_experiencia_cloud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tamano_empresa',
            field=models.CharField(blank=True, choices=[('1-10 usuarios', 'PYMES'), ('11-50 usuarios', ' STARTUP'), ('51-200 usuarios', 'ENTERPRISE'), ('200+ usuarios', 'INDUSTRIAL')], help_text='Selecciona el tamaño de tu empresa.', max_length=255, null=True, verbose_name='Tamaño organizacional'),
        ),
    ]
