# Generated by Django 4.2.23 on 2025-10-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_smartquailcrew'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartquailcrew',
            name='bank_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Información bancaria (Banco, cuenta, etc.)'),
        ),
        migrations.AddField(
            model_name='smartquailcrew',
            name='bank_transaction_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de transacción bancaria'),
        ),
        migrations.AddField(
            model_name='smartquailcrew',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('transfer', 'Transferencia bancaria'), ('platform', 'Plataforma de pagos'), ('cash', 'Efectivo')], max_length=20, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='smartquailcrew',
            name='payment_platform_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Plataforma de pago (nombre, ID)'),
        ),
    ]
