# Generated by Django 4.2.20 on 2025-07-25 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_problemafrecuente_ticketsoporte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.administrativeprofile', verbose_name='Usuario en Sistema MEDDES™'),
        ),
    ]
