# Generated by Django 4.2.23 on 2026-04-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_registroactividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
