# Generated by Django 4.2.23 on 2025-10-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_smartquailcrew_bank_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartquailcrew',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='crew/profile_pictures/', verbose_name='Foto de perfil'),
        ),
    ]
