# Generated by Django 6.1.2 on 2026-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_sector_negocios'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
