# Generated by Django 4.2.30 on 2026-05-13 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_profile_tamano_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El número debe tener el formato 593XXXXXXXXX (ej: 593963521262).', regex='^593\\d{9}$')], verbose_name='Teléfono convencional de contacto'),
        ),
    ]
