# Generated by Django 4.2.23 on 2025-10-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_smartquailcrew_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acepta_terminos',
            field=models.BooleanField(default=False, verbose_name='Acepta los términos y condiciones'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suscripcion_noticias',
            field=models.BooleanField(default=False, verbose_name='Desea suscribirse al canal de noticias'),
        ),
    ]
