# Generated by Django 4.2.30 on 2026-05-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(help_text='El número debe tener el formato 593XXXXXXXXX (ej: 593963521262).', max_length=15, unique=True, verbose_name='Teléfono convencional de whatsapp'),
        ),
    ]
