# Generated by Django 4.2.23 on 2025-10-31 07:25

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_customuser_acepta_terminos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+593', max_length=128, null=True, region=None, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono convencional de contacto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='suscripcion_noticias',
            field=models.BooleanField(default=False, verbose_name='Desea recibir notificaciones, alertas y noticias de SmartQuail, Inc. a su correo electrónico'),
        ),
    ]
