# Generated by Django 4.2.23 on 2025-11-22 10:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Perfil de Cliente', 'verbose_name_plural': 'Perfiles de Clientes'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='actividad_economica',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='adjunto_autorizacion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apellidos_paciente',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apellidos_representante_legal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certificado_inicio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='es_alta',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='es_en_terapia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='es_pausa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='es_retirado',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_pausa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_re_inicio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_retiro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instirucional',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='motivo_otro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='motivo_retiro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nacionalidad_representante',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre_paciente',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombres_representante_legal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relacion_del_representante',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ruc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ruc_representante',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sucursales',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_terapeutas',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='valorizacion_terapeutica',
        ),
        migrations.AddField(
            model_name='profile',
            name='cargo_usuario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo en la Empresa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='descripcion_necesidades',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto o Necesidades Cloud'),
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion_empresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de la Empresa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='documento_empresa',
            field=models.FileField(blank=True, null=True, upload_to='documentos/empresa/', verbose_name='Documento Legal de la Empresa (opcional)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_corporativo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Corporativo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nivel_experiencia_cloud',
            field=models.CharField(blank=True, choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50, null=True, verbose_name='Nivel de experiencia en la nube'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Completo del Usuario'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Empresa u Organización'),
        ),
        migrations.AddField(
            model_name='profile',
            name='presupuesto_estimado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Presupuesto Estimado para Soluciones Cloud'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ruc_empresa',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RUC de la Empresa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ruc_usuario',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Cédula / RUC del Usuario'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sector_negocio',
            field=models.CharField(blank=True, choices=[('Tecnología', 'Tecnología'), ('Comercio', 'Comercio'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Manufactura', 'Manufactura'), ('Servicios Profesionales', 'Servicios Profesionales'), ('Finanzas', 'Finanzas'), ('Gobierno', 'Gobierno'), ('ONG', 'ONG'), ('Otro', 'Otro')], max_length=255, null=True, verbose_name='Sector de Negocio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='servicios_cloud_interes',
            field=models.JSONField(default=list, help_text='Ejemplo: Infraestructura, Backup, Ciberseguridad, Migraciones...', verbose_name='Servicios Cloud de Interés'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tamano_empresa',
            field=models.CharField(blank=True, choices=[('1-10 empleados', '1-10 empleados'), ('11-50 empleados', '11-50 empleados'), ('51-200 empleados', '51-200 empleados'), ('200+ empleados', 'Más de 200 empleados')], max_length=255, null=True, verbose_name='Tamaño de la Empresa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='provincia',
            field=models.CharField(blank=True, choices=[('Azuay', 'Azuay'), ('Bolívar', 'Bolívar'), ('Cañar', 'Cañar'), ('Carchi', 'Carchi'), ('Chimborazo', 'Chimborazo'), ('Cotopaxi', 'Cotopaxi'), ('El Oro', 'El Oro'), ('Esmeraldas', 'Esmeraldas'), ('Galápagos', 'Galápagos'), ('Guayas', 'Guayas'), ('Imbabura', 'Imbabura'), ('Loja', 'Loja'), ('Los Ríos', 'Los Ríos'), ('Manabí', 'Manabí'), ('Morona Santiago', 'Morona Santiago'), ('Napo', 'Napo'), ('Orellana', 'Orellana'), ('Pastaza', 'Pastaza'), ('Pichincha', 'Pichincha'), ('Santa Elena', 'Santa Elena'), ('Santo Domingo de los Tsáchilas', 'Santo Domingo de los Tsáchilas'), ('Sucumbíos', 'Sucumbíos'), ('Tungurahua', 'Tungurahua'), ('Zamora Chinchipe', 'Zamora Chinchipe')], default='Pichincha', max_length=255, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono de Contacto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
