# Generated by Django 4.2.23 on 2025-11-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_profile_tamano_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='presupuesto_estimado',
            field=models.CharField(blank=True, choices=[('500-2000', '500 - 2,000 USD'), ('2000-10000', '2,000 - 10,000 USD'), ('10000-35000', '10,000 - 35,000 USD'), ('50000+', '+50,000 USD')], max_length=20, null=True, verbose_name='Presupuesto Estimado para Soluciones Cloud'),
        ),
    ]
