# Generated by Django 4.2.23 on 2025-11-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_profile_presupuesto_estimado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='descripcion_necesidades',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='documento_empresa',
        ),
    ]
