# Generated by Django 4.2.23 on 2025-12-03 00:53

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_profile_descripcion_necesidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+593', max_length=128, null=True, region=None, validators=[django.core.validators.RegexValidator(message='El número debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono de Contacto'),
        ),
    ]
