# Generated by Django 4.2.23 on 2026-01-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_customuser_sector_negocios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sector_negocio',
            field=models.CharField(blank=True, choices=[('gastronomico', 'Gastronómico'), ('tecnologico', 'Tecnológico'), ('medico_terapeutico', 'Médico y Terapéutico'), ('educacion_primaria', 'Educación Primaria'), ('educacion_universitaria', 'Educación Universitaria'), ('organizacion_social', 'Organización Social'), ('organizacion_politica', 'Organización Política'), ('empresa_publica', 'Empresa Pública'), ('empresa_privada', 'Empresa Privada'), ('servicios_mantenimiento', 'Servicios de Mantenimiento'), ('servicios_administrativos', 'Servicios Administrativos'), ('servicios_contables', 'Servicios Contables'), ('servicios_transporte', 'Servicios de Transporte'), ('industria_textil', 'Industria Textil'), ('industria_agropecuaria', 'Industria Agropecuaria'), ('servicios_legales', 'Servicios Legales'), ('industria_gastronomica', 'Industria Gastronómica'), ('transporte', 'Transporte'), ('investigacion_cientifica', 'Investigación Científica'), ('arte_entretenimiento', 'Arte y Entretenimiento'), ('Maketting_publicidad', 'Marketing y Publicidad')], max_length=255, null=True, verbose_name='Sector de Negocio'),
        ),
    ]
