# Generated by Django 4.2.30 on 2026-05-10 01:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paas_coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='credito',
            field=models.CharField(blank=True, choices=[('3 meses sin intereses', '3 meses sin intereses'), ('6 meses (2%)', '6 meses (2%)'), ('12 meses (5%)', '12 meses (5%)'), ('24 meses (5%)', 'meses (5%)')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='descripcion_valor_agregado',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del valor agregado del proyecto'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='ingresos_anuales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ingresos anuales'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='presupuesto_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto real disponible'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paas_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
