# Generated by Django 4.2.30 on 2026-05-10 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paas_coupons', '0002_coupon_created_coupon_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='percent_credit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='credito',
            field=models.CharField(blank=True, choices=[('3', '3 meses sin intereses (PYMES)'), ('6', '6 meses (2% PYMES y STARTUPS)'), ('12', '12 meses (6% STARTUPS y ENTERPRISES)'), ('24', '12 meses (12% ENTERPRISES y INDUSTRIAL)')], max_length=150, null=True),
        ),
    ]
