# Generated by Django 4.2.30 on 2026-05-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paas_coupons', '0003_coupon_percent_credit_alter_coupon_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='credito',
            field=models.CharField(blank=True, choices=[('3', '3 meses sin intereses (PYMES)'), ('6', '6 meses (2% PYMES y STARTUPS)'), ('12', '12 meses (6% STARTUPS y ENTERPRISES)'), ('24', '24 meses (12% ENTERPRISES y COORP)')], max_length=150, null=True),
        ),
    ]
