# Generated by Django 4.2.30 on 2026-05-07 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas_coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='descripcion_valor_agregado',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del valor agregado del proyecto'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='ingresos_anuales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ingresos anuales'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='presupuesto_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto real disponible'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
