# Generated by Django 4.2.30 on 2026-05-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_coupons', '0002_coupon_created_coupon_descripcion_valor_agregado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
