# Generated by Django 4.2.23 on 2026-02-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_activo', models.BooleanField(default=True, help_text='Indica si el movimiento corresponde a un activo')),
                ('asset_code', models.CharField(blank=True, help_text='Identificador único interno del activo.', max_length=50, null=True, unique=True, verbose_name='Código del activo')),
                ('category', models.CharField(blank=True, help_text='Clasificación del activo (maquinaria, equipo, vehículo, etc.).', max_length=100, null=True, verbose_name='Categoría')),
                ('serial_number', models.CharField(blank=True, help_text='Número de serie proporcionado por el fabricante.', max_length=100, null=True, verbose_name='Número de serie')),
                ('brand', models.CharField(blank=True, help_text='Marca comercial del activo.', max_length=100, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, help_text='Modelo específico del activo.', max_length=100, null=True, verbose_name='Modelo')),
                ('acquisition_date', models.DateField(blank=True, help_text='Fecha en que el activo fue adquirido.', null=True, verbose_name='Fecha de adquisición')),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo inicial pagado por el activo.', max_digits=18, null=True, verbose_name='Costo de adquisición')),
                ('additional_costs', models.DecimalField(blank=True, decimal_places=2, help_text='Costos adicionales capitalizables (transporte, instalación, impuestos no recuperables).', max_digits=18, null=True, verbose_name='Costos adicionales')),
                ('useful_life_years', models.PositiveIntegerField(blank=True, help_text='Número estimado de años de vida útil del activo.', null=True, verbose_name='Vida útil (años)')),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado del activo al final de su vida útil.', max_digits=18, null=True, verbose_name='Valor residual')),
                ('depreciation_accumulated', models.DecimalField(blank=True, decimal_places=2, help_text='Monto total depreciado hasta la fecha.', max_digits=18, null=True, verbose_name='Depreciación acumulada')),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor contable actual del activo (costo menos depreciación).', max_digits=18, null=True, verbose_name='Valor en libros')),
                ('fair_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor determinado mediante avalúo técnico independiente.', max_digits=18, null=True, verbose_name='Valor razonable')),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado del activo según condiciones actuales del mercado.', max_digits=18, null=True, verbose_name='Valor de mercado')),
                ('valuation_date', models.DateField(blank=True, help_text='Fecha en que se realizó la última valoración del activo.', null=True, verbose_name='Fecha de valoración')),
                ('nominal_value_per_share', models.DecimalField(blank=True, decimal_places=2, help_text='Valor nominal asignado a cada acción.', max_digits=18, null=True, verbose_name='Valor nominal por acción')),
                ('book_value_per_share', models.DecimalField(blank=True, decimal_places=2, help_text='Valor contable actual de cada acción.', max_digits=18, null=True, verbose_name='Valor contable por acción')),
                ('market_value_per_share', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de mercado actual de cada acción.', max_digits=18, null=True, verbose_name='Valor de mercado por acción')),
                ('es_pasivo', models.BooleanField(default=True, help_text='Indica si el movimiento corresponde a un activo')),
                ('code', models.CharField(blank=True, help_text='Identificador único interno del pasivo.', max_length=50, null=True, unique=True, verbose_name='Código del pasivo')),
                ('name', models.CharField(blank=True, help_text='Nombre descriptivo del pasivo.', max_length=255, null=True, verbose_name='Nombre del pasivo')),
                ('description', models.TextField(blank=True, help_text='Detalle o explicación adicional del pasivo.', null=True, verbose_name='Descripción')),
                ('liability_type', models.CharField(blank=True, choices=[('current', 'Corriente'), ('non_current', 'No corriente'), ('financial', 'Financiero'), ('tax', 'Fiscal'), ('labor', 'Laboral'), ('commercial', 'Comercial'), ('contingent', 'Contingente'), ('convertible', 'Convertible')], help_text='Clasificación contable del pasivo.', max_length=20, null=True, verbose_name='Tipo de pasivo')),
                ('origin_date', models.DateField(blank=True, help_text='Fecha en que se generó la obligación.', null=True, verbose_name='Fecha de origen')),
                ('due_date', models.DateField(blank=True, help_text='Fecha límite para cumplir la obligación.', null=True, verbose_name='Fecha de vencimiento')),
                ('initial_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto original de la obligación.', max_digits=18, null=True, verbose_name='Monto inicial')),
                ('currency', models.CharField(blank=True, help_text='Moneda en la que está expresado el pasivo.', max_length=10, null=True, verbose_name='Moneda')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Tipo de cambio aplicado si la moneda es extranjera.', max_digits=18, null=True, verbose_name='Tipo de cambio')),
                ('payments_made', models.DecimalField(blank=True, decimal_places=2, help_text='Monto total pagado hasta la fecha.', max_digits=18, null=True, verbose_name='Pagos realizados')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de interés nominal anual expresada en porcentaje.', max_digits=8, null=True, verbose_name='Tasa de interés')),
                ('interest_accrued_manual', models.DecimalField(blank=True, decimal_places=2, help_text='Intereses acumulados registrados manualmente (si aplica).', max_digits=18, null=True, verbose_name='Intereses acumulados manuales')),
                ('penalties', models.DecimalField(blank=True, decimal_places=2, help_text='Multas o penalidades acumuladas.', max_digits=18, null=True, verbose_name='Penalidades')),
                ('financial_expenses', models.DecimalField(blank=True, decimal_places=2, help_text='Costos financieros adicionales asociados.', max_digits=18, null=True, verbose_name='Gastos financieros')),
                ('creditor', models.CharField(blank=True, help_text='Entidad o persona a quien se le debe la obligación.', max_length=255, null=True, verbose_name='Acreedor')),
                ('contract_number', models.CharField(blank=True, help_text='Número identificador del contrato asociado.', max_length=100, null=True, verbose_name='Número de contrato')),
                ('guarantee_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado de la garantía asociada al pasivo.', max_digits=18, null=True, verbose_name='Valor de la garantía')),
                ('conversion_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por acción en caso de conversión a capital.', max_digits=18, null=True, verbose_name='Precio de conversión')),
                ('total_shares_issued', models.PositiveIntegerField(blank=True, help_text='Total de acciones actualmente emitidas por la sociedad.', null=True, verbose_name='Total de acciones emitidas')),
                ('total_share_capital', models.DecimalField(blank=True, decimal_places=2, help_text='Capital social actual de la empresa.', max_digits=18, null=True, verbose_name='Capital social total')),
                ('status', models.CharField(blank=True, choices=[('active', 'Vigente'), ('paid', 'Pagado'), ('refinanced', 'Refinanciado'), ('default', 'En mora'), ('cancelled', 'Cancelado')], help_text='Estado actual del pasivo.', max_length=20, null=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el sistema.', null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de modificación del registro.', null=True, verbose_name='Fecha de actualización')),
            ],
        ),
    ]
