# Generated by Django 4.2.23 on 2026-02-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='banco',
            field=models.CharField(blank=True, choices=[('banco_a', 'Banco A'), ('banco_b', 'Banco B'), ('banco_c', 'Banco C')], help_text='Banco donde se realiza el cobro.', max_length=30, null=True, verbose_name='Institución Bancaria'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='codigo_referencia_pago',
            field=models.CharField(blank=True, help_text='Número de referencia de la transacción bancaria o comprobante de pago.', max_length=150, null=True, verbose_name='Código de referencia de pago'),
        ),
    ]
