# Generated by Django 4.2.23 on 2026-02-06 23:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0008_estadofinanciero_analisis_activos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadofinanciero',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='analisis_activos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='liquidez',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='margen_utilidad_bruta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='margen_utilidad_neta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='rentabilidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
