# Generated by Django 4.2.23 on 2026-02-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0010_movimientofinanciero'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que el movimiento se creó en el sistema.', null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='es_egreso',
            field=models.BooleanField(default=False, help_text='Indica si el movimiento corresponde a un ingreso (False) o a un egreso (True).'),
        ),
    ]
