# Generated by Django 4.2.23 on 2026-02-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0011_movimientofinanciero_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadofinanciero',
            old_name='analisis_activos',
            new_name='analisis_flujo_financiero',
        ),
        migrations.RenameField(
            model_name='estadofinanciero',
            old_name='liquidez',
            new_name='ratio_cobertura',
        ),
    ]
