# Generated by Django 4.2.23 on 2026-02-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0014_estadofinanciero_inversiones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadofinanciero',
            old_name='deducion_gastos',
            new_name='deduccion_gastos',
        ),
        migrations.RenameField(
            model_name='estadofinanciero',
            old_name='deducion_gastos_currency',
            new_name='deduccion_gastos_currency',
        ),
    ]
