# Generated by Django 4.2.23 on 2026-02-08 05:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0015_rename_deducion_gastos_estadofinanciero_deduccion_gastos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadofinanciero',
            name='porcentaje_ventas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='confirmado',
            field=models.BooleanField(default=False, help_text='Indica si el movimiento ya fue confirmado/validado contablemente.', verbose_name='Acreditado'),
        ),
    ]
