# Generated by Django 4.2.23 on 2026-02-09 00:00

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0016_estadofinanciero_porcentaje_ventas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadofinanciero',
            name='cuentas_por_cobrar',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='cuentas_por_pagar',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='declaracion_iva',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='deduccion_gastos',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='gastos_fijos',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='gastos_legales',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='gastos_nomina',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='gastos_operativos',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='gastos_publicitarios',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='gastos_tributarios',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='categoria',
            field=models.CharField(blank=True, choices=[('gastos_fijos', 'Gastos fijos (servicios)'), ('gastos_operativos', 'Gastos operativos'), ('gastos_publicitarios', 'Gastos publicitarios'), ('gastos_legales', 'Gastos legales'), ('gastos_nomina', 'Gastos de nómina'), ('gastos_tributarios', 'Gastos tributarios'), ('declaracion_iva', 'Declaración I.V.A'), ('deuda', 'Deuda'), ('ventas', 'Ventas'), ('deducciones', 'Deducción Tributaria'), ('inversion', 'Inversión')], help_text='Clasificación contable del movimiento financiero.', max_length=30, null=True),
        ),
    ]
