# Generated by Django 4.2.23 on 2026-02-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0017_alter_estadofinanciero_cuentas_por_cobrar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='categoria_ingresos',
            field=models.CharField(blank=True, choices=[('ventas', 'Ventas'), ('deducciones', 'Deducción Tributaria'), ('inversion', 'Inversión')], help_text='Clasificación contable del movimiento financiero.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='categoria',
            field=models.CharField(blank=True, choices=[('gastos_fijos', 'Gastos fijos (servicios)'), ('gastos_operativos', 'Gastos operativos'), ('gastos_publicitarios', 'Gastos publicitarios'), ('gastos_legales', 'Gastos legales'), ('gastos_nomina', 'Gastos de nómina'), ('gastos_tributarios', 'Gastos tributarios'), ('declaracion_iva', 'Declaración I.V.A'), ('deuda', 'Deuda')], help_text='Clasificación contable del movimiento financiero.', max_length=30, null=True),
        ),
    ]
