# Generated by Django 4.2.23 on 2026-02-09 02:26

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0019_estadofinanciero_cuentas_cobrar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadofinanciero',
            old_name='cuentas_por_cobrar',
            new_name='acciones_legales',
        ),
        migrations.RenameField(
            model_name='estadofinanciero',
            old_name='cuentas_por_cobrar_currency',
            new_name='acciones_legales_currency',
        ),
        migrations.RenameField(
            model_name='estadofinanciero',
            old_name='cuentas_por_pagar',
            new_name='deudas_pagar',
        ),
        migrations.RenameField(
            model_name='estadofinanciero',
            old_name='cuentas_por_pagar_currency',
            new_name='deudas_pagar_currency',
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='cuentas_cobrar',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='cuentas_pagar',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='categoria',
            field=models.CharField(blank=True, choices=[('gastos_fijos', 'Gastos fijos (servicios)'), ('gastos_operativos', 'Gastos operativos'), ('gastos_publicitarios', 'Gastos publicitarios'), ('gastos_legales', 'Gastos legales'), ('gastos_nomina', 'Gastos de nómina'), ('gastos_tributarios', 'Gastos tributarios'), ('pago_deuda', 'Pago de Deuda')], help_text='Clasificación contable del movimiento financiero.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='categoria_ingresos',
            field=models.CharField(blank=True, choices=[('ventas', 'Ventas'), ('deducciones', 'Deducción Tributaria'), ('inversion', 'Inversión'), ('acciones_legales', 'Acción Legal')], help_text='Clasificación contable del movimiento financiero.', max_length=30, null=True),
        ),
    ]
