# Generated by Django 4.2.23 on 2026-02-10 00:19

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0022_estadofinanciero_total_efectivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadofinanciero',
            name='total_efectivo',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='Total de Efectivo  contable', max_digits=12, null=True, verbose_name='Efectivo Contable'),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='total_efectivo_bancos',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='Total efectivo en bancos registrados', max_digits=12, null=True, verbose_name='Efectivo Bancos'),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='umbral_conciliacion',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje máximo permitido de 1% para considerar conciliado', max_digits=5, verbose_name='Umbral de conciliación (%)'),
        ),
    ]
