# Generated by Django 4.2.23 on 2026-02-10 00:39

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0024_alter_estadofinanciero_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadofinanciero',
            name='fecha_fin',
            field=models.DateField(help_text='Fecha de corte del período contable analizado', verbose_name='Elegir fecha de inicio para análisis'),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='fecha_inicio',
            field=models.DateField(help_text='Fecha inicial del período contable analizado', verbose_name='Elegir fecha de inicio para análisis'),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='total_egresos_bancos',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', help_text='Escriba el valor total de egresos registrados e identificados en las cuentas bancarias, Ej: 1000.2', max_digits=12, verbose_name='Egresos bancarios'),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='total_ingresos_bancos',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', help_text='Escriba el valor total de ingresos registrados e identificados en las cuentas bancarias, Ej: 1000.2', max_digits=12, verbose_name='Ingresos bancarios'),
        ),
        migrations.AlterField(
            model_name='estadofinanciero',
            name='umbral_conciliacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Porcentaje máximo permitido para considerar conciliado', max_digits=5, verbose_name='Umbral de conciliación (%)'),
        ),
    ]
