# Generated by Django 4.2.23 on 2026-02-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0026_estadofinanciero_diferencia_egresos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadofinanciero',
            name='nombre_banco',
            field=models.CharField(blank=True, choices=[('banco_pichincha', 'Banco Pichincha'), ('banco_guayaquil', 'Banco de Guayaquil'), ('produbanco', 'Produbanco'), ('banco_internacional', 'Banco Internacional'), ('banco_del_austro', 'Banco del Austro'), ('banco_provincial', 'Banco del Pacífico'), ('coopac', 'Cooperativa COOPAC'), ('banco_bolivariano', 'Banco Bolivariano'), ('banco_dell_sol', 'Banco del Sol'), ('banco_machala', 'Banco Machala'), ('banco_farmacias', 'Banco de las Farmacias'), ('banco_florencia', 'Banco Florencia'), ('banco_ambato', 'Banco Ambato'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('diners', 'Diners Club'), ('discover', 'Discover'), ('jcb', 'JCB'), ('unionpay', 'UnionPay'), ('paymentez', 'Paymentez'), ('datafast', 'Datafast'), ('payphone', 'PayPhone'), ('banco_pichincha_online', 'Banco Pichincha Online'), ('banco_guayaquil_online', 'Banco de Guayaquil Online'), ('redeban', 'Redeban'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('mercadopago', 'MercadoPago'), ('square', 'Square'), ('otros', 'Otro')], help_text='Identifique el banco correspondiente para analizar.', max_length=30, null=True, verbose_name='Institución Bancaria'),
        ),
    ]
