# Generated by Django 4.2.23 on 2026-02-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinessanalytics_id', '0029_alter_estadofinanciero_nombre_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='es_ingreso',
            field=models.BooleanField(default=True, help_text='Indica si el movimiento corresponde a un ingreso (True) o a un egreso (False).'),
        ),
    ]
