# Generated by Django 4.2.23 on 2026-01-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulacion',
            name='iess_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regulacion',
            name='mt_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regulacion',
            name='scvs_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regulacion',
            name='spdp_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regulacion',
            name='sri_extra',
            field=models.BooleanField(default=False),
        ),
    ]
