# Generated by Django 4.2.23 on 2026-01-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0002_regulacion_iess_extra_regulacion_mt_extra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spdp_actadelegado',
            options={'verbose_name': 'Registro SPDP DPD / RAT / Incidentes', 'verbose_name_plural': 'Registros SPDP DPD / RAT / Incidentes'},
        ),
        migrations.RemoveField(
            model_name='spdp_actadelegado',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='spdp_actadelegado',
            name='funciones',
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='acto_designacion',
            field=models.CharField(blank=True, help_text='Número o referencia del acto administrativo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='archivo_incidente',
            field=models.FileField(blank=True, null=True, upload_to='spdp/incidentes/'),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='correo_delegado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='declaracion_confidencialidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='declaracion_independencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='funciones_delegado',
            field=models.TextField(blank=True, help_text='Funciones del DPD conforme a la LOPDP', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='identificacion_delegado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_datos_afectados',
            field=models.TextField(blank=True, help_text='Datos personales afectados', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del incidente', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_estado',
            field=models.CharField(blank=True, choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_fecha_deteccion',
            field=models.DateField(blank=True, help_text='Fecha de detección del incidente', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_fecha_notificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_identificacion',
            field=models.CharField(blank=True, help_text='Código o identificación del incidente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_medidas_correctivas',
            field=models.TextField(blank=True, help_text='Medidas correctivas implementadas', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_medidas_mitigacion',
            field=models.TextField(blank=True, help_text='Medidas de mitigación adoptadas', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_notificado_spdp',
            field=models.BooleanField(default=False, help_text='¿El incidente fue notificado a la SPDP?'),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_riesgo',
            field=models.CharField(blank=True, help_text='Nivel de riesgo (bajo, medio, alto)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_tipo',
            field=models.CharField(blank=True, help_text='Tipo de incidente (confidencialidad, integridad, disponibilidad)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='incidente_titulares_afectados',
            field=models.TextField(blank=True, help_text='Categoría de titulares afectados', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_base_legal',
            field=models.CharField(blank=True, help_text='Base legal del tratamiento según LOPDP', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_categoria_datos',
            field=models.TextField(blank=True, help_text='Categorías de datos personales tratados', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_categoria_destinatarios',
            field=models.TextField(blank=True, help_text='Destinatarios o terceros receptores de datos', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_categoria_titulares',
            field=models.TextField(blank=True, help_text='Categorías de titulares de datos', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_encargado_tratamiento',
            field=models.CharField(blank=True, help_text='Encargado del tratamiento, si aplica', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_finalidad',
            field=models.TextField(blank=True, help_text='Finalidad específica del tratamiento', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_medidas_organizativas',
            field=models.TextField(blank=True, help_text='Medidas organizativas de seguridad aplicadas', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_medidas_tecnicas',
            field=models.TextField(blank=True, help_text='Medidas técnicas de seguridad aplicadas', null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_nombre_tratamiento',
            field=models.CharField(blank=True, help_text='Nombre o identificación del tratamiento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_pais_transferencia',
            field=models.CharField(blank=True, help_text='País u organismo internacional receptor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_plazo_conservacion',
            field=models.CharField(blank=True, help_text='Plazo o criterio de conservación de datos', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_responsable_tratamiento',
            field=models.CharField(blank=True, help_text='Responsable del tratamiento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_transferencias_internacionales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='telefono_delegado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='tipo_vinculacion',
            field=models.CharField(blank=True, choices=[('dependencia', 'Relación de dependencia'), ('servicios', 'Prestación de servicios'), ('externo', 'Delegado externo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spdp_actadelegado',
            name='fecha_nombramiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spdp_actadelegado',
            name='nombre_delegado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
