# Generated by Django 4.2.23 on 2026-01-31 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('smartbusinesslaw', '0003_alter_spdp_actadelegado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spdp_actadelegado',
            name='rat_encargado_tratamiento',
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_titular_datos',
            field=models.ForeignKey(blank=True, help_text='Usuario titular de los datos personales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rat_tratamientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='spdp_actadelegado',
            name='rat_categoria_titulares',
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_categoria_titulares',
            field=models.ManyToManyField(blank=True, help_text='Grupos de usuarios que actúan como titulares de los datos', related_name='rat_tratamientos', to='auth.group'),
        ),
    ]
