# Generated by Django 4.2.23 on 2026-01-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0005_alter_spdp_actadelegado_rat_base_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spdp_actadelegado',
            name='rat_categoria_datos',
            field=models.JSONField(blank=True, choices=[('personales', 'Datos personales'), ('sensibles', 'Datos sensibles'), ('financieros', 'Datos financieros'), ('salud', 'Datos de salud'), ('laborales', 'Datos laborales')], help_text='Categorías de datos personales tratados. Seleccione uno o varios.', null=True),
        ),
        migrations.AlterField(
            model_name='spdp_actadelegado',
            name='rat_categoria_destinatarios',
            field=models.JSONField(blank=True, choices=[('internos', 'Departamentos internos'), ('externos', 'Proveedores de servicios'), ('entidades_gubernamentales', 'Entidades gubernamentales'), ('terceros_autorizados', 'Terceros autorizados')], help_text='Destinatarios o terceros receptores de datos. Seleccione uno o varios.', null=True),
        ),
    ]
