# Generated by Django 4.2.23 on 2026-01-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0007_alter_spdp_actadelegado_rat_base_legal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='hash_delegado',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='hash_incidente',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='hash_rat',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
