# Generated by Django 4.2.23 on 2026-01-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('smartbusinesslaw', '0008_spdp_actadelegado_hash_delegado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, editable=False, help_text='Fecha automática de expiración (fecha de creación + 310 días)', null=True),
        ),
        migrations.AlterField(
            model_name='spdp_actadelegado',
            name='rat_categoria_titulares',
            field=models.ManyToManyField(blank=True, help_text='Grupos de usuarios que actúan como titulares de los datos', to='auth.group'),
        ),
    ]
