# Generated by Django 4.2.23 on 2026-02-04 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0012_scvsfinancialreport_alter_spdp_actadelegado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scvs_actasasamblea',
            options={'verbose_name': 'Acta de Junta General SCVS', 'verbose_name_plural': 'Actas de Junta General SCVS'},
        ),
        migrations.AlterModelOptions(
            name='scvsfinancialreport',
            options={'verbose_name': 'Balance: SuperIntendencia de Compañías, Valores y Seguros', 'verbose_name_plural': 'Balances: SuperIntendencia de Compañías, Valores y Seguros'},
        ),
        migrations.AlterModelOptions(
            name='spdp_actadelegado',
            options={'verbose_name': 'Registro: Superintendencia de Protección de Datos Personales (SPDP)', 'verbose_name_plural': 'Registros: Superintendencia de Protección de Datos Personales (SPDP)'},
        ),
        migrations.RemoveField(
            model_name='scvs_actasasamblea',
            name='asistentes',
        ),
        migrations.RemoveField(
            model_name='scvs_actasasamblea',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='scvs_actasasamblea',
            name='tema_tratado',
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='abogado_patrocinador',
            field=models.CharField(blank=True, help_text='Nombre del abogado patrocinador que certifica el acta.', max_length=255, null=True, verbose_name='Abogado patrocinador'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='administradores_asistentes',
            field=models.TextField(blank=True, help_text='Listado de administradores presentes en la Junta.', null=True, verbose_name='Administradores asistentes'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='admins_anio_fiscal',
            field=models.PositiveIntegerField(blank=True, help_text='Año fiscal al que corresponde la nómina de administradores.', null=True, verbose_name='Año fiscal (administradores)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='admins_detalle',
            field=models.TextField(blank=True, help_text='Listado estructurado de administradores. Debe incluir: nombres, tipo y número de identificación, cargo, fecha de inicio y fin de funciones, forma de designación, nacionalidad.', null=True, verbose_name='Detalle de administradores'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='admins_fecha_certificacion',
            field=models.DateField(blank=True, help_text='Fecha de certificación de la nómina de administradores.', null=True, verbose_name='Fecha de certificación (administradores)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='admins_fecha_vigencia',
            field=models.DateField(blank=True, help_text='Fecha desde la cual se encuentra vigente el nombramiento de los administradores.', null=True, verbose_name='Fecha de vigencia del nombramiento'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='admins_observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales relacionadas con la nómina de administradores.', null=True, verbose_name='Observaciones (administradores)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='admins_representante_legal',
            field=models.CharField(blank=True, help_text='Nombre del representante legal que certifica la nómina de administradores.', max_length=255, null=True, verbose_name='Representante legal (administradores)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='admins_representante_legal_vigente',
            field=models.BooleanField(blank=True, help_text='Indica si el representante legal consta como vigente en la nómina.', null=True, verbose_name='Representante legal vigente'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='admins_secretario',
            field=models.CharField(blank=True, help_text='Nombre del secretario que certifica la nómina de administradores.', max_length=255, null=True, verbose_name='Secretario de la compañía'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='capital_presente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capital presente o debidamente representado en la Junta.', max_digits=18, null=True, verbose_name='Capital presente o representado'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='capital_suscrito_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capital suscrito total de la compañía.', max_digits=18, null=True, verbose_name='Capital suscrito total'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='contador',
            field=models.CharField(blank=True, help_text='Nombre del contador responsable de la información financiera.', max_length=255, null=True, verbose_name='Contador'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='convocatoria_valida',
            field=models.BooleanField(blank=True, help_text='Indica si la convocatoria cumple los requisitos legales.', null=True, verbose_name='Convocatoria válida'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='desarrollo_junta',
            field=models.TextField(blank=True, help_text='Descripción del desarrollo de la Junta y deliberaciones.', null=True, verbose_name='Desarrollo de la Junta'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='ejercicio_fiscal',
            field=models.PositiveIntegerField(blank=True, help_text='Ejercicio económico al que corresponde la Junta General.', null=True, verbose_name='Ejercicio fiscal'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='fecha_certificacion',
            field=models.DateField(blank=True, help_text='Fecha en que el documento fue certificado y firmado.', null=True, verbose_name='Fecha de certificación'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='fecha_convocatoria',
            field=models.DateField(blank=True, help_text='Fecha en la que se realizó la convocatoria formal.', null=True, verbose_name='Fecha de convocatoria'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='forma_convocatoria',
            field=models.CharField(blank=True, help_text='Medio utilizado para convocar a la Junta (prensa, correo, estatuto o universal).', max_length=50, null=True, verbose_name='Forma de convocatoria'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_abogado',
            field=models.CharField(blank=True, help_text='Nombre del abogado patrocinador del informe del gerente.', max_length=255, null=True, verbose_name='Abogado patrocinador'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_anio_fiscal',
            field=models.PositiveIntegerField(blank=True, help_text='Año fiscal al que corresponde el informe del gerente.', null=True, verbose_name='Año fiscal (informe del gerente)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_cargo',
            field=models.CharField(blank=True, help_text='Cargo oficial del gerente general.', max_length=255, null=True, verbose_name='Cargo del gerente'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_conclusion',
            field=models.TextField(blank=True, help_text='Conclusión final del informe del gerente.', null=True, verbose_name='Conclusión'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_cumplimiento_legal',
            field=models.TextField(blank=True, help_text='Declaración de cumplimiento normativo y legal.', null=True, verbose_name='Cumplimiento normativo'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_decisiones',
            field=models.TextField(blank=True, help_text='Principales decisiones administrativas adoptadas durante el ejercicio.', null=True, verbose_name='Decisiones administrativas'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_declaracion_responsabilidad',
            field=models.TextField(blank=True, help_text='Declaración expresa de responsabilidad del gerente general.', null=True, verbose_name='Declaración de responsabilidad'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_desempeno_operativo',
            field=models.TextField(blank=True, help_text='Análisis del desempeño operativo del ejercicio.', null=True, verbose_name='Desempeño operativo'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_eventos_relevantes',
            field=models.TextField(blank=True, help_text='Eventos relevantes ocurridos durante el ejercicio fiscal.', null=True, verbose_name='Eventos relevantes'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_fecha_emision',
            field=models.DateField(blank=True, help_text='Fecha de emisión del informe del gerente.', null=True, verbose_name='Fecha de emisión del informe'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_firma',
            field=models.CharField(blank=True, help_text='Nombre del gerente general que firma el informe.', max_length=255, null=True, verbose_name='Firma del gerente general'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_introduccion',
            field=models.TextField(blank=True, help_text='Introducción general del informe del gerente.', null=True, verbose_name='Introducción del informe'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_nombre',
            field=models.CharField(blank=True, help_text='Nombre completo del Gerente General que emite el informe.', max_length=255, null=True, verbose_name='Nombre del gerente general'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_objeto_social',
            field=models.TextField(blank=True, help_text='Evaluación del cumplimiento del objeto social de la compañía.', null=True, verbose_name='Cumplimiento del objeto social'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_periodo_informado',
            field=models.CharField(blank=True, help_text='Periodo que cubre el informe del gerente.', max_length=100, null=True, verbose_name='Periodo informado'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_proyecciones',
            field=models.TextField(blank=True, help_text='Perspectivas y proyecciones futuras de la compañía.', null=True, verbose_name='Perspectivas futuras'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_representante_legal',
            field=models.CharField(blank=True, help_text='Nombre del representante legal que suscribe el informe del gerente.', max_length=255, null=True, verbose_name='Representante legal (informe gerente)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_riesgos',
            field=models.TextField(blank=True, help_text='Riesgos y contingencias identificados por la gerencia.', null=True, verbose_name='Riesgos y contingencias'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='gerente_situacion_financiera',
            field=models.TextField(blank=True, help_text='Descripción de la situación financiera de la compañía.', null=True, verbose_name='Situación financiera'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='hora_cierre',
            field=models.TimeField(blank=True, help_text='Hora de clausura de la Junta General.', null=True, verbose_name='Hora de cierre'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio formal de la Junta General.', null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='informe_gerente',
            field=models.TextField(blank=True, help_text='Informe narrativo del gerente sobre la gestión del ejercicio fiscal.', null=True, verbose_name='Informe del gerente'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='lugar_asamblea',
            field=models.CharField(blank=True, help_text='Ciudad y dirección donde se celebró la Junta General.', max_length=255, null=True, verbose_name='Lugar de la asamblea'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='medio_convocatoria',
            field=models.TextField(blank=True, help_text='Detalle del medio de convocatoria utilizado.', null=True, verbose_name='Medio de convocatoria'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='orden_dia',
            field=models.TextField(blank=True, help_text='Listado completo de los puntos tratados en la Junta.', null=True, verbose_name='Orden del día'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='porcentaje_asistencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje del capital presente respecto al total.', max_digits=5, null=True, verbose_name='Porcentaje de asistencia'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='presidente_junta',
            field=models.CharField(blank=True, help_text='Nombre completo del presidente de la Junta General.', max_length=255, null=True, verbose_name='Presidente de la Junta'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='quorum_valido',
            field=models.BooleanField(blank=True, help_text='Indica si se cumple el quórum legal para deliberar.', null=True, verbose_name='Quórum válido'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='representante_legal',
            field=models.CharField(blank=True, help_text='Nombre del representante legal de la compañía.', max_length=255, null=True, verbose_name='Representante legal'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='resoluciones',
            field=models.TextField(blank=True, help_text='Detalle completo de las resoluciones aprobadas.', null=True, verbose_name='Resoluciones adoptadas'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='resultados_votacion',
            field=models.TextField(blank=True, help_text='Detalle de votos a favor, en contra y abstenciones.', null=True, verbose_name='Resultados de votación'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='secretario_junta',
            field=models.CharField(blank=True, help_text='Nombre completo del secretario de la Junta General.', max_length=255, null=True, verbose_name='Secretario de la Junta'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_anio_fiscal',
            field=models.PositiveIntegerField(blank=True, help_text='Año fiscal al que corresponde la nómina de socios o accionistas.', null=True, verbose_name='Año fiscal (Nómina de socios)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_asistentes',
            field=models.TextField(blank=True, help_text='Listado detallado de socios o accionistas asistentes, con acciones y porcentajes.', null=True, verbose_name='Socios / Accionistas asistentes'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_capital_pagado_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capital efectivamente pagado según la nómina de socios.', max_digits=18, null=True, verbose_name='Capital pagado total (socios)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_capital_suscrito_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capital suscrito total según la nómina de socios.', max_digits=18, null=True, verbose_name='Capital suscrito total (socios)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_contador',
            field=models.CharField(blank=True, help_text='Nombre del contador responsable de certificar la nómina de socios.', max_length=255, null=True, verbose_name='Contador (socios)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_detalle',
            field=models.TextField(blank=True, help_text='Listado estructurado de socios o accionistas. Debe incluir por cada socio: tipo de persona, nombres/razón social, nacionalidad, tipo y número de identificación, número de acciones o participaciones, valor nominal, porcentaje de participación, tipo de aporte, capital suscrito y pagado.', null=True, verbose_name='Detalle de socios / accionistas'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_fecha_certificacion',
            field=models.DateField(blank=True, help_text='Fecha de certificación de la nómina de socios.', null=True, verbose_name='Fecha de certificación (socios)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_fecha_corte',
            field=models.DateField(blank=True, help_text='Fecha de corte de la información de socios o accionistas.', null=True, verbose_name='Fecha de corte de la nómina'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_representante_legal',
            field=models.CharField(blank=True, help_text='Nombre del representante legal que certifica la nómina de socios.', max_length=255, null=True, verbose_name='Representante legal (socios)'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_tipo_compania',
            field=models.CharField(blank=True, choices=[('SA', 'Sociedad Anónima'), ('LTDA', 'Compañía Limitada'), ('SAS', 'SAS')], help_text='Tipo de compañía según su forma societaria.', max_length=10, null=True, verbose_name='Tipo de compañía'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='socios_total_numero',
            field=models.PositiveIntegerField(blank=True, help_text='Número total de socios o accionistas registrados.', null=True, verbose_name='Total de socios / accionistas'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='tipo_junta',
            field=models.CharField(blank=True, choices=[('ORDINARIA', 'Junta Ordinaria'), ('EXTRAORDINARIA', 'Junta Extraordinaria'), ('UNIVERSAL', 'Junta Universal')], help_text='Tipo de Junta General celebrada según la Ley de Compañías.', max_length=20, null=True, verbose_name='Tipo de junta'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='scvs_actasasamblea',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo PDF del acta firmada para subir a la SCVS.', null=True, upload_to='scvs/actas/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='scvs_actasasamblea',
            name='fecha_asamblea',
            field=models.DateField(blank=True, help_text='Fecha en la que se celebró la Junta General.', null=True, verbose_name='Fecha de la asamblea'),
        ),
        migrations.AlterField(
            model_name='scvs_actasasamblea',
            name='regulacion',
            field=models.ForeignKey(help_text='Regulación o proceso legal al que pertenece este conjunto documental SCVS.', on_delete=django.db.models.deletion.CASCADE, related_name='scvs_actas', to='smartbusinesslaw.regulacion', verbose_name='Regulación asociada'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='accounts_payable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deudas con proveedores por compras de bienes o servicios a crédito.', max_digits=18, null=True, verbose_name='Cuentas por pagar'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='accounts_payable_related',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cuentas por pagar a empresas relacionadas o vinculadas a la compañía.', max_digits=18, null=True, verbose_name='Cuentas por pagar relacionadas'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='accounts_receivable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto total que clientes deben a la compañía por ventas a crédito.', max_digits=18, null=True, verbose_name='Cuentas por cobrar'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='accounts_receivable_related',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cuentas por cobrar a empresas relacionadas o vinculadas a la compañía.', max_digits=18, null=True, verbose_name='Cuentas por cobrar relacionadas'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='accumulated_depreciation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suma de la depreciación aplicada a los activos fijos desde su adquisición.', max_digits=18, null=True, verbose_name='Depreciación acumulada'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='administrative_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gastos relacionados con la administración general de la empresa (sueldos de gerencia, servicios, etc.)', max_digits=18, null=True, verbose_name='Gastos administrativos'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='cash_and_equivalents',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suma del efectivo en caja y bancos, más inversiones a corto plazo fácilmente convertibles en efectivo.', max_digits=18, null=True, verbose_name='Efectivo y equivalentes'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='cashflow_financing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entrada y salida de efectivo relacionadas con préstamos, emisión de acciones o dividendos.', max_digits=18, null=True, verbose_name='Flujos de financiamiento'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='cashflow_investing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entrada y salida de efectivo relacionadas con la compra o venta de activos a largo plazo.', max_digits=18, null=True, verbose_name='Flujos de inversión'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='cashflow_operating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entrada y salida de efectivo por operaciones normales de la compañía.', max_digits=18, null=True, verbose_name='Flujos de operación'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nombre legal completo de la compañía registrado ante la Superintendencia de Compañías.', max_length=255, null=True, verbose_name='Nombre de la compañía'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='company_type',
            field=models.CharField(blank=True, choices=[('SA', 'Sociedad Anónima'), ('LTDA', 'Compañía Limitada'), ('SAS', 'SAS')], help_text='Tipo legal de la sociedad según registro mercantil.', max_length=10, null=True, verbose_name='Tipo de sociedad'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='cost_of_sales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costos directamente relacionados con la producción o adquisición de bienes vendidos.', max_digits=18, null=True, verbose_name='Costo de ventas'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='currency',
            field=models.CharField(blank=True, default='USD', help_text='Moneda utilizada en los estados financieros. Normalmente USD para Ecuador.', max_length=10, null=True, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='economic_activity',
            field=models.CharField(blank=True, help_text='Código CIIU (Clasificación Internacional Industrial Uniforme) de la actividad económica principal de la empresa.', max_length=10, null=True, verbose_name='Actividad económica'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='employee_profit_sharing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de utilidades destinado a la participación de los trabajadores según ley.', max_digits=18, null=True, verbose_name='Participación de empleados'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='equity_closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo total del patrimonio al cierre del ejercicio fiscal.', max_digits=18, null=True, verbose_name='Saldo final del patrimonio'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='equity_decreases',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reducciones en el patrimonio durante el periodo, como distribución de dividendos o pérdidas netas.', max_digits=18, null=True, verbose_name='Disminuciones del patrimonio'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='equity_increases',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aumentos en el patrimonio durante el periodo, incluyendo aportes de socios y utilidades netas.', max_digits=18, null=True, verbose_name='Incrementos del patrimonio'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='equity_opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo total del patrimonio al inicio del ejercicio fiscal.', max_digits=18, null=True, verbose_name='Saldo inicial del patrimonio'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='financial_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Intereses pagados y otros costos financieros relacionados con deudas.', max_digits=18, null=True, verbose_name='Gastos financieros'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='financial_obligations_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de todas las deudas y préstamos, tanto a corto como a largo plazo.', max_digits=18, null=True, verbose_name='Obligaciones financieras totales'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='fiscal_year',
            field=models.PositiveIntegerField(blank=True, help_text='Año al que corresponde el reporte financiero. Ejemplo: 2025', null=True, verbose_name='Año fiscal'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='fixed_assets_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de adquisición de todos los activos fijos antes de depreciación.', max_digits=18, null=True, verbose_name='Costo de activos fijos'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='fixed_assets_depreciation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Depreciación acumulada de los activos fijos hasta la fecha del reporte.', max_digits=18, null=True, verbose_name='Depreciación de activos fijos'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingresos operativos menos el costo de ventas.', max_digits=18, null=True, verbose_name='Utilidad bruta'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='income_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del impuesto a la renta correspondiente al periodo fiscal.', max_digits=18, null=True, verbose_name='Impuesto a la renta'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='intangible_assets',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Activos no físicos con valor económico, como patentes, marcas o software.', max_digits=18, null=True, verbose_name='Activos intangibles'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='inventories',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de inventarios de bienes, materias primas y productos terminados listos para la venta.', max_digits=18, null=True, verbose_name='Inventarios'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='labor_obligations',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deudas con empleados, como salarios, bonos, prestaciones sociales o vacaciones pendientes.', max_digits=18, null=True, verbose_name='Obligaciones laborales'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='legal_reserve',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porción de las utilidades retenidas que la ley exige mantener como reserva legal.', max_digits=18, null=True, verbose_name='Reserva legal'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='long_term_loans',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obligaciones financieras con vencimiento mayor a un año.', max_digits=18, null=True, verbose_name='Préstamos a largo plazo'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='net_cash_flow',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Variación neta del efectivo durante el periodo: flujo de operación + inversión + financiamiento.', max_digits=18, null=True, verbose_name='Flujo neto de efectivo'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='net_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resultado neto del periodo fiscal: ingresos menos gastos e impuestos.', max_digits=18, null=True, verbose_name='Resultado neto'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='operating_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingresos generados por la actividad principal de la compañía (ventas de productos o servicios).', max_digits=18, null=True, verbose_name='Ingresos operativos'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='other_current_assets',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Otros activos que se espera convertir en efectivo o usar dentro del año fiscal.', max_digits=18, null=True, verbose_name='Otros activos corrientes'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='other_current_liabilities',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Otras obligaciones a corto plazo que la empresa debe cumplir dentro del año fiscal.', max_digits=18, null=True, verbose_name='Otros pasivos corrientes'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='other_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gastos no operativos, como pérdidas por venta de activos o gastos extraordinarios.', max_digits=18, null=True, verbose_name='Otros gastos'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='other_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingresos no operativos, como venta de activos, dividendos o ganancias extraordinarias.', max_digits=18, null=True, verbose_name='Otros ingresos'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='other_non_current_assets',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Activos que no se espera convertir en efectivo en menos de un año, distintos a los ya mencionados.', max_digits=18, null=True, verbose_name='Otros activos no corrientes'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='other_non_current_liabilities',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obligaciones financieras y no financieras con vencimiento mayor a un año distintas a las ya mencionadas.', max_digits=18, null=True, verbose_name='Otros pasivos no corrientes'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='property_plant_equipment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de terrenos, edificios, maquinaria y equipo utilizados en las operaciones de la empresa.', max_digits=18, null=True, verbose_name='Propiedad, planta y equipo'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='provisions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reservas de dinero para cubrir pasivos futuros o contingencias previstas.', max_digits=18, null=True, verbose_name='Provisiones'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='retained_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Utilidades o pérdidas acumuladas de ejercicios anteriores que se mantienen en la empresa.', max_digits=18, null=True, verbose_name='Resultados acumulados'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='ruc',
            field=models.CharField(blank=True, help_text='Número de RUC de la compañía (13 dígitos). Es el identificador único tributario en Ecuador.', max_length=13, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='selling_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gastos relacionados con la comercialización y distribución de productos o servicios.', max_digits=18, null=True, verbose_name='Gastos de ventas'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='share_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de aportes de los socios o accionistas registrado legalmente como capital social.', max_digits=18, null=True, verbose_name='Capital social'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='short_term_investments',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Inversiones temporales y valores negociables con vencimiento menor a un año.', max_digits=18, null=True, verbose_name='Inversiones a corto plazo'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='short_term_loans',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obligaciones financieras con vencimiento menor a un año.', max_digits=18, null=True, verbose_name='Préstamos a corto plazo'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='tax_payables',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Impuestos por pagar, incluyendo IVA, retenciones y otros tributos pendientes.', max_digits=18, null=True, verbose_name='Obligaciones tributarias'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
