# Generated by Django 4.2.23 on 2026-02-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0015_alter_sri_anexostributarios_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sri_declaracionimpuestos',
            options={},
        ),
        migrations.RemoveField(
            model_name='sri_declaracionimpuestos',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='sri_declaracionimpuestos',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='sri_declaracionimpuestos',
            name='fecha_presentacion',
        ),
        migrations.RemoveField(
            model_name='sri_declaracionimpuestos',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='sri_declaracionimpuestos',
            name='regulacion',
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='anticipos_renta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Anticipos y créditos aplicables.', max_digits=16, null=True, verbose_name='Anticipos y créditos tributarios'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='base_imponible_renta',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Base imponible calculada automáticamente.', max_digits=16, null=True, verbose_name='Base imponible del Impuesto a la Renta'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='base_patente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base imponible para patente municipal.', max_digits=16, null=True, verbose_name='Base imponible de patente municipal'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='costos_gastos_deducibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costos y gastos deducibles según normativa.', max_digits=16, null=True, verbose_name='Costos y gastos deducibles'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='fecha_declaracion',
            field=models.DateField(blank=True, help_text='Fecha de presentación de la declaración.', null=True, verbose_name='Fecha de declaración'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='ice_causado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ICE causado según actividad económica.', max_digits=14, null=True, verbose_name='Impuesto a los Consumos Especiales (ICE)'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='impuesto_renta_causado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Impuesto determinado antes de créditos.', max_digits=16, null=True, verbose_name='Impuesto a la Renta causado'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='ingresos_gravados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingresos sujetos a Impuesto a la Renta.', max_digits=16, null=True, verbose_name='Ingresos gravados'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='isd_causado',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='ISD calculado automáticamente (5%).', max_digits=14, null=True, verbose_name='Impuesto a la Salida de Divisas (ISD)'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='iva_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='IVA a pagar calculado automáticamente.', max_digits=14, null=True, verbose_name='IVA a pagar'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='iva_compras',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IVA pagado en compras con derecho a crédito tributario.', max_digits=14, null=True, verbose_name='IVA en compras'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='iva_ventas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IVA causado por ventas gravadas.', max_digits=14, null=True, verbose_name='IVA en ventas'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='pagos_exterior',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pagos sujetos a ISD.', max_digits=16, null=True, verbose_name='Pagos al exterior'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='patente_municipal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor anual de la patente municipal.', max_digits=14, null=True, verbose_name='Patente municipal'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='periodo',
            field=models.CharField(blank=True, help_text='Periodo fiscal declarado. Ejemplo: 01-2025 o 2025.', max_length=7, null=True, verbose_name='Periodo fiscal'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre o razón social del contribuyente.', max_length=255, null=True, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='regimen',
            field=models.CharField(blank=True, choices=[('RIMPE_EMPRENDEDOR', 'RIMPE Emprendedor'), ('RIMPE_POPULAR', 'RIMPE Negocio Popular'), ('REGIMEN_GENERAL', 'Régimen General')], help_text='Régimen tributario registrado ante el SRI.', max_length=20, null=True, verbose_name='Régimen tributario'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='renta_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Valor final del Impuesto a la Renta.', max_digits=16, null=True, verbose_name='Impuesto a la Renta a pagar'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='retencion_iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IVA retenido a terceros.', max_digits=14, null=True, verbose_name='Retención de IVA'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='retencion_renta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Retenciones de Impuesto a la Renta practicadas.', max_digits=14, null=True, verbose_name='Retención en la fuente de Renta'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='ruc',
            field=models.CharField(blank=True, help_text='Registro Único de Contribuyentes del sujeto pasivo.', max_length=13, null=True, verbose_name='RUC'),
        ),
    ]
