# Generated by Django 4.2.23 on 2026-02-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0017_sri_declaracionimpuestos_archivo_auditoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sri_declaracionimpuestos',
            name='periodo',
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='ejercicio_fiscal',
            field=models.PositiveIntegerField(blank=True, help_text='Año fiscal al que corresponde la información.', null=True, verbose_name='Ejercicio fiscal'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='mes',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], help_text='Mes correspondiente a los anexos (01=Enero, 12=Diciembre).', null=True, verbose_name='Mes'),
        ),
    ]
