# Generated by Django 4.2.30 on 2026-08-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paas_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tamano_empresa',
            field=models.CharField(blank=True, choices=[('1-10 usuarios', 'PYMES'), ('11-50 usuarios', ' STARTUP'), ('51-200 usuarios', 'ENTERPRISE'), ('200+ usuarios', 'INDUSTRIAL')], help_text='Selecciona el tamaño de tu empresa.', max_length=255, null=True, verbose_name='Tamaño de la Empresa'),
        ),
    ]
