# Generated by Django 4.2.30 on 2026-05-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paas_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tamano_empresa',
            field=models.CharField(blank=True, choices=[('1-10 usuarios', 'pymes'), ('11-50 usuarios', 'startups'), ('51-200 usuarios', 'enterprises'), ('200+ usuarios', 'industrial')], max_length=255, null=True, verbose_name='Tamaño de la Empresa'),
        ),
    ]
