# Generated by Django 4.2.30 on 2026-05-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paas_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vence_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
