# Generated by Django 4.2.30 on 2026-05-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_shop', '0002_alter_category_tamano_empresa'),
        ('paas_shop', '0002_category_tamano_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suite',
            name='suite',
        ),
        migrations.AddField(
            model_name='suite',
            name='suite',
            field=models.ManyToManyField(blank=True, max_length=200, null=True, to='saas_shop.product'),
        ),
    ]
