# Generated by Django 4.2.23 on 2026-01-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paas_shop', '0002_alter_category_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suite',
            field=models.CharField(blank=True, choices=[('SmartBusinessAnalytics® (I+D)', 'SmartBusinessAnalytics® (I+D)'), ('SmartBusinessAnalytics® (I+D+A)', 'SmartBusinessAnalytics® (I+D+A)'), ('SmartBusinessAnalytics® (I+D+A+AI)', 'SmartBusinessAnalytics® (I+D+A+AI)'), ('SmartBusinessMedia® (I+D)', 'SmartBusinessMedia® (I+D)'), ('SmartBusinessMedia® (I+D+A)', 'SmartBusinessMedia® (I+D+A)'), ('SmartBusinessMedia® (I+D+A+AI)', 'SmartBusinessMedia® (I+D+A+AI)'), ('SmartBusinessLaw® (I+D)', 'SmartBusinessLaw® (I+D)'), ('SmartBusinessLaw® (I+D+A)', 'SmartBusinessLaw® (I+D+A)'), ('SmartBusinessLaw® (I+D+A+AI)', 'SmartBusinessLaw® (I+D+A+AI)')], max_length=200, null=True),
        ),
    ]
