# Generated by Django 4.2.30 on 2026-05-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paas_shop', '0003_remove_suite_suite_suite_suite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='suite',
        ),
        migrations.AddField(
            model_name='product',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='paas_shop.suite'),
        ),
    ]
