# Generated by Django 4.2.23 on 2026-01-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paas_shop', '0003_product_suite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('suite', models.CharField(blank=True, choices=[('SmartBusinessAnalytics® (I+D)', 'SmartBusinessAnalytics® (I+D)'), ('SmartBusinessAnalytics® (I+D+A)', 'SmartBusinessAnalytics® (I+D+A)'), ('SmartBusinessAnalytics® (I+D+A+AI)', 'SmartBusinessAnalytics® (I+D+A+AI)'), ('SmartBusinessMedia® (I+D)', 'SmartBusinessMedia® (I+D)'), ('SmartBusinessMedia® (I+D+A)', 'SmartBusinessMedia® (I+D+A)'), ('SmartBusinessMedia® (I+D+A+AI)', 'SmartBusinessMedia® (I+D+A+AI)'), ('SmartBusinessLaw® (I+D)', 'SmartBusinessLaw® (I+D)'), ('SmartBusinessLaw® (I+D+A)', 'SmartBusinessLaw® (I+D+A)'), ('SmartBusinessLaw® (I+D+A+AI)', 'SmartBusinessLaw® (I+D+A+AI)')], max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='suite',
        ),
        migrations.AddField(
            model_name='product',
            name='suite',
            field=models.ManyToManyField(blank=True, related_name='products', to='paas_shop.suite'),
        ),
    ]
