# Generated by Django 4.2.30 on 2026-08-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paas_shop', '0003_alter_product_margen_sq_alter_product_margen_sq_arch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payback',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='PayBack(meses)'),
        ),
        migrations.AddField(
            model_name='product',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ROI(%)'),
        ),
    ]
