# Generated by Django 4.2.30 on 2026-05-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paas_shop', '0005_remove_suite_almacenamiento_remove_suite_ancho_banda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suite',
            name='suite',
        ),
        migrations.AddField(
            model_name='product',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='paas_shop.suite'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='paas_shop.category'),
        ),
    ]
