# Generated by Django 4.2.30 on 2026-05-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paas_shop', '0006_remove_suite_suite_product_suite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suite', to='paas_shop.suite'),
        ),
    ]
