# Generated by Django 4.2.23 on 2026-02-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAutomationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Prompt para generar el contenido con Gemini')),
                ('brand_voice', models.CharField(blank=True, max_length=255)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
