# Generated by Django 4.2.23 on 2026-02-23 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialautomationpost',
            options={'ordering': ['-scheduled_datetime'], 'verbose_name': 'Social Automation Post', 'verbose_name_plural': 'Social Automation Posts'},
        ),
        migrations.CreateModel(
            name='GeneratedSocialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('meta_post_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='generated', max_length=50)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('social_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_assets', to='core.socialautomationpost')),
            ],
        ),
    ]
