# Generated by Django 4.2.23 on 2026-02-24 01:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_socialautomationpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedsocialasset',
            options={'ordering': ['-id'], 'verbose_name': 'Generated Social Asset', 'verbose_name_plural': 'Generated Social Assets'},
        ),
        migrations.CreateModel(
            name='SocialPostSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('both', 'Ambos')], default='both', max_length=50)),
                ('caption', models.TextField(blank=True)),
                ('meta_post_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('scheduled', 'Programado'), ('posted', 'Publicado'), ('error', 'Error')], default='pending', max_length=20)),
                ('image', models.ForeignKey(help_text='Selecciona la imagen generada previamente', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='core.generatedsocialasset')),
            ],
        ),
    ]
