# Generated by Django 4.2.23 on 2026-02-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_generatedsocialasset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialautomationpost',
            name='brand_text',
            field=models.TextField(blank=True, help_text='Texto de la marca'),
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logotipo de la marca', null=True, upload_to='social_automation/logos/'),
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Imagen de referencia para el contenido', null=True, upload_to='social_automation/references/'),
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='title',
            field=models.CharField(blank=True, help_text='Título del post', max_length=255, null=True),
        ),
    ]
