# Generated by Django 4.2.23 on 2026-02-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_socialautomationpost_brand_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialautomationpost',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='social_automation/logos/'),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='social_automation/references/'),
        ),
    ]
