# Generated by Django 4.2.23 on 2026-02-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_socialautomationpost_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedsocialasset',
            options={'ordering': ['-id'], 'verbose_name': 'Post Instagram (AI+A)', 'verbose_name_plural': 'Posts Instagram (AI+A)'},
        ),
        migrations.AlterModelOptions(
            name='socialautomationpost',
            options={'ordering': ['-scheduled_datetime'], 'verbose_name': 'AI Content image Creator', 'verbose_name_plural': 'AI Content images Creators'},
        ),
        migrations.RemoveField(
            model_name='socialautomationpost',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='socialautomationpost',
            name='reference_image',
        ),
        migrations.AddField(
            model_name='generatedsocialasset',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='social_automation/logos/'),
        ),
        migrations.AddField(
            model_name='generatedsocialasset',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='social_automation/references/'),
        ),
    ]
