# Generated by Django 4.2.23 on 2026-02-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('core', '0007_alter_generatedsocialasset_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedsocialasset',
            options={'ordering': ['-id'], 'verbose_name': 'AI Brand Image Generation', 'verbose_name_plural': 'AI Brand Image Generations'},
        ),
        migrations.AlterModelOptions(
            name='socialautomationpost',
            options={'ordering': ['-scheduled_datetime'], 'verbose_name': 'AI Content Image Creator', 'verbose_name_plural': 'AI Content Image Creators'},
        ),
        migrations.AlterField(
            model_name='generatedsocialasset',
            name='caption',
            field=models.TextField(blank=True, help_text='Texto o caption para redes sociales'),
        ),
        migrations.AlterField(
            model_name='generatedsocialasset',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Imagen final editada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='generatedsocialasset',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Logo de la marca a incluir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='generatedsocialasset',
            name='meta_post_id',
            field=models.CharField(blank=True, help_text='ID del post en Meta (Instagram/Facebook)', max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedsocialasset',
            name='reference_image',
            field=models.ForeignKey(blank=True, help_text='Imagen de referencia desde SocialAutomationPost', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='generatedsocialasset',
            name='status',
            field=models.CharField(default='generated', help_text='Estado del asset: generated, sent_to_n8n, error', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='brand_text',
            field=models.TextField(blank=True, help_text='Texto de la marca para incluir en la imagen'),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='brand_voice',
            field=models.CharField(blank=True, help_text='Tono de la marca', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, help_text='Fecha programada para el posteo (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='status',
            field=models.CharField(default='pending', help_text='Estado del post: pending, processing, completed, error', max_length=50),
        ),
    ]
