# Generated by Django 4.2.23 on 2026-02-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_generatedsocialasset_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialautomationpost',
            name='prompt',
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='color_palette',
            field=models.CharField(blank=True, choices=[('pastel', 'Tonos pastel'), ('vibrant', 'Colores vibrantes'), ('monochrome', 'Monocromo'), ('dark_mode', 'Tonos oscuros'), ('light_mode', 'Tonos claros')], help_text='Categoría de paleta de colores de la imagen', max_length=50),
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='company_info_text',
            field=models.TextField(blank=True, help_text='Información adicional de la empresa para la imagen (website, contacto, descriptor)'),
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa para incluir en la imagen', null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='font_style',
            field=models.CharField(blank=True, choices=[('sans_serif', 'Sans-serif moderna'), ('serif', 'Serif clásica'), ('handwritten', 'Estilo manuscrito'), ('display', 'Tipografía llamativa / Display')], help_text='Tipo de tipografía para el texto de la imagen', max_length=50),
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='format',
            field=models.CharField(blank=True, choices=[('square', 'Cuadrado 1080x1080px'), ('portrait', 'Vertical 1080x1350px'), ('landscape', 'Horizontal 1080x566px'), ('story', 'Historia de Instagram 1080x1920px')], help_text='Formato de imagen para publicación', max_length=50),
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='style',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimalista'), ('modern', 'Moderno'), ('retro', 'Retro / Vintage'), ('illustrative', 'Ilustrativo / Vectorial'), ('photorealistic', 'Fotorealista'), ('cinematic', 'Cinemático / Dramático')], help_text='Estilo visual de la imagen', max_length=50),
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='title_text',
            field=models.TextField(blank=True, help_text='Texto principal / título que aparecerá en la imagen'),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='brand_text',
            field=models.TextField(blank=True, help_text='Texto de la marca que aparecerá en la imagen (slogan o mensaje)'),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='brand_voice',
            field=models.CharField(blank=True, choices=[('friendly', 'Amigable'), ('professional', 'Profesional'), ('aspirational', 'Aspiracional'), ('fun', 'Divertido'), ('luxury', 'Lujoso / Premium'), ('techy', 'Tecnológico / Innovador')], help_text='Tono de la marca', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', help_text='Estado del post', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='title',
            field=models.CharField(blank=True, choices=[('launch', 'Lanzamiento de producto'), ('promotion', 'Promoción / Oferta'), ('event', 'Evento especial'), ('testimonial', 'Testimonio / Historia de cliente'), ('educational', 'Educativo / Tips'), ('fun', 'Contenido divertido / meme')], help_text='Tipo de post para Instagram', max_length=255, null=True),
        ),
    ]
