# Generated by Django 4.2.23 on 2026-02-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_socialautomationpost_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialautomationpost',
            name='generated_image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen generada por la IA y almacenada en el bucket', null=True),
        ),
    ]
