# Generated by Django 4.2.23 on 2026-02-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aiinstagrampostpublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinstagrampostpublished',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Track ID de la tarea programada', max_length=255, null=True),
        ),
    ]
