# Generated by Django 4.2.23 on 2026-02-26 20:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('core', '0012_aiinstagrampostpublished_celery_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInstagramCarouselPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('post_type', models.CharField(blank=True, choices=[('educational', 'Educativo'), ('sales', 'Venta'), ('engagement', 'Engagement'), ('storytelling', 'Storytelling'), ('personal_brand', 'Marca Personal')], max_length=50, null=True)),
                ('tone', models.CharField(blank=True, choices=[('casual', 'Casual'), ('professional', 'Profesional'), ('friendly', 'Amigable'), ('authoritative', 'Autoridad'), ('inspirational', 'Inspirador')], max_length=50, null=True)),
                ('objective', models.CharField(blank=True, choices=[('increase_sales', 'Aumentar ventas'), ('generate_leads', 'Generar leads'), ('increase_engagement', 'Aumentar engagement'), ('educate', 'Educar audiencia'), ('brand_awareness', 'Reconocimiento de marca')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Borrador'), ('ready', 'Listo para publicar'), ('scheduled', 'Programado'), ('published', 'Publicado')], max_length=20, null=True)),
                ('ai_context', models.TextField(blank=True, help_text='Describe aquí todo el contexto para generar captions, copy y hashtags del carrusel', null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('call_to_action', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
            ],
            options={
                'verbose_name': 'AI Instagram Carousel Post',
                'verbose_name_plural': 'AI Instagram Carousel Posts',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, help_text='Caption individual de la imagen', max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('post', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='core.aiinstagramcarouselpost')),
            ],
        ),
    ]
