# Generated by Django 4.2.23 on 2026-02-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aiinstagramcarouselpost_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialautomationpost',
            name='generated_image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen generada por la IA y almacenada en el bucket', max_length=1000, null=True),
        ),
    ]
