# Generated by Django 4.2.23 on 2026-02-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_socialautomationpost_generated_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialautomationpost',
            name='image_context',
            field=models.TextField(blank=True, help_text='Contexto adicional para la generación de la imagen (mensaje, campaña, audiencia, etc.)'),
        ),
        migrations.AddField(
            model_name='socialautomationpost',
            name='image_type',
            field=models.CharField(blank=True, choices=[('web_landing', 'Web Landing Page'), ('instagram_carousel', 'Instagram Carrusel'), ('instagram_post', 'Instagram Post'), ('instagram_story', 'Instagram Stories')], help_text='Destino estratégico de la imagen', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='brand_text',
            field=models.TextField(blank=True, help_text='Texto de la marca (slogan o mensaje)'),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='color_palette',
            field=models.CharField(blank=True, choices=[('pastel', 'Tonos pastel'), ('vibrant', 'Colores vibrantes'), ('monochrome', 'Monocromo'), ('dark_mode', 'Tonos oscuros'), ('light_mode', 'Tonos claros')], help_text='Categoría de paleta de colores', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='company_info_text',
            field=models.TextField(blank=True, help_text='Información adicional (website, descriptor, contacto)'),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='font_style',
            field=models.CharField(blank=True, choices=[('sans_serif', 'Sans-serif moderna'), ('serif', 'Serif clásica'), ('handwritten', 'Estilo manuscrito'), ('display', 'Tipografía llamativa / Display')], help_text='Tipo de tipografía', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='format',
            field=models.CharField(blank=True, choices=[('square', 'Cuadrado 1080x1080px'), ('portrait', 'Vertical 1080x1350px'), ('landscape', 'Horizontal 1080x566px'), ('story', 'Historia de Instagram 1080x1920px')], help_text='Formato técnico de la imagen', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='generated_image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen generada por IA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, help_text='Fecha programada para el posteo', null=True),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialautomationpost',
            name='title_text',
            field=models.TextField(blank=True, help_text='Texto principal que aparecerá en la imagen'),
        ),
    ]
