# Generated by Django 4.2.23 on 2026-03-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_socialautomationpost_image_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAutomationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('product_demo', 'Demostración de producto'), ('tip', 'Tip / Educativo'), ('story', 'Historia / storytelling'), ('promotion', 'Promoción / oferta'), ('behind_scenes', 'Behind the scenes'), ('testimonial', 'Testimonio cliente'), ('trend', 'Trend / contenido viral')], help_text='Tipo estratégico de video', max_length=100)),
                ('platform', models.CharField(choices=[('instagram_reels', 'Instagram Reels'), ('tiktok', 'TikTok'), ('youtube_shorts', 'YouTube Shorts'), ('multi_platform', 'Multi plataforma')], default='multi_platform', max_length=100)),
                ('hook', models.CharField(blank=True, help_text='Frase de apertura que captura la atención en los primeros 3 segundos', max_length=300)),
                ('video_context', models.TextField(blank=True, help_text='Contexto del video: producto, audiencia, campaña, etc.')),
                ('script', models.TextField(blank=True, help_text='Guion del video generado o editado manualmente')),
                ('call_to_action', models.CharField(blank=True, choices=[('visit_website', 'Visitar website'), ('buy_now', 'Comprar ahora'), ('follow', 'Seguir cuenta'), ('comment', 'Comentar'), ('share', 'Compartir'), ('link_bio', 'Link en bio')], max_length=100)),
                ('duration', models.CharField(choices=[('7s', '7 segundos'), ('15s', '15 segundos'), ('30s', '30 segundos'), ('45s', '45 segundos'), ('60s', '60 segundos')], default='15s', max_length=20)),
                ('style', models.CharField(blank=True, choices=[('cinematic', 'Cinemático'), ('ugc', 'UGC estilo usuario'), ('minimal', 'Minimalista'), ('corporate', 'Corporativo'), ('dynamic', 'Dinámico / viral'), ('ai_generated', 'AI generado')], max_length=100)),
                ('music_style', models.CharField(blank=True, choices=[('upbeat', 'Energética'), ('corporate', 'Corporativa'), ('inspirational', 'Inspiracional'), ('trendy', 'Trendy TikTok'), ('ambient', 'Ambiental')], max_length=100)),
                ('subtitles', models.BooleanField(default=True, help_text='Generar subtítulos automáticos')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=50)),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text='Fecha programada para publicación', null=True)),
                ('generated_video_url', models.URLField(blank=True, help_text='URL del video generado', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'AI Video Creator',
                'verbose_name_plural': 'AI Video Creators',
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
