# Generated by Django 4.2.23 on 2026-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_socialautomationvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialautomationvideo',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Track ID de la tarea programada', max_length=255, null=True),
        ),
    ]
