# Generated by Django 4.2.23 on 2026-03-06 20:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('core', '0017_socialautomationvideo_celery_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiinstagramcarouselpost',
            options={'verbose_name': 'AI Instagram Carousel', 'verbose_name_plural': 'AI Instagram Carousels'},
        ),
        migrations.RenameField(
            model_name='aiinstagramcarouselpost',
            old_name='call_to_action',
            new_name='slide10_headline',
        ),
        migrations.RenameField(
            model_name='aiinstagramcarouselpost',
            old_name='caption',
            new_name='slide10_negative_prompt',
        ),
        migrations.RenameField(
            model_name='aiinstagramcarouselpost',
            old_name='hashtags',
            new_name='slide10_prompt',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='live',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='aiinstagramcarouselpost',
            name='scheduled_for',
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='layout_style',
            field=models.CharField(blank=True, choices=[('centered', 'Texto centrado'), ('split', 'Texto + imagen'), ('top_text', 'Texto arriba'), ('big_number', 'Número grande'), ('quote', 'Quote layout')], help_text='Distribución del contenido dentro del slide.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide10_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide10_subheadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide1_headline',
            field=models.CharField(blank=True, help_text='Texto principal del slide.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide1_image',
            field=models.ForeignKey(blank=True, help_text='Imagen generada por IA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide1_negative_prompt',
            field=models.TextField(blank=True, help_text='Elementos que la IA debe evitar.', null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide1_prompt',
            field=models.TextField(blank=True, help_text='Prompt visual para generar la imagen.', null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide1_subheadline',
            field=models.CharField(blank=True, help_text='Texto secundario opcional.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide2_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide2_negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide2_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide2_subheadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide3_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide3_negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide3_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide3_subheadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide4_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide4_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide4_negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide4_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide4_subheadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide5_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide5_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide5_negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide5_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide5_subheadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide6_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide6_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide6_negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide6_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide6_subheadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide7_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide7_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide7_negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide7_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide7_subheadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide8_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide8_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide8_negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide8_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide8_subheadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide9_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide9_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide9_negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide9_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slide9_subheadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='slides_to_generate',
            field=models.IntegerField(default=5, help_text='Cantidad de slides que se generarán (1-10).'),
        ),
        migrations.AddField(
            model_name='aiinstagramcarouselpost',
            name='visual_style',
            field=models.CharField(blank=True, choices=[('minimalist', 'Minimalista'), ('bold_typography', 'Tipografía fuerte'), ('illustration', 'Ilustración'), ('3d', '3D'), ('photorealistic', 'Fotorealista'), ('flat_design', 'Flat design')], help_text='Estilo visual general de las imágenes.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aiinstagramcarouselpost',
            name='ai_context',
            field=models.TextField(blank=True, help_text='\nDescribe el contexto del carrusel:\n- tema principal\n- público objetivo\n- problema que se quiere explicar\n- tipo de contenido (tips, errores, guía, etc.)\n\nLa IA usará este contexto para construir los prompts de imagen.\n', null=True),
        ),
        migrations.AlterField(
            model_name='aiinstagramcarouselpost',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Indica si las imágenes ya fueron generadas.'),
        ),
        migrations.AlterField(
            model_name='aiinstagramcarouselpost',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID de tarea para procesos async.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aiinstagramcarouselpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('educational', 'Educativo'), ('sales', 'Venta'), ('engagement', 'Engagement'), ('storytelling', 'Storytelling'), ('personal_brand', 'Marca Personal')], help_text='Tipo de contenido del carrusel.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aiinstagramcarouselpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único usado por APIs y automatizaciones.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aiinstagramcarouselpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Listo para generar'), ('generating', 'Generando imágenes'), ('completed', 'Completado'), ('failed', 'Error')], default='draft', help_text='Estado del proceso de generación.', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiinstagramcarouselpost',
            name='title',
            field=models.CharField(blank=True, help_text='Nombre interno del carrusel. No aparece en las imágenes.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aiinstagramcarouselpost',
            name='tone',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('professional', 'Profesional'), ('friendly', 'Amigable'), ('authoritative', 'Autoridad'), ('inspirational', 'Inspirador')], help_text='Tono del contenido generado por IA.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AIInstagramCarouselPosted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('post_type', models.CharField(blank=True, choices=[('educational', 'Educativo'), ('sales', 'Venta'), ('engagement', 'Engagement'), ('storytelling', 'Storytelling'), ('personal_brand', 'Marca Personal')], max_length=50, null=True)),
                ('tone', models.CharField(blank=True, choices=[('casual', 'Casual'), ('professional', 'Profesional'), ('friendly', 'Amigable'), ('authoritative', 'Autoridad'), ('inspirational', 'Inspirador')], max_length=50, null=True)),
                ('objective', models.CharField(blank=True, choices=[('increase_sales', 'Aumentar ventas'), ('generate_leads', 'Generar leads'), ('increase_engagement', 'Aumentar engagement'), ('educate', 'Educar audiencia'), ('brand_awareness', 'Reconocimiento de marca')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Borrador'), ('ready', 'Listo para publicar'), ('scheduled', 'Programado'), ('published', 'Publicado')], max_length=20, null=True)),
                ('ai_context', models.TextField(blank=True, help_text='Describe aquí todo el contexto para generar captions, copy y hashtags del carrusel', null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('call_to_action', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
            ],
            options={
                'verbose_name': 'AI Instagram Carousel Post',
                'verbose_name_plural': 'AI Instagram Carousel Posts',
            },
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='post',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='core.aiinstagramcarouselposted'),
        ),
    ]
