# Generated by Django 4.2.23 on 2026-04-25 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_media_A', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcarouselpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookcarouselpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='facebookcarouselpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookimagepost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookimagepost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='facebookimagepost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookvideopost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookvideopost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='facebookvideopost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramcarouselpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramcarouselpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='instagramcarouselpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramreel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramreel',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='instagramreel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookcarouselpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebookcarouselpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookimagepost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebookimagepost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookvideopost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebookvideopost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramcarouselpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instagramcarouselpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkedinpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkedinpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
