# Generated by Django 4.2.23 on 2026-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_A', '0002_facebookcarouselpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookcarouselpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='facebookimagepost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='facebookvideopost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='instagramcarouselpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='instagramreel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='linkedinpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='twitterpost',
            options={'ordering': ['-created_at']},
        ),
    ]
