# Generated by Django 4.2.23 on 2025-08-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('SBA', 'SmartBusinessAnalytics'), ('SBM', 'SmartBusinessMedia'), ('SBL', 'SmartBusinessLaw'), ('SBT', 'SmartBusinessTechnologies')], max_length=3)),
                ('include_rd', models.BooleanField(default=False)),
                ('include_automation', models.BooleanField(default=False)),
                ('include_ai', models.BooleanField(default=False)),
                ('num_processes', models.PositiveIntegerField(default=1)),
                ('data_volume', models.PositiveIntegerField(default=0, help_text='En MB')),
                ('complexity', models.IntegerField(default=1, help_text='1-5')),
                ('result_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Calculation',
                'verbose_name_plural': 'Product Calculations',
                'ordering': ['-created_at'],
            },
        ),
    ]
