# Generated by Django 4.2.23 on 2025-08-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQOrders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infra_type', models.CharField(choices=[('onprem', 'Nube Privada / On-Premises'), ('public', 'Nube Pública'), ('hybrid', 'Arquitectura Híbrida')], max_length=10)),
                ('cpu_cores', models.PositiveIntegerField()),
                ('ram_gb', models.PositiveIntegerField()),
                ('storage_gb', models.PositiveIntegerField()),
                ('bandwidth_mbps', models.PositiveIntegerField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
