# Generated by Django 4.2.29 on 2026-06-24 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartbusinesslaw_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratolaboral',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ContratoLaboral', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='iess_afiliaciones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IESS_Afiliaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='iess_aportes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IESS_Aportes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='iess_historialaportes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IESS_HistorialAportes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='mt_contratos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MT_Contratos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='mt_nominas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MT_Nominas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='mt_planillas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MT_Planillas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SCVS_ActasAsamblea', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='scvs_estatutos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SCVS_Estatutos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SCVSFinancialReport', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SPDP_ActaDelegado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='spdp_arco',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SPDP_ARCO', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='spdp_consentimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SPDP_Consentimiento', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='spdp_dpia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SPDP_DPIA', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='spdp_incidente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SPDP_Incidente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='spdp_politicainterna',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SPDP_PoliticaInterna', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='spdp_rat',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SPDP_RAT', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SRI_AnexosTributarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SRI_DeclaracionImpuestos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='sri_retenciones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SRI_Retenciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='sri_ruc',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SRI_RUC', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
    ]
