# Generated by Django 4.2.29 on 2026-06-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw_demo', '0002_contratolaboral_usuario_iess_afiliaciones_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='cantidad_empleados',
            field=models.IntegerField(default=0),
        ),
    ]
