# Generated by Django 4.2.23 on 2026-02-11 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de contrato')),
                ('contract_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Hash único del contrato')),
                ('tipo_contrato', models.CharField(choices=[('CONF', 'Acuerdo de confidencialidad y no competencia'), ('LAB', 'Contrato laboral'), ('ASA', 'Acta de asamblea'), ('ALI', 'Alianza estratégica')], max_length=4, verbose_name='Tipo de contrato')),
                ('fecha_firma', models.DateField(verbose_name='Fecha de firma')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('partes_contratantes', models.TextField(verbose_name='Partes contratantes')),
                ('objeto_contrato', models.TextField(verbose_name='Objeto del contrato')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('RESCINDIDO', 'Rescindido')], default='VIGENTE', max_length=20, verbose_name='Estado del contrato')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClausulaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_clausura', models.CharField(blank='True', max_length=260, null='True', verbose_name='titulo de clausura')),
                ('clausula', models.CharField(blank='True', choices=[('CLAUSULA_1', 'CLÁUSULA PRIMERA'), ('CLAUSULA_2', 'CLÁUSULA SEGUNDA'), ('CLAUSULA_3', 'CLÁUSULA TERCERA'), ('CLAUSULA_4', 'CLÁUSULA CUARTA'), ('CLAUSULA_5', 'CLÁUSULA QUINTA'), ('CLAUSULA_6', 'CLÁUSULA SEXTA'), ('CLAUSULA_7', 'CLÁUSULA SÉPTIMA'), ('CLAUSULA_8', 'CLÁUSULA OCTAVA'), ('CLAUSULA_9', 'CLÁUSULA NOVENA'), ('CLAUSULA_10', 'CLÁUSULA DÉCIMA'), ('CLAUSULA_11', 'CLÁUSULA UNDÉCIMA'), ('CLAUSULA_12', 'CLÁUSULA DUODÉCIMA'), ('CLAUSULA_13', 'CLÁUSULA DECIMOTERCERA'), ('CLAUSULA_14', 'CLÁUSULA DECIMOCUARTA'), ('CLAUSULA_15', 'CLÁUSULA DECIMOQUINTA'), ('CLAUSULA_16', 'CLÁUSULA DECIMOSEXTA'), ('CLAUSULA_17', 'CLÁUSULA DECIMOSÉPTIMA'), ('CLAUSULA_18', 'CLÁUSULA DECIMOCTAVA'), ('CLAUSULA_19', 'CLÁUSULA DECIMONOVENA'), ('CLAUSULA_20', 'CLÁUSULA VIGÉSIMA'), ('CLAUSULA_21', 'CLÁUSULA VIGESIMOPRIMERA'), ('CLAUSULA_22', 'CLÁUSULA VIGESIMOSEGUNDA'), ('CLAUSULA_23', 'CLÁUSULA VIGESIMOTERCERA'), ('CLAUSULA_24', 'CLÁUSULA VIGESIMOCUARTA'), ('CLAUSULA_25', 'CLÁUSULA VIGESIMOQUINTA'), ('CLAUSULA_26', 'CLÁUSULA VIGESIMOSEXTA'), ('CLAUSULA_27', 'CLÁUSULA VIGESIMOSÉPTIMA'), ('CLAUSULA_28', 'CLÁUSULA VIGESIMOCTAVA'), ('CLAUSULA_29', 'CLÁUSULA VIGESIMONOVENA'), ('CLAUSULA_30', 'CLÁUSULA TRIGÉSIMA')], max_length=16, null='True', verbose_name='CLÁUSULA')),
                ('detalle', models.TextField(verbose_name='Detalle de la cláusula')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clausulas', to='smartcontracts.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Cláusula de contrato',
                'verbose_name_plural': 'Cláusulas de contrato',
            },
        ),
    ]
