# Generated by Django 4.2.27 on 2026-01-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de contrato')),
                ('tipo_contrato', models.CharField(choices=[('CONF', 'Acuerdo de confidencialidad y no competencia'), ('LAB', 'Contrato laboral'), ('ASA', 'Acta de asamblea'), ('ALI', 'Alianza estratégica')], max_length=4, verbose_name='Tipo de contrato')),
                ('fecha_firma', models.DateField(verbose_name='Fecha de firma')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('partes_contratantes', models.TextField(verbose_name='Partes contratantes')),
                ('objeto_contrato', models.TextField(verbose_name='Objeto del contrato')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('RESCINDIDO', 'Rescindido')], default='VIGENTE', max_length=20, verbose_name='Estado del contrato')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClausulaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_clausula', models.PositiveIntegerField(verbose_name='Número de cláusula')),
                ('detalle', models.TextField(verbose_name='Detalle de la cláusula')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clausulas', to='smartcontracts.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Cláusula de contrato',
                'verbose_name_plural': 'Cláusulas de contrato',
                'ordering': ['numero_clausula'],
                'unique_together': {('contrato', 'numero_clausula')},
            },
        ),
    ]
