# Generated by Django 4.2.27 on 2026-02-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('CONF', 'Acuerdo de confidencialidad y no competencia'), ('LAB', 'Contrato laboral'), ('ASA', 'Acta de asamblea'), ('ALI', 'Alianza estratégica'), ('DES', 'DECISIÓN DEL ACCIONISTA ÚNICO')], max_length=4, verbose_name='Tipo de contrato'),
        ),
    ]
