# Generated by Django 4.2.27 on 2026-01-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='contract_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Hash único del contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
