# Generated by Django 4.2.27 on 2026-01-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontracts', '0002_contrato_contract_hash_alter_contrato_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clausulacontrato',
            options={'ordering': ['clausula'], 'verbose_name': 'Cláusula de contrato', 'verbose_name_plural': 'Cláusulas de contrato'},
        ),
        migrations.AlterUniqueTogether(
            name='clausulacontrato',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clausulacontrato',
            name='clausula',
            field=models.CharField(blank='True', choices=[('CLAUSULA_1', 'CLÁUSULA PRIMERA'), ('CLAUSULA_2', 'CLÁUSULA SEGUNDA'), ('CLAUSULA_3', 'CLÁUSULA TERCERA'), ('CLAUSULA_4', 'CLÁUSULA CUARTA'), ('CLAUSULA_5', 'CLÁUSULA QUINTA'), ('CLAUSULA_6', 'CLÁUSULA SEXTA'), ('CLAUSULA_7', 'CLÁUSULA SÉPTIMA'), ('CLAUSULA_8', 'CLÁUSULA OCTAVA'), ('CLAUSULA_9', 'CLÁUSULA NOVENA'), ('CLAUSULA_10', 'CLÁUSULA DÉCIMA'), ('CLAUSULA_11', 'CLÁUSULA UNDÉCIMA'), ('CLAUSULA_12', 'CLÁUSULA DUODÉCIMA'), ('CLAUSULA_13', 'CLÁUSULA DECIMOTERCERA'), ('CLAUSULA_14', 'CLÁUSULA DECIMOCUARTA'), ('CLAUSULA_15', 'CLÁUSULA DECIMOQUINTA'), ('CLAUSULA_16', 'CLÁUSULA DECIMOSEXTA'), ('CLAUSULA_17', 'CLÁUSULA DECIMOSÉPTIMA'), ('CLAUSULA_18', 'CLÁUSULA DECIMOCTAVA'), ('CLAUSULA_19', 'CLÁUSULA DECIMONOVENA'), ('CLAUSULA_20', 'CLÁUSULA VIGÉSIMA'), ('CLAUSULA_21', 'CLÁUSULA VIGESIMOPRIMERA'), ('CLAUSULA_22', 'CLÁUSULA VIGESIMOSEGUNDA'), ('CLAUSULA_23', 'CLÁUSULA VIGESIMOTERCERA'), ('CLAUSULA_24', 'CLÁUSULA VIGESIMOCUARTA'), ('CLAUSULA_25', 'CLÁUSULA VIGESIMOQUINTA'), ('CLAUSULA_26', 'CLÁUSULA VIGESIMOSEXTA'), ('CLAUSULA_27', 'CLÁUSULA VIGESIMOSÉPTIMA'), ('CLAUSULA_28', 'CLÁUSULA VIGESIMOCTAVA'), ('CLAUSULA_29', 'CLÁUSULA VIGESIMONOVENA'), ('CLAUSULA_30', 'CLÁUSULA TRIGÉSIMA')], max_length=16, null='True', verbose_name='CLÁUSULA'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contract_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Hash único del contrato'),
        ),
        migrations.AlterUniqueTogether(
            name='clausulacontrato',
            unique_together={('contrato', 'clausula')},
        ),
        migrations.RemoveField(
            model_name='clausulacontrato',
            name='numero_clausula',
        ),
    ]
