# Generated by Django 4.2.27 on 2026-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontracts', '0002_alter_contrato_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('CONF', 'Acuerdo de confidencialidad y no competencia'), ('LAB', 'Contrato laboral'), ('ASA', 'Acta de asamblea'), ('ALI', 'Alianza estratégica'), ('DES', 'DECISIÓN DEL ACCIONISTA ÚNICO'), ('ACE', 'ACEPTACIÓN DE LOS CARGOS DE PRESIDENTE Y GERENTE GENERAL'), ('NON', 'NOMBRAMIENTO DE GERENTE GENERAL Y PRESIDENTE')], max_length=4, verbose_name='Tipo de contrato'),
        ),
    ]
