# Generated by Django 4.2.27 on 2026-01-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontracts', '0003_alter_clausulacontrato_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clausulacontrato',
            name='titulo_clausura',
            field=models.CharField(blank='True', max_length=16, null='True', verbose_name='titulo de clausura'),
            preserve_default='True',
        ),
    ]
