# Generated by Django 4.2.27 on 2026-01-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontracts', '0004_clausulacontrato_titulo_clausura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clausulacontrato',
            name='titulo_clausura',
            field=models.CharField(blank='True', max_length=260, null='True', verbose_name='titulo de clausura'),
        ),
    ]
