# Generated by Django 4.2.27 on 2026-01-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontracts', '0005_alter_clausulacontrato_titulo_clausura'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clausulacontrato',
            unique_together=set(),
        ),
    ]
