# Generated by Django 4.2.23 on 2026-01-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontracts', '0006_alter_clausulacontrato_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clausulacontrato',
            options={'verbose_name': 'Cláusula de contrato', 'verbose_name_plural': 'Cláusulas de contrato'},
        ),
    ]
