# Generated by Django 4.2.23 on 2026-04-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontracts', '0006_alter_contrato_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('CONF', 'Acuerdo de confidencialidad y no competencia'), ('LAB', 'Contrato laboral'), ('ASA', 'Acta de asamblea'), ('IFA', 'Informe Anual Financiero y Contable'), ('ALI', 'Alianza estratégica'), ('DES', 'DECISIÓN DEL ACCIONISTA ÚNICO'), ('ACE', 'ACEPTACIÓN DE LOS CARGOS DE PRESIDENTE Y GERENTE GENERAL'), ('NON', 'NOMBRAMIENTO DE GERENTE GENERAL Y PRESIDENTE'), ('DE-MIT', 'DECLARACIÓN FORMAL ANTE EL MINISTERIO DE TRABAJO'), ('DES-MIT', 'DESCARGO FORMAL PRESENTADO ANTE EL MINISTERIO DEL TRABAJO')], max_length=200, verbose_name='Tipo de contrato'),
        ),
    ]
