# Generated by Django 4.2.23 on 2026-04-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontracts', '0007_alter_contrato_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Cargo a quien va dirigido'),
        ),
    ]
