# Generated by Django 4.2.23 on 2026-01-29 22:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_registro', models.CharField(help_text='Nombre del registro o cumplimiento interno', max_length=255)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('vigente', models.BooleanField(default=True)),
                ('nombre_SCVS', models.CharField(blank=True, choices=[('ESTATUTOS', 'Estatutos de la compañía'), ('ACTAS_ASAMBLEA', 'Actas de Asamblea'), ('INFORME_FINANCIERO', 'Informe Financiero anual'), ('REGISTRO_DIRECTORES', 'Registro de Directores')], max_length=50, null=True)),
                ('nombre_SPDP', models.CharField(blank=True, choices=[('CONSENTIMIENTOS', 'Consentimientos de clientes/usuarios'), ('RAT', 'Registro de Tratamiento de Datos'), ('DPIA', 'Evaluación de Impacto en Protección de Datos'), ('ARCO', 'Procedimiento ARCO'), ('INCIDENTES', 'Registro de Incidentes de Seguridad'), ('POLITICAS', 'Políticas internas de protección de datos'), ('ACTA_DELEGADO', 'Acta de nombramiento del Delegado de Datos')], max_length=50, null=True)),
                ('nombre_SRI', models.CharField(blank=True, choices=[('RUC', 'Registro Único de Contribuyentes'), ('DECLARACION_IMPUESTOS', 'Declaración de Impuestos'), ('RETENCIONES', 'Comprobantes de Retención')], max_length=50, null=True)),
                ('nombre_MIN_TRABAJO', models.CharField(blank=True, choices=[('CONTRATOS', 'Contratos de trabajo'), ('NOMINAS', 'Nóminas de empleados'), ('PLANILLAS', 'Planillas de seguridad social')], max_length=50, null=True)),
                ('nombre_IESS', models.CharField(blank=True, choices=[('AFILIACIONES', 'Afiliaciones de empleados'), ('APORTES', 'Comprobantes de aportes'), ('HISTORIAL', 'Historial de aportes')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SRI_RUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13)),
                ('fecha_emision', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='sri/ruc/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sri_ruc', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'RUC SRI',
                'verbose_name_plural': 'RUC SRI',
            },
        ),
        migrations.CreateModel(
            name='SRI_Retenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='sri/retenciones/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sri_retenciones', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Retención SRI',
                'verbose_name_plural': 'Retenciones SRI',
            },
        ),
        migrations.CreateModel(
            name='SRI_DeclaracionImpuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(max_length=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_presentacion', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='sri/declaraciones/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sri_declaraciones', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Declaración Impuestos SRI',
                'verbose_name_plural': 'Declaraciones Impuestos SRI',
            },
        ),
        migrations.CreateModel(
            name='SPDP_RAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dato', models.CharField(max_length=255)),
                ('finalidad', models.TextField()),
                ('base_legal', models.CharField(max_length=255)),
                ('medidas_seguridad', models.TextField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='spdp/rat/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_rat', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'RAT SPDP',
                'verbose_name_plural': 'RAT SPDP',
            },
        ),
        migrations.CreateModel(
            name='SPDP_PoliticaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_aprobacion', models.DateField(default=django.utils.timezone.now)),
                ('vigente', models.BooleanField(default=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='spdp/politicas/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_politicas', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Política Interna SPDP',
                'verbose_name_plural': 'Políticas Internas SPDP',
            },
        ),
        migrations.CreateModel(
            name='SPDP_Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_detectado', models.DateField(default=django.utils.timezone.now)),
                ('nivel_gravedad', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=10)),
                ('notificado', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='spdp/incidentes/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_incidentes', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Incidente SPDP',
                'verbose_name_plural': 'Incidentes SPDP',
            },
        ),
        migrations.CreateModel(
            name='SPDP_DPIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('riesgo_identificado', models.TextField()),
                ('medidas_mitigacion', models.TextField()),
                ('fecha_elaboracion', models.DateField(default=django.utils.timezone.now)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='spdp/dpia/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_dpia', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'DPIA SPDP',
                'verbose_name_plural': 'DPIA SPDP',
            },
        ),
        migrations.CreateModel(
            name='SPDP_Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('finalidad', models.TextField()),
                ('fecha_firma', models.DateField()),
                ('aceptado', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='spdp/consentimientos/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_consentimientos', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Consentimiento SPDP',
                'verbose_name_plural': 'Consentimientos SPDP',
            },
        ),
        migrations.CreateModel(
            name='SPDP_ARCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('tipo_solicitud', models.CharField(choices=[('ACCESO', 'Acceso'), ('RECTIFICACION', 'Rectificación'), ('CANCELACION', 'Cancelación'), ('OPOSICION', 'Oposición')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('respondido', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='spdp/arco/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_arco', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Solicitud ARCO SPDP',
                'verbose_name_plural': 'Solicitudes ARCO SPDP',
            },
        ),
        migrations.CreateModel(
            name='SPDP_ActaDelegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_delegado', models.CharField(max_length=255)),
                ('fecha_nombramiento', models.DateField()),
                ('funciones', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='spdp/delegado/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_delegado', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Acta Delegado SPDP',
                'verbose_name_plural': 'Actas Delegado SPDP',
            },
        ),
        migrations.CreateModel(
            name='SCVS_InformeFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(max_length=20)),
                ('fecha_presentacion', models.DateField()),
                ('aprobado_por_junta', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='scvs/informes/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scvs_informes', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Informe Financiero SCVS',
                'verbose_name_plural': 'Informes Financieros SCVS',
            },
        ),
        migrations.CreateModel(
            name='SCVS_Estatutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('fecha_aprobacion', models.DateField()),
                ('notario', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='scvs/estatutos/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scvs_estatutos', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Estatuto SCVS',
                'verbose_name_plural': 'Estatutos SCVS',
            },
        ),
        migrations.CreateModel(
            name='SCVS_ActasAsamblea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asamblea', models.DateField()),
                ('tema_tratado', models.TextField()),
                ('asistentes', models.TextField()),
                ('resultado', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='scvs/actas/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scvs_actas', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Acta de Asamblea SCVS',
                'verbose_name_plural': 'Actas de Asamblea SCVS',
            },
        ),
        migrations.CreateModel(
            name='MT_Planillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_planilla', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_presentacion', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mt/planillas/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt_planillas', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Planilla MT',
                'verbose_name_plural': 'Planillas MT',
            },
        ),
        migrations.CreateModel(
            name='MT_Nominas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mt/nominas/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt_nominas', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Nómina MT',
                'verbose_name_plural': 'Nóminas MT',
            },
        ),
        migrations.CreateModel(
            name='MT_Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mt/contratos/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt_contratos', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Contrato MT',
                'verbose_name_plural': 'Contratos MT',
            },
        ),
        migrations.CreateModel(
            name='IESS_HistorialAportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='iess/historial/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iess_historial', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Historial de Aportes IESS',
                'verbose_name_plural': 'Historiales de Aportes IESS',
            },
        ),
        migrations.CreateModel(
            name='IESS_Aportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='iess/aportes/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iess_aportes', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Aporte IESS',
                'verbose_name_plural': 'Aportes IESS',
            },
        ),
        migrations.CreateModel(
            name='IESS_Afiliaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=255)),
                ('fecha_afiliacion', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='iess/afiliaciones/')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iess_afiliaciones', to='smartbusinesslaw.regulacion')),
            ],
            options={
                'verbose_name': 'Afiliación IESS',
                'verbose_name_plural': 'Afiliaciones IESS',
            },
        ),
    ]
