# Generated by Django 4.2.23 on 2026-02-11 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smartbusinesslaw', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_titular_datos',
            field=models.ForeignKey(blank=True, help_text='Usuario titular de los datos personales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rat_tratamientos', to=settings.AUTH_USER_MODEL, verbose_name='Titulares (DPD)'),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_delegado', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AlterUniqueTogether(
            name='scvsfinancialreport',
            unique_together={('ruc', 'fiscal_year')},
        ),
        migrations.AddField(
            model_name='scvs_estatutos',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scvs_estatutos', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='regulacion',
            field=models.ForeignKey(help_text='Regulación o proceso legal al que pertenece este conjunto documental SCVS.', on_delete=django.db.models.deletion.CASCADE, related_name='scvs_actas', to='smartbusinesslaw.regulacion', verbose_name='Regulación asociada'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='contrato',
            field=models.ForeignKey(blank=True, help_text='Contrato del trabajador asociado a esta nómina.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='smartbusinesslaw.contratolaboral', unique=True, verbose_name='Contrato SUT'),
        ),
        migrations.AddField(
            model_name='mt_planillas',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt_planillas', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='mt_nominas',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt_nominas', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='mt_contratos',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt_contratos', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='iess_historialaportes',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iess_historial', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='iess_aportes',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iess_aportes', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='iess_afiliaciones',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iess_afiliaciones', to='smartbusinesslaw.regulacion'),
        ),
    ]
