# Generated by Django 5.2.13 on 2026-04-26 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smartbusinesslaw', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='rat_titular_datos',
            field=models.ForeignKey(blank=True, help_text='Usuario titular de los datos personales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rat_tratamientos', to=settings.AUTH_USER_MODEL, verbose_name='Titulares (DPD)'),
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_delegado', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='spdp_arco',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_arco', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='spdp_consentimiento',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_consentimientos', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='spdp_dpia',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_dpia', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='spdp_incidente',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_incidentes', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='spdp_politicainterna',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_politicas', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='spdp_rat',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdp_rat', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddIndex(
            model_name='sri_anexostributarios',
            index=models.Index(fields=['ruc', 'ejercicio_fiscal', 'mes'], name='smartbusine_ruc_e893ff_idx'),
        ),
        migrations.AddField(
            model_name='sri_retenciones',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sri_retenciones', to='smartbusinesslaw.regulacion'),
        ),
        migrations.AddField(
            model_name='sri_ruc',
            name='regulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sri_ruc', to='smartbusinesslaw.regulacion'),
        ),
    ]
