# Generated by Django 4.2.27 on 2026-02-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sri_declaracionimpuestos',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Declaracion: Servicio de Rentas Internas (SRI)', 'verbose_name_plural': 'Declaraciones: Servicio de Rentas Internas (SRI)'},
        ),
    ]
