# Generated by Django 4.2.27 on 2026-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0003_alter_sri_declaracionimpuestos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='base_imponible',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base imponible determinada para el cálculo del Impuesto a la Renta.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_autorizacion',
            field=models.CharField(blank=True, help_text='Número de autorización electrónica del comprobante.', max_length=49, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_base_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base imponible gravada con tarifa diferente de 0%.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_base_iva_0',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base imponible gravada con tarifa 0% de IVA.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_base_no_objeto_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base imponible no objeto de IVA.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_establecimiento',
            field=models.CharField(blank=True, help_text='Código de establecimiento del comprobante (3 dígitos).', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_fecha_emision',
            field=models.DateField(blank=True, help_text='Fecha de emisión del comprobante de compra.', null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_id_proveedor',
            field=models.CharField(blank=True, help_text='Número de identificación del proveedor sin guiones.', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor del IVA pagado en la compra.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_punto_emision',
            field=models.CharField(blank=True, help_text='Código de punto de emisión del comprobante (3 dígitos).', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_razon_social_proveedor',
            field=models.CharField(blank=True, help_text='Razón social o nombres completos del proveedor.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_secuencial',
            field=models.CharField(blank=True, help_text='Número secuencial del comprobante (9 dígitos).', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_tipo_comprobante',
            field=models.CharField(blank=True, help_text='Código del tipo de comprobante según catálogo del SRI (ej: 01=Factura, 04=Nota de Crédito).', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_tipo_id_proveedor',
            field=models.CharField(blank=True, help_text='Tipo de identificación del proveedor (04=RUC, 05=Cédula, 06=Pasaporte, etc.).', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total del comprobante de compra (incluye impuestos).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='contador',
            field=models.CharField(help_text='Nombre completo del contador responsable.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='distribuyo_dividendos',
            field=models.BooleanField(default=False, help_text='Indica si la sociedad distribuyó dividendos a sus socios.'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='dividendo_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto total de dividendos pagados al socio.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ejercicio_fiscal',
            field=models.PositiveIntegerField(help_text='Año fiscal al que corresponde la información reportada (formato YYYY).', verbose_name='Ejercicio fiscal'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_aporte_iess',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total aportado al IESS por el empleado.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_cargo',
            field=models.CharField(blank=True, help_text='Cargo o puesto desempeñado por el empleado.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_identificacion',
            field=models.CharField(blank=True, help_text='Número de identificación del empleado.', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_ir_retenido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Impuesto a la Renta retenido al empleado durante el ejercicio fiscal.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_nombres',
            field=models.CharField(blank=True, help_text='Nombres completos del empleado.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_sueldo_anual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de ingresos gravados percibidos por el empleado en el año.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_tipo_id',
            field=models.CharField(blank=True, help_text='Tipo de identificación del empleado.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='fecha_certificacion',
            field=models.DateField(help_text='Fecha en la que se certifica la información reportada.'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='gastos_no_deducibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de gastos contables no deducibles fiscalmente.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='impuesto_dividendo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Impuesto retenido sobre los dividendos distribuidos.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='impuesto_renta_causado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del Impuesto a la Renta causado según la base imponible.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ingresos_exentos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingresos que están exentos del Impuesto a la Renta.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='mes',
            field=models.PositiveIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], help_text='Mes al que corresponde el anexo (01=Enero, 12=Diciembre).', verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='monto_operacion_parte_relacionada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto total de operaciones realizadas con la parte relacionada.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='obligado_contabilidad',
            field=models.BooleanField(default=True, help_text='Indica si el contribuyente está obligado a llevar contabilidad conforme normativa vigente.', verbose_name='Obligado a llevar contabilidad'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='parte_relacionada_identificacion',
            field=models.CharField(blank=True, help_text='Número de identificación de la parte relacionada.', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='parte_relacionada_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la parte relacionada.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='razon_social',
            field=models.CharField(help_text='Nombre legal completo registrado ante el SRI.', max_length=255, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='representante_legal',
            field=models.CharField(help_text='Nombre completo del representante legal de la sociedad.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_ir_codigo',
            field=models.CharField(blank=True, help_text='Código de retención en la fuente de Impuesto a la Renta según tabla del SRI.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_ir_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje aplicado de retención en la fuente de Impuesto a la Renta.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_ir_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor retenido por concepto de Impuesto a la Renta.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_iva_codigo',
            field=models.CharField(blank=True, help_text='Código de retención de IVA según catálogo del SRI.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_iva_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de retención de IVA aplicado.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_iva_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor retenido por concepto de IVA.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ruc',
            field=models.CharField(help_text='Registro Único de Contribuyentes de la sociedad, debe contener 13 dígitos sin guiones.', max_length=13, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_identificacion',
            field=models.CharField(blank=True, help_text='Número de identificación del socio/accionista.', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_nombre',
            field=models.CharField(blank=True, help_text='Nombre completo del socio/accionista.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_porcentaje_participacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de participación del socio/accionista.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_tipo_id',
            field=models.CharField(blank=True, help_text='Tipo de identificación del socio/accionista.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='tiene_empleados',
            field=models.BooleanField(default=False, help_text='Indica si la empresa tuvo empleados en relación de dependencia durante el ejercicio fiscal.'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='tiene_partes_relacionadas',
            field=models.BooleanField(default=False, help_text='Indica si la sociedad realizó operaciones con partes relacionadas.'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='tipo_operacion',
            field=models.CharField(blank=True, help_text='Tipo de operación realizada con la parte relacionada.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='utilidad_contable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resultado contable antes de ajustes fiscales.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_base_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base imponible de ventas gravadas con tarifa diferente de 0%.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_base_iva_0',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base imponible de ventas gravadas con tarifa 0% de IVA.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_id_cliente',
            field=models.CharField(blank=True, help_text='Número de identificación del cliente.', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total de IVA generado en las ventas.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_razon_social_cliente',
            field=models.CharField(blank=True, help_text='Razón social o nombres completos del cliente.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_tipo_id_cliente',
            field=models.CharField(blank=True, help_text='Tipo de identificación del cliente (04=RUC, 05=Cédula, etc.).', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total facturado al cliente, incluyendo impuestos.', max_digits=18),
        ),
    ]
