# Generated by Django 4.2.23 on 2026-02-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0004_alter_sri_anexostributarios_base_imponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='beneficiarios_finales',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='socios',
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='anticipada',
            field=models.CharField(blank=True, help_text='Año de declaración anticipada en formato YYYY.', max_length=4, null=True, verbose_name='Anticipada'),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_identificacion',
            field=models.CharField(blank=True, help_text='Número de identificación del beneficiario final.', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_nombre_completo',
            field=models.CharField(blank=True, help_text='Nombre completo del beneficiario final.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_porcentaje_participacion',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Porcentaje de participación del beneficiario final (hasta 6 decimales).', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_tipo_identificacion',
            field=models.CharField(blank=True, help_text='Tipo de identificación del beneficiario final.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='codigo_operativo',
            field=models.CharField(blank=True, help_text='Código operativo de 3 caracteres según instructivo REBEFICS.', max_length=3, null=True, verbose_name='Código Operativo'),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='porcentaje_accionario_bolsa',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Porcentaje accionario que negocia en bolsa (hasta 3 enteros y 6 decimales).', max_digits=9, null=True, verbose_name='Porcentaje Accionario Bolsa'),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='porcentaje_accionario_no_bolsa',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Porcentaje accionario que NO negocia en bolsa (hasta 3 enteros y 6 decimales).', max_digits=9, null=True, verbose_name='Porcentaje Accionario No Bolsa'),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='socio_identificacion_rebefics',
            field=models.CharField(blank=True, help_text='Número de identificación del socio/accionista.', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='socio_nombre_rebefics',
            field=models.CharField(blank=True, help_text='Nombre completo del socio/accionista.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='socio_porcentaje_rebefics',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Porcentaje de participación del socio/accionista (hasta 6 decimales).', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='socio_tipo_identificacion',
            field=models.CharField(blank=True, help_text='Tipo de identificación del socio/accionista.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='tipo_declaracion',
            field=models.CharField(blank=True, help_text='Código según Tabla 8 del SRI (2 caracteres).', max_length=2, null=True, verbose_name='Tipo de Declaración'),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='tipo_sociedad',
            field=models.CharField(blank=True, help_text='Código de tipo de sociedad según Tabla 1 del SRI (2 caracteres).', max_length=2, null=True, verbose_name='Tipo de Sociedad'),
        ),
    ]
