# Generated by Django 4.2.23 on 2026-02-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0005_remove_sri_anexostributarios_beneficiarios_finales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='ventas_compensacion_ley_solidaridad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de compensaciones de ventas por Ley de Solidaridad aplicado al establecimiento.', max_digits=18),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='ventas_forma_cobro',
            field=models.CharField(blank=True, help_text='Forma de cobro utilizada en la venta (Efectivo, Tarjeta, Transferencia, Cheque, Otros). Obligatorio desde junio-2016.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='ventas_porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=12, help_text='Porcentaje de IVA aplicado sobre la base imponible gravada (ej: 12%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total de IVA generado en las ventas. Debe ser igual a ventas_base_iva * porcentaje_iva.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total facturado al cliente, incluyendo impuestos. Debe ser ventas_base_iva_0 + ventas_base_iva + ventas_monto_iva.', max_digits=18),
        ),
    ]
