# Generated by Django 4.2.23 on 2026-04-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0005_alter_scvs_esf_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scvs_ecp',
            options={'verbose_name': 'Estado de Cambio de Patrimonio (ECP)', 'verbose_name_plural': 'Estados de Cambio de Patrimonio (ESF)'},
        ),
        migrations.AlterModelOptions(
            name='scvs_efe',
            options={'verbose_name': 'Estado Flujo Efectivo (EFE)', 'verbose_name_plural': 'Estados Flujo Efectivo (EFE)'},
        ),
        migrations.AlterModelOptions(
            name='scvs_eir',
            options={'verbose_name': 'Estado Integral de Resultados(EIR)', 'verbose_name_plural': 'Estados Integral de Resultados(EIR)'},
        ),
        migrations.AlterField(
            model_name='scvs_esf',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartbusinesslaw.scvsfinancialreport'),
        ),
    ]
