# Generated by Django 4.2.23 on 2026-02-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0006_sri_anexostributarios_ventas_compensacion_ley_solidaridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_forma_cobro',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTROS', 'Otros')], help_text='Forma de cobro utilizada en la venta. Obligatorio desde junio-2016.', max_length=20, null=True),
        ),
    ]
