# Generated by Django 4.2.23 on 2026-01-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0006_alter_spdp_actadelegado_rat_categoria_datos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spdp_actadelegado',
            name='rat_base_legal',
            field=models.CharField(choices=[('art7_consentimiento', 'Art. 7 LOPDP – Consentimiento del titular'), ('art7_obligacion_legal', 'Art. 7 LOPDP – Cumplimiento de obligación legal'), ('art7_contrato', 'Art. 7 LOPDP – Ejecución de un contrato'), ('art7_precontractual', 'Art. 7 LOPDP – Medidas precontractuales'), ('art7_interes_publico', 'Art. 7 LOPDP – Interés público o ejercicio de potestades públicas'), ('art7_interes_legitimo', 'Art. 7 LOPDP – Interés legítimo del responsable o tercero'), ('art7_intereses_vitales', 'Art. 7 LOPDP – Protección de intereses vitales'), ('art12_nna', 'Art. 12 LOPDP – Datos de niños, niñas y adolescentes')], help_text='Base(s) legal(es) del tratamiento conforme a la LOPDP. ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spdp_actadelegado',
            name='rat_categoria_datos',
            field=models.CharField(blank=True, choices=[('personales', 'Datos personales'), ('sensibles', 'Datos sensibles'), ('financieros', 'Datos financieros'), ('salud', 'Datos de salud'), ('laborales', 'Datos laborales')], help_text='Categorías de datos personales tratados. Seleccione uno o varios.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spdp_actadelegado',
            name='rat_categoria_destinatarios',
            field=models.CharField(blank=True, choices=[('internos', 'Departamentos internos'), ('externos', 'Proveedores de servicios'), ('entidades_gubernamentales', 'Entidades gubernamentales'), ('terceros_autorizados', 'Terceros autorizados')], help_text='Destinatarios o terceros receptores de datos. Seleccione uno o varios.', max_length=255, null=True),
        ),
    ]
