# Generated by Django 4.2.23 on 2026-04-11 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0006_alter_scvs_ecp_options_alter_scvs_efe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scvs_ecp',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartbusinesslaw.scvsfinancialreport'),
        ),
        migrations.AlterField(
            model_name='scvs_efe',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartbusinesslaw.scvsfinancialreport'),
        ),
        migrations.AlterField(
            model_name='scvs_eir',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartbusinesslaw.scvsfinancialreport'),
        ),
    ]
