# Generated by Django 4.2.23 on 2026-04-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0007_alter_scvs_ecp_report_alter_scvs_efe_report_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scvs_ecp',
            options={'verbose_name': 'Estado de Cambio de Patrimonio (ECP)', 'verbose_name_plural': 'Estados de Cambio de Patrimonio (ECP)'},
        ),
        migrations.AlterModelOptions(
            name='scvsfinancialreport',
            options={'verbose_name': 'Balance Financiero (SCVS)', 'verbose_name_plural': 'Balances Financieros (SCVS)'},
        ),
        migrations.AlterField(
            model_name='scvs_esf',
            name='c_10102020223',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='OTRAS INVERSIONES EN EL EXTERIOR', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='fiscal_year',
            field=models.PositiveIntegerField(help_text='Año al que corresponde el reporte financiero. Ejemplo: 2025', verbose_name='Año fiscal'),
        ),
    ]
