# Generated by Django 4.2.23 on 2026-02-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0007_alter_sri_anexostributarios_ventas_forma_cobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_forma_cobro',
            field=models.CharField(blank=True, choices=[('01', 'Efectivo'), ('02', 'Cheque'), ('03', 'Transferencia'), ('04', 'Tarjeta'), ('05', 'Otros')], help_text='Forma de cobro utilizada en la venta. Obligatorio desde junio-2016. Debe usar los códigos ATS: 01=Efectivo, 02=Cheque, 03=Transferencia, 04=Tarjeta, 05=Otros.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor total facturado al cliente, incluyendo impuestos. Debe ser ventas_base_iva_0 + ventas_base_iva + ventas_monto_iva.', max_digits=18, null=True),
        ),
    ]
