# Generated by Django 4.2.23 on 2026-02-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0008_alter_sri_anexostributarios_ventas_forma_cobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_es_beneficiario_final',
            field=models.CharField(blank=True, help_text='Indica si es beneficiario final (SI/NO).', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_identificacion_informante_padre',
            field=models.CharField(blank=True, help_text='Número de identificación del contribuyente que reporta al SRI.', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_tipo_sujeto',
            field=models.CharField(blank=True, help_text='Tipo de sujeto del beneficiario final (PN=Persona Natural, PJ=Persona Jurídica).', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='socio_tipo_sujeto',
            field=models.CharField(blank=True, help_text='Tipo de sujeto del socio/accionista (PN=Persona Natural, PJ=Persona Jurídica).', max_length=2, null=True),
        ),
    ]
