# Generated by Django 4.2.23 on 2026-04-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0009_alter_scvs_ecp_report_alter_scvs_efe_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inscripción'),
        ),
    ]
