# Generated by Django 4.2.23 on 2026-01-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0009_spdp_actadelegado_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spdp_actadelegado',
            name='fecha_expiracion',
        ),
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='legalizado_spd',
            field=models.BooleanField(default=False, verbose_name='Legalizado (SPDP)'),
        ),
        migrations.AlterField(
            model_name='spdp_actadelegado',
            name='nombre_delegado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delegado (DPD)'),
        ),
    ]
