# Generated by Django 4.2.23 on 2026-02-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0009_sri_anexostributarios_bf_es_beneficiario_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_calle',
            field=models.CharField(blank=True, help_text='Calle del beneficiario final.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_canton',
            field=models.CharField(blank=True, help_text='Cantón del beneficiario final.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal del beneficiario final.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_numero',
            field=models.CharField(blank=True, help_text='Número de la dirección del beneficiario final.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_parroquia',
            field=models.CharField(blank=True, help_text='Parroquia del beneficiario final.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_primer_apellido',
            field=models.CharField(blank=True, help_text='Primer apellido del beneficiario final.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_primer_nombre',
            field=models.CharField(blank=True, help_text='Primer nombre del beneficiario final.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_provincia',
            field=models.CharField(blank=True, help_text='Provincia del beneficiario final.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_residencia_fiscal',
            field=models.CharField(blank=True, help_text='País de residencia fiscal del beneficiario final.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_segundo_apellido',
            field=models.CharField(blank=True, help_text='Segundo apellido del beneficiario final.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_segundo_nombre',
            field=models.CharField(blank=True, help_text='Segundo nombre del beneficiario final.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='distribuyo_dividendos',
            field=models.CharField(blank=True, help_text='Indica si distribuyó dividendos (SI/NO).', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='dividendo_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de dividendos pagados al beneficiario.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='impuesto_dividendo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Impuesto retenido sobre los dividendos.', max_digits=15, null=True),
        ),
    ]
