# Generated by Django 4.2.23 on 2026-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0010_remove_spdp_actadelegado_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spdp_actadelegado',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, editable=False, help_text='Fecha automática de expiración (fecha de creación + 310 días)', null=True),
        ),
    ]
