# Generated by Django 4.2.23 on 2026-04-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0010_scvsfinancialreport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Nota'),
        ),
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='fecha_incripcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inscripción de compañia'),
        ),
    ]
