# Generated by Django 4.2.23 on 2026-02-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0010_sri_anexostributarios_bf_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_forma_cobro',
            field=models.CharField(blank=True, choices=[('01', 'Sin utilización del sistema financiero'), ('15', 'Compensación'), ('16', 'Tarjeta de débito'), ('17', 'Dinero electrónico'), ('18', 'Tarjeta prepago'), ('19', 'Tarjeta de crédito'), ('20', 'Transferencia bancaria'), ('21', 'Cheque'), ('24', 'Otros con utilización del sistema financiero')], help_text='Forma de cobro utilizada en la venta según catálogo ATS del SRI. Obligatorio desde junio 2016 cuando el comprobante es electrónico. Códigos válidos: 01=Sin sistema financiero, 15=Compensación, 16=Tarjeta débito, 17=Dinero electrónico, 18=Tarjeta prepago, 19=Tarjeta crédito, 20=Transferencia bancaria, 21=Cheque, 24=Otros con sistema financiero.', max_length=2, null=True),
        ),
    ]
