# Generated by Django 4.2.23 on 2026-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0011_alter_sri_anexostributarios_ventas_forma_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_ciudad',
            field=models.CharField(blank=True, help_text='Ciudad del beneficiario final.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del beneficiario final (YYYY-MM-DD).', null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_interseccion',
            field=models.CharField(blank=True, help_text='Intersección de la dirección.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_jurisdiccion',
            field=models.CharField(blank=True, help_text='Código país de jurisdicción si es no residente.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_nacionalidad_dos',
            field=models.CharField(blank=True, help_text='Código país segunda nacionalidad.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_nacionalidad_tres',
            field=models.CharField(blank=True, help_text='Código país tercera nacionalidad.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_nacionalidad_uno',
            field=models.CharField(blank=True, help_text='Código país de primera nacionalidad (ISO numérico, ej: 593).', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_por_administracion',
            field=models.CharField(blank=True, help_text='Indica si es beneficiario por administración (SI/NO).', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_por_otros_motivos',
            field=models.CharField(blank=True, help_text='Código de otros motivos según tabla SRI.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_por_otros_relacionados',
            field=models.CharField(blank=True, help_text='Código de otros motivos relacionados (si aplica).', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_por_propiedad',
            field=models.CharField(blank=True, help_text='Indica si es beneficiario por propiedad (SI/NO).', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_referencia',
            field=models.CharField(blank=True, help_text='Referencia adicional de dirección.', max_length=255, null=True),
        ),
    ]
