# Generated by Django 4.2.23 on 2026-02-03 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartbusinesslaw', '0011_spdp_actadelegado_fecha_expiracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCVSFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, help_text='Número de RUC de la compañía (13 dígitos)', max_length=13, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Nombre legal de la compañía', max_length=255, null=True)),
                ('company_type', models.CharField(blank=True, choices=[('SA', 'Sociedad Anónima'), ('LTDA', 'Compañía Limitada'), ('SAS', 'SAS')], help_text='Tipo de sociedad', max_length=10, null=True)),
                ('fiscal_year', models.PositiveIntegerField(blank=True, help_text='Año fiscal del reporte', null=True)),
                ('economic_activity', models.CharField(blank=True, help_text='Código CIIU de la actividad económica principal', max_length=10, null=True)),
                ('currency', models.CharField(blank=True, default='USD', help_text='Moneda utilizada en el reporte', max_length=10, null=True)),
                ('cash_and_equivalents', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo y equivalentes', max_digits=18, null=True)),
                ('short_term_investments', models.DecimalField(blank=True, decimal_places=2, help_text='Inversiones a corto plazo', max_digits=18, null=True)),
                ('accounts_receivable', models.DecimalField(blank=True, decimal_places=2, help_text='Cuentas por cobrar comerciales', max_digits=18, null=True)),
                ('inventories', models.DecimalField(blank=True, decimal_places=2, help_text='Inventarios de la compañía', max_digits=18, null=True)),
                ('other_current_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Otros activos corrientes', max_digits=18, null=True)),
                ('property_plant_equipment', models.DecimalField(blank=True, decimal_places=2, help_text='Propiedad, planta y equipo', max_digits=18, null=True)),
                ('accumulated_depreciation', models.DecimalField(blank=True, decimal_places=2, help_text='Depreciación acumulada de activos', max_digits=18, null=True)),
                ('intangible_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Activos intangibles', max_digits=18, null=True)),
                ('other_non_current_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Otros activos no corrientes', max_digits=18, null=True)),
                ('accounts_payable', models.DecimalField(blank=True, decimal_places=2, help_text='Cuentas por pagar', max_digits=18, null=True)),
                ('short_term_loans', models.DecimalField(blank=True, decimal_places=2, help_text='Obligaciones financieras a corto plazo', max_digits=18, null=True)),
                ('tax_payables', models.DecimalField(blank=True, decimal_places=2, help_text='Obligaciones tributarias', max_digits=18, null=True)),
                ('labor_obligations', models.DecimalField(blank=True, decimal_places=2, help_text='Obligaciones laborales', max_digits=18, null=True)),
                ('other_current_liabilities', models.DecimalField(blank=True, decimal_places=2, help_text='Otros pasivos corrientes', max_digits=18, null=True)),
                ('long_term_loans', models.DecimalField(blank=True, decimal_places=2, help_text='Obligaciones financieras a largo plazo', max_digits=18, null=True)),
                ('provisions', models.DecimalField(blank=True, decimal_places=2, help_text='Provisiones', max_digits=18, null=True)),
                ('other_non_current_liabilities', models.DecimalField(blank=True, decimal_places=2, help_text='Otros pasivos no corrientes', max_digits=18, null=True)),
                ('share_capital', models.DecimalField(blank=True, decimal_places=2, help_text='Capital social', max_digits=18, null=True)),
                ('legal_reserve', models.DecimalField(blank=True, decimal_places=2, help_text='Reserva legal', max_digits=18, null=True)),
                ('retained_earnings', models.DecimalField(blank=True, decimal_places=2, help_text='Resultados acumulados', max_digits=18, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, help_text='Resultado neto del ejercicio', max_digits=18, null=True)),
                ('operating_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Ingresos operativos (ventas)', max_digits=18, null=True)),
                ('cost_of_sales', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de ventas', max_digits=18, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, help_text='Utilidad bruta', max_digits=18, null=True)),
                ('administrative_expenses', models.DecimalField(blank=True, decimal_places=2, help_text='Gastos administrativos', max_digits=18, null=True)),
                ('selling_expenses', models.DecimalField(blank=True, decimal_places=2, help_text='Gastos de ventas', max_digits=18, null=True)),
                ('financial_expenses', models.DecimalField(blank=True, decimal_places=2, help_text='Gastos financieros', max_digits=18, null=True)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, help_text='Otros ingresos', max_digits=18, null=True)),
                ('other_expenses', models.DecimalField(blank=True, decimal_places=2, help_text='Otros gastos', max_digits=18, null=True)),
                ('income_tax', models.DecimalField(blank=True, decimal_places=2, help_text='Impuesto a la renta', max_digits=18, null=True)),
                ('equity_opening_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo inicial del patrimonio', max_digits=18, null=True)),
                ('equity_increases', models.DecimalField(blank=True, decimal_places=2, help_text='Incrementos en el patrimonio (aportes, utilidades)', max_digits=18, null=True)),
                ('equity_decreases', models.DecimalField(blank=True, decimal_places=2, help_text='Disminuciones del patrimonio (dividendos, pérdidas)', max_digits=18, null=True)),
                ('equity_closing_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo final del patrimonio', max_digits=18, null=True)),
                ('cashflow_operating', models.DecimalField(blank=True, decimal_places=2, help_text='Flujos de efectivo por actividades de operación', max_digits=18, null=True)),
                ('cashflow_investing', models.DecimalField(blank=True, decimal_places=2, help_text='Flujos de efectivo por actividades de inversión', max_digits=18, null=True)),
                ('cashflow_financing', models.DecimalField(blank=True, decimal_places=2, help_text='Flujos de efectivo por actividades de financiamiento', max_digits=18, null=True)),
                ('net_cash_flow', models.DecimalField(blank=True, decimal_places=2, help_text='Flujo neto de efectivo del periodo', max_digits=18, null=True)),
                ('accounts_receivable_related', models.DecimalField(blank=True, decimal_places=2, help_text='Cuentas por cobrar a partes relacionadas', max_digits=18, null=True)),
                ('accounts_payable_related', models.DecimalField(blank=True, decimal_places=2, help_text='Cuentas por pagar a partes relacionadas', max_digits=18, null=True)),
                ('fixed_assets_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo total de activos fijos', max_digits=18, null=True)),
                ('fixed_assets_depreciation', models.DecimalField(blank=True, decimal_places=2, help_text='Depreciación acumulada de activos fijos', max_digits=18, null=True)),
                ('financial_obligations_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total de obligaciones financieras', max_digits=18, null=True)),
                ('employee_profit_sharing', models.DecimalField(blank=True, decimal_places=2, help_text='Participación de los trabajadores', max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('ruc', 'fiscal_year')},
            },
        ),
        migrations.AlterModelOptions(
            name='spdp_actadelegado',
            options={'verbose_name': 'Superintendencia de Protección de Datos Personales (SPDP)', 'verbose_name_plural': 'Superintendencia de Protección de Datos Personales (SPDP)'},
        ),
        migrations.AlterField(
            model_name='spdp_actadelegado',
            name='rat_titular_datos',
            field=models.ForeignKey(blank=True, help_text='Usuario titular de los datos personales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rat_tratamientos', to=settings.AUTH_USER_MODEL, verbose_name='Titulares (DPD)'),
        ),
        migrations.DeleteModel(
            name='SCVS_InformeFinanciero',
        ),
    ]
