# Generated by Django 4.2.23 on 2026-02-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0012_sri_anexostributarios_bf_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='company_type',
            field=models.CharField(blank=True, choices=[('01', 'Sociedades en General'), ('02', 'Sociedades que Cotizan sus Acciones en Bolsa de Valores'), ('03', 'Fideicomisos'), ('04', 'Sociedades sin Fines de Lucro'), ('05', 'Sector Económico Popular y Solidario'), ('06', 'Sector Financiero Popular y Solidario'), ('07', 'Fondos de Inversión, Complementarios y Otros'), ('08', 'Sucesión Indivisa'), ('09', 'Junta de Agua'), ('10', 'Fideicomisos y Similares Extranjeros')], help_text='Tipo de sociedad según el catálogo del SRI.', max_length=2, null=True, verbose_name='Tipo de sociedad'),
        ),
    ]
