# Generated by Django 4.2.23 on 2026-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0014_alter_scvsfinancialreport_company_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaNombramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sociedad', models.CharField(default='SMARTQUAIL S.A.S.', max_length=100)),
                ('fecha_constitutiva', models.DateField(default='2020-10-20')),
                ('nombre_accionista', models.CharField(default='Santiago Mauricio Silva Domínguez', max_length=100)),
                ('cargo_accionista', models.CharField(default='Accionista fundador', max_length=50)),
                ('nombre_designado', models.CharField(max_length=100)),
                ('cargo_designado', models.CharField(default='Presidente', max_length=50)),
                ('nacionalidad_designado', models.CharField(default='ecuatoriana', max_length=50)),
                ('domicilio_designado', models.CharField(default='cantón Quito', max_length=100)),
                ('duracion_anos', models.PositiveIntegerField(default=5)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carta de Nombramiento',
                'verbose_name_plural': 'Cartas de Nombramiento',
            },
        ),
    ]
