# Generated by Django 4.2.23 on 2026-02-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0014_sri_anexostributarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sri_anexostributarios',
            options={'ordering': ['-ejercicio_fiscal', '-mes'], 'verbose_name': 'Anexo: Servicios De Rentas Internas (SRI)', 'verbose_name_plural': 'Anexos: Servicios De Rentas Internas (SRI)'},
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='beneficiarios_finales',
            field=models.CharField(blank=True, help_text='Lista de beneficiarios finales con todos sus datos: nombre, ID, nacionalidad, fecha de nacimiento, porcentaje y control indirecto.', max_length=255, null=True, verbose_name='Beneficiarios Finales'),
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='socios',
            field=models.CharField(blank=True, help_text='Lista de socios o accionistas con sus datos: nombre, ID, porcentaje de participación y tipo de participación.', max_length=255, null=True, verbose_name='Socios/Accionistas'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='base_imponible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_autorizacion',
            field=models.CharField(blank=True, max_length=49, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_base_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_base_iva_0',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_base_no_objeto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_establecimiento',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_id_proveedor',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_punto_emision',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_razon_social_proveedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_secuencial',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_tipo_comprobante',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_tipo_id_proveedor',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='compras_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='contador',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='distribuyo_dividendos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='dividendo_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_aporte_iess',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_identificacion',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_ir_retenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_nombres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_sueldo_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='empleado_tipo_id',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='fecha_certificacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='gastos_no_deducibles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='impuesto_dividendo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='impuesto_renta_causado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ingresos_exentos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='monto_operacion_parte_relacionada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='parte_relacionada_identificacion',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='parte_relacionada_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='representante_legal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_ir_codigo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_ir_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_ir_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_iva_codigo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_iva_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='retencion_iva_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_identificacion',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_porcentaje_participacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_tipo_id',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='tiene_empleados',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='tiene_partes_relacionadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='tipo_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='utilidad_contable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_base_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_base_iva_0',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_id_cliente',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_razon_social_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_tipo_id_cliente',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='ventas_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
