# Generated by Django 4.2.23 on 2026-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0015_cartanombramiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartanombramiento',
            options={'verbose_name': 'Nombramiento', 'verbose_name_plural': 'Nombramientos'},
        ),
        migrations.AddField(
            model_name='cartanombramiento',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
