# Generated by Django 4.2.23 on 2026-02-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0016_alter_sri_declaracionimpuestos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='archivo_auditoria',
            field=models.FileField(blank=True, null=True, upload_to='sri/declaraciones/auditoria/', verbose_name='Archivo de auditoría'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='cp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Número de comprobante de pago asociad.', max_digits=14, null=True, verbose_name='Número de Comprobante de Pago (CP)'),
        ),
        migrations.AddField(
            model_name='sri_declaracionimpuestos',
            name='declarado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Declarado'),
        ),
        migrations.AlterField(
            model_name='sri_declaracionimpuestos',
            name='isd_causado',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='ISD calculado automáticamente (5%).', max_digits=14, null=True, verbose_name='Salida de Divisas (ISD)'),
        ),
        migrations.AlterField(
            model_name='sri_declaracionimpuestos',
            name='retencion_renta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Retenciones de Impuesto a la Renta practicadas.', max_digits=14, null=True, verbose_name='Retenciones'),
        ),
    ]
