# Generated by Django 4.2.23 on 2026-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0016_alter_cartanombramiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartanombramiento',
            name='hash_nombramiento',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
