# Generated by Django 4.2.23 on 2026-03-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0017_cartanombramiento_hash_nombramiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='title',
            field=models.CharField(blank=True, choices=[('NOMBRAMIENTOS', 'NOMBRAMIENTOS'), ('INFORME FINANCIERO', 'INFORME FINANCIERO'), ('ACCIONISTAS', 'ACCIONISTAS')], help_text='Ttema a tratar.', max_length=20, null=True, verbose_name='Tema a tratar'),
        ),
    ]
