# Generated by Django 4.2.23 on 2026-02-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0018_remove_sri_declaracionimpuestos_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sri_declaracionimpuestos',
            name='cp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Número de comprobante de pago asociad.', max_digits=25, null=True, verbose_name='N. Comprobante (CP)'),
        ),
        migrations.AlterField(
            model_name='sri_declaracionimpuestos',
            name='isd_causado',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='ISD calculado automáticamente (5%).', max_digits=14, null=True, verbose_name='ISD a pagar'),
        ),
        migrations.AlterField(
            model_name='sri_declaracionimpuestos',
            name='patente_municipal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor anual de la patente municipal.', max_digits=14, null=True, verbose_name='PM a pagar'),
        ),
        migrations.AlterField(
            model_name='sri_declaracionimpuestos',
            name='renta_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Valor final del Impuesto a la Renta.', max_digits=16, null=True, verbose_name='IR a pagar'),
        ),
        migrations.AlterField(
            model_name='sri_declaracionimpuestos',
            name='retencion_renta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Retenciones de Impuesto a la Renta practicadas.', max_digits=14, null=True, verbose_name='RT a pagar'),
        ),
    ]
