# Generated by Django 4.2.23 on 2026-02-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0019_alter_sri_declaracionimpuestos_cp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleador_razon_social', models.CharField(help_text='Nombre legal completo de la empresa o persona empleadora.', max_length=255, verbose_name='Razón social del empleador')),
                ('empleador_ruc', models.CharField(help_text='Registro Único de Contribuyentes del empleador.', max_length=13, verbose_name='RUC del empleador')),
                ('empleador_representante_legal', models.CharField(help_text='Nombre completo del representante legal del empleador.', max_length=255, verbose_name='Representante legal')),
                ('empleador_domicilio', models.TextField(help_text='Dirección completa del empleador.', verbose_name='Domicilio del empleador')),
                ('trabajador_nombres', models.CharField(help_text='Nombres y apellidos completos del trabajador.', max_length=255, verbose_name='Nombres completos del trabajador')),
                ('trabajador_identificacion', models.CharField(help_text='Número de cédula o pasaporte del trabajador.', max_length=13, verbose_name='Número de identificación')),
                ('trabajador_nacionalidad', models.CharField(help_text='Nacionalidad del trabajador.', max_length=100, verbose_name='Nacionalidad')),
                ('trabajador_estado_civil', models.CharField(help_text='Estado civil del trabajador.', max_length=50, verbose_name='Estado civil')),
                ('trabajador_domicilio', models.TextField(help_text='Dirección domiciliaria del trabajador.', verbose_name='Domicilio del trabajador')),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Contrato por tiempo indefinido'), ('PLAZO_FIJO', 'Contrato a plazo fijo'), ('OCASIONAL', 'Contrato ocasional'), ('OBRA', 'Contrato por obra o servicio'), ('JORNADA_PARCIAL', 'Contrato de jornada parcial')], help_text='Tipo de contrato conforme al Código del Trabajo.', max_length=20, verbose_name='Tipo de contrato')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la relación laboral.', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de terminación del contrato, si aplica.', null=True, verbose_name='Fecha de finalización')),
                ('duracion_contrato', models.CharField(blank=True, help_text='Plazo del contrato en meses o días, si aplica.', max_length=100, null=True, verbose_name='Duración del contrato')),
                ('cargo', models.CharField(help_text='Cargo o puesto de trabajo del trabajador.', max_length=255, verbose_name='Cargo')),
                ('area_trabajo', models.CharField(help_text='Área o departamento donde desempeña sus funciones.', max_length=255, verbose_name='Área o departamento')),
                ('funciones', models.TextField(help_text='Descripción detallada de las funciones del trabajador.', verbose_name='Funciones del cargo')),
                ('lugar_trabajo', models.CharField(help_text='Lugar donde se ejecutarán las labores.', max_length=255, verbose_name='Lugar de trabajo')),
                ('tipo_jornada', models.CharField(choices=[('COMPLETA', 'Jornada completa'), ('PARCIAL', 'Jornada parcial'), ('NOCTURNA', 'Jornada nocturna'), ('MIXTA', 'Jornada mixta')], help_text='Tipo de jornada laboral conforme a la ley.', max_length=20, verbose_name='Tipo de jornada')),
                ('horas_semanales', models.PositiveIntegerField(help_text='Número de horas laboradas a la semana.', verbose_name='Horas semanales')),
                ('horario', models.CharField(help_text='Horario habitual de trabajo (ej. 08h00 a 17h00).', max_length=255, verbose_name='Horario de trabajo')),
                ('salario_mensual', models.DecimalField(decimal_places=2, help_text='Remuneración mensual en dólares, nunca inferior al SBU.', max_digits=10, verbose_name='Salario mensual')),
                ('forma_pago', models.CharField(help_text='Forma de pago del salario (transferencia, cheque, efectivo).', max_length=100, verbose_name='Forma de pago')),
                ('beneficios_adicionales', models.TextField(blank=True, help_text='Bonos, comisiones u otros beneficios contractuales.', null=True, verbose_name='Beneficios adicionales')),
                ('afiliacion_iess', models.BooleanField(default=True, help_text='Indica si el trabajador será afiliado al IESS.', verbose_name='Afiliación al IESS')),
                ('decimo_tercer_sueldo', models.BooleanField(default=True, help_text='Indica si el trabajador recibe décimo tercer sueldo.', verbose_name='Décimo tercer sueldo')),
                ('decimo_cuarto_sueldo', models.BooleanField(default=True, help_text='Indica si el trabajador recibe décimo cuarto sueldo.', verbose_name='Décimo cuarto sueldo')),
                ('vacaciones_anuales', models.PositiveIntegerField(default=15, help_text='Número de días de vacaciones anuales conforme a la ley.', verbose_name='Vacaciones anuales')),
                ('clausula_confidencialidad', models.BooleanField(default=True, help_text='Indica si el contrato incluye cláusula de confidencialidad.', verbose_name='Cláusula de confidencialidad')),
                ('clausula_no_competencia', models.BooleanField(default=False, help_text='Indica si existe cláusula de no competencia.', verbose_name='Cláusula de no competencia')),
                ('causales_terminacion', models.TextField(help_text='Causales de terminación conforme al Código del Trabajo.', verbose_name='Causales de terminación')),
                ('lugar_firma', models.CharField(help_text='Ciudad donde se suscribe el contrato.', max_length=255, verbose_name='Lugar de suscripción')),
                ('fecha_firma', models.DateField(help_text='Fecha de firma del contrato laboral.', verbose_name='Fecha de suscripción')),
                ('empleador_firma', models.CharField(help_text='Nombre del representante que firma el contrato.', max_length=255, verbose_name='Firma del empleador')),
                ('trabajador_firma', models.CharField(help_text='Nombre del trabajador firmante.', max_length=255, verbose_name='Firma del trabajador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato Laboral',
                'verbose_name_plural': 'Contratos Laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
