# Generated by Django 4.2.23 on 2026-03-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0019_alter_scvs_actasasamblea_title_clausulacontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='scvs_actasasamblea',
            name='acta_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
