# Generated by Django 4.2.23 on 2026-03-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0020_scvs_actasasamblea_acta_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartanombramiento',
            name='codigo_dactilar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
