# Generated by Django 4.2.23 on 2026-02-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0020_contratolaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratolaboral',
            name='hash_contrato',
            field=models.CharField(blank=True, editable=False, help_text='Hash SHA-256 único que certifica la integridad del contrato.', max_length=64, null=True, unique=True, verbose_name='Hash único del contrato'),
        ),
    ]
