# Generated by Django 4.2.23 on 2026-02-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0021_contratolaboral_hash_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_empleador', models.CharField(blank=True, help_text='Número de RUC registrado en el SRI y el IESS.', max_length=13, null=True, verbose_name='RUC del empleador')),
                ('razon_social', models.CharField(blank=True, help_text='Nombre legal de la empresa empleadora.', max_length=255, null=True, verbose_name='Razón social')),
                ('cedula_empleado', models.CharField(blank=True, help_text='Número de cédula del trabajador.', max_length=10, null=True, verbose_name='Cédula del empleado')),
                ('nacionalidad', models.CharField(blank=True, help_text='Nacionalidad del trabajador según su documento de identidad.', max_length=50, null=True, verbose_name='Nacionalidad')),
                ('nombres', models.CharField(blank=True, help_text='Nombres completos del trabajador.', max_length=100, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, help_text='Apellidos completos del trabajador.', max_length=100, null=True, verbose_name='Apellidos')),
                ('tipo_contrato', models.CharField(blank=True, help_text='Tipo de contrato registrado en el Ministerio de Trabajo.', max_length=100, null=True, verbose_name='Tipo de contrato')),
                ('numero_contrato', models.CharField(blank=True, help_text='Número o código del contrato en el Ministerio de Trabajo.', max_length=50, null=True, verbose_name='Número de contrato')),
                ('fecha_ingreso', models.DateField(blank=True, help_text='Fecha de inicio de la relación laboral.', null=True, verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(blank=True, help_text='Fecha de terminación del contrato, si aplica.', null=True, verbose_name='Fecha de salida')),
                ('mes', models.PositiveIntegerField(blank=True, help_text='Mes al que corresponde la nómina (1–12).', null=True, verbose_name='Mes')),
                ('anio', models.PositiveIntegerField(blank=True, help_text='Año al que corresponde la nómina.', null=True, verbose_name='Año')),
                ('sueldo_base', models.DecimalField(blank=True, decimal_places=2, help_text='Sueldo mensual acordado en el contrato.', max_digits=10, null=True, verbose_name='Sueldo base')),
                ('horas_extra', models.DecimalField(blank=True, decimal_places=2, help_text='Valor monetario de horas suplementarias y extraordinarias.', max_digits=10, null=True, verbose_name='Horas extra')),
                ('otros_ingresos', models.DecimalField(blank=True, decimal_places=2, help_text='Bonificaciones u otros ingresos gravados.', max_digits=10, null=True, verbose_name='Otros ingresos')),
                ('decimo_tercero', models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional del décimo tercero.', max_digits=10, null=True, verbose_name='Décimo tercero')),
                ('decimo_cuarto', models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional del décimo cuarto.', max_digits=10, null=True, verbose_name='Décimo cuarto')),
                ('utilidades', models.DecimalField(blank=True, decimal_places=2, help_text='Participación en utilidades del trabajador.', max_digits=10, null=True, verbose_name='Utilidades')),
                ('aporte_iess_trabajador', models.DecimalField(blank=True, decimal_places=2, help_text='9.45 % del sueldo base, descontado al trabajador.', max_digits=10, null=True, verbose_name='Aporte IESS trabajador')),
                ('aporte_iess_empleador', models.DecimalField(blank=True, decimal_places=2, help_text='11.15 % del sueldo base, asumido por el empleador.', max_digits=10, null=True, verbose_name='Aporte IESS empleador')),
                ('total_ingresos', models.DecimalField(blank=True, decimal_places=2, help_text='Suma total de ingresos del trabajador en el mes.', max_digits=10, null=True, verbose_name='Total ingresos')),
                ('sueldo_a_pagar', models.DecimalField(blank=True, decimal_places=2, help_text='Valor neto que recibe el trabajador luego de descuentos.', max_digits=10, null=True, verbose_name='Sueldo a pagar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se generó el registro de nómina.', verbose_name='Fecha de creación')),
                ('hash_contrato', models.CharField(blank=True, editable=False, help_text='Hash SHA-256 único que certifica la integridad del contrato.', max_length=64, null=True, unique=True, verbose_name='Hash único del contrato')),
            ],
            options={
                'verbose_name': 'Nómina de trabajador: Instituto Ecuatoriano de Seguridad Social (IESS)',
                'verbose_name_plural': 'Nómina de trabajadores: Instituto Ecuatoriano de Seguridad Social (IESS)',
            },
        ),
        migrations.AlterField(
            model_name='contratolaboral',
            name='horario',
            field=models.CharField(blank=True, help_text='Horario habitual de trabajo (ej. 08h00 a 17h00).', max_length=255, null=True, verbose_name='Horario de trabajo'),
        ),
        migrations.AlterField(
            model_name='contratolaboral',
            name='horas_semanales',
            field=models.PositiveIntegerField(blank=True, help_text='Número de horas laboradas a la semana.', null=True, verbose_name='Horas semanales'),
        ),
    ]
