# Generated by Django 4.2.23 on 2026-03-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0021_cartanombramiento_codigo_dactilar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='bf_ciudad',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='bf_es_beneficiario_final',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='bf_identificacion_informante_padre',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='bf_jurisdiccion',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='bf_nacionalidad_tres',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='bf_nombre_completo',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='bf_por_otros_relacionados',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='bf_tipo_sujeto',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='socio_identificacion_rebefics',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='socio_nombre_rebefics',
        ),
        migrations.RemoveField(
            model_name='sri_anexostributarios',
            name='socio_porcentaje_rebefics',
        ),
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='socio_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Porcentaje de participación accionaria del socio o accionista dentro de la compañía.', max_digits=9, null=True, verbose_name='Porcentaje de participación del socio'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_calle',
            field=models.CharField(blank=True, help_text='Nombre de la calle principal del domicilio del beneficiario final.', max_length=100, null=True, verbose_name='Calle principal'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_canton',
            field=models.CharField(blank=True, help_text='Código del cantón según la división política administrativa del Ecuador.', max_length=5, null=True, verbose_name='Cantón'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal correspondiente al domicilio.', max_length=10, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del beneficiario final.', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_identificacion',
            field=models.CharField(blank=True, help_text='Número de identificación del beneficiario final conforme al tipo seleccionado.', max_length=13, null=True, verbose_name='Número de identificación del beneficiario final'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_interseccion',
            field=models.CharField(blank=True, help_text='Nombre de la calle transversal o intersección.', max_length=100, null=True, verbose_name='Intersección'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_nacionalidad_dos',
            field=models.CharField(blank=True, help_text='Código numérico del país correspondiente a una segunda nacionalidad, si aplica.', max_length=3, null=True, verbose_name='Segunda nacionalidad'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_nacionalidad_uno',
            field=models.CharField(blank=True, help_text='Código numérico del país correspondiente a la nacionalidad principal del beneficiario final.', max_length=3, null=True, verbose_name='Primera nacionalidad'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_numero',
            field=models.CharField(blank=True, help_text='Número de casa, edificio o lote del domicilio.', max_length=20, null=True, verbose_name='Número de domicilio'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_parroquia',
            field=models.CharField(blank=True, help_text='Código de parroquia conforme al catálogo territorial del INEC.', max_length=7, null=True, verbose_name='Parroquia'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_por_administracion',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], help_text='Indica si el beneficiario final ejerce control mediante funciones de administración o dirección.', max_length=2, null=True, verbose_name='Control por administración'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_por_otros_motivos',
            field=models.CharField(blank=True, choices=[('01', 'Influencia significativa'), ('02', 'Control indirecto'), ('03', 'Relación contractual'), ('04', 'Acuerdo de accionistas'), ('05', 'Control familiar'), ('06', 'Control indirecto de sociedad'), ('07', 'Fideicomiso'), ('08', 'Protector'), ('09', 'Administrador o directivo')], help_text='Código que identifica otros motivos por los cuales se considera beneficiario final.', max_length=2, null=True, verbose_name='Otros motivos de control'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_por_propiedad',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], help_text='Indica si el beneficiario final ejerce control a través de participación accionaria.', max_length=2, null=True, verbose_name='Control por propiedad'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_porcentaje_participacion',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Porcentaje de participación directa o indirecta del beneficiario final en la sociedad.', max_digits=9, null=True, verbose_name='Porcentaje de participación'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_primer_apellido',
            field=models.CharField(blank=True, help_text='Primer apellido del beneficiario final.', max_length=100, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_primer_nombre',
            field=models.CharField(blank=True, help_text='Primer nombre del beneficiario final.', max_length=100, null=True, verbose_name='Primer nombre'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_provincia',
            field=models.CharField(blank=True, choices=[('01', 'Azuay'), ('02', 'Bolívar'), ('03', 'Cañar'), ('04', 'Carchi'), ('05', 'Cotopaxi'), ('06', 'Chimborazo'), ('07', 'El Oro'), ('08', 'Esmeraldas'), ('09', 'Guayas'), ('10', 'Imbabura'), ('11', 'Loja'), ('12', 'Los Ríos'), ('13', 'Manabí'), ('14', 'Morona Santiago'), ('15', 'Napo'), ('16', 'Pastaza'), ('17', 'Pichincha'), ('18', 'Tungurahua'), ('19', 'Zamora Chinchipe'), ('20', 'Galápagos'), ('21', 'Sucumbíos'), ('22', 'Orellana'), ('23', 'Santo Domingo de los Tsáchilas'), ('24', 'Santa Elena')], help_text='Provincia del domicilio del beneficiario final dentro del Ecuador.', max_length=2, null=True, verbose_name='Provincia de residencia'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_referencia',
            field=models.CharField(blank=True, help_text='Referencia adicional para ubicar el domicilio (ejemplo: edificio, oficina, referencia cercana).', max_length=255, null=True, verbose_name='Referencia de ubicación'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_residencia_fiscal',
            field=models.CharField(blank=True, help_text='Código numérico del país de residencia fiscal según estándar ISO (por ejemplo: 593 para Ecuador).', max_length=3, null=True, verbose_name='País de residencia fiscal'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_segundo_apellido',
            field=models.CharField(blank=True, help_text='Segundo apellido del beneficiario final, si aplica.', max_length=100, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_segundo_nombre',
            field=models.CharField(blank=True, help_text='Segundo nombre del beneficiario final, si aplica.', max_length=100, null=True, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_tipo_identificacion',
            field=models.CharField(blank=True, choices=[('C', 'Cédula'), ('R', 'RUC'), ('P', 'Pasaporte'), ('I', 'Identificación exterior')], help_text='Tipo de documento de identificación del beneficiario final (cédula, RUC, pasaporte o identificación exterior).', max_length=1, null=True, verbose_name='Tipo de identificación del beneficiario final'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='distribuyo_dividendos',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], help_text='Indica si durante el ejercicio fiscal se distribuyeron dividendos al beneficiario final.', max_length=2, null=True, verbose_name='Distribución de dividendos'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='dividendo_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto total de dividendos pagados al beneficiario final durante el ejercicio fiscal.', max_digits=15, null=True, verbose_name='Monto de dividendos pagados'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='impuesto_dividendo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor del impuesto retenido sobre los dividendos distribuidos.', max_digits=15, null=True, verbose_name='Impuesto retenido por dividendos'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_identificacion',
            field=models.CharField(blank=True, help_text='Número de identificación del socio o accionista.', max_length=13, null=True, verbose_name='Identificación del socio'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_nombre',
            field=models.CharField(blank=True, help_text='Nombre completo o razón social del socio o accionista.', max_length=255, null=True, verbose_name='Nombre o razón social del socio'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_tipo_identificacion',
            field=models.CharField(blank=True, choices=[('C', 'Cédula'), ('R', 'RUC'), ('P', 'Pasaporte'), ('I', 'Identificación exterior')], help_text='Tipo de identificación del socio o accionista de la compañía.', max_length=1, null=True, verbose_name='Tipo de identificación del socio'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='socio_tipo_sujeto',
            field=models.CharField(blank=True, choices=[('01', 'Persona Natural'), ('02', 'Persona Jurídica')], help_text='Tipo de sujeto del socio: persona natural o persona jurídica.', max_length=2, null=True, verbose_name='Tipo de sujeto'),
        ),
    ]
