# Generated by Django 4.2.23 on 2026-03-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0022_remove_sri_anexostributarios_bf_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sri_anexostributarios',
            name='bf_ciudad',
            field=models.CharField(blank=True, help_text='Código de ciudad según la división política administrativa del Ecuador.', max_length=5, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='sri_anexostributarios',
            name='bf_provincia',
            field=models.CharField(blank=True, choices=[('001', 'Azuay'), ('002', 'Bolívar'), ('003', 'Cañar'), ('004', 'Carchi'), ('005', 'Cotopaxi'), ('006', 'Chimborazo'), ('007', 'El Oro'), ('008', 'Esmeraldas'), ('009', 'Guayas'), ('010', 'Imbabura'), ('011', 'Loja'), ('012', 'Los Ríos'), ('013', 'Manabí'), ('014', 'Morona Santiago'), ('015', 'Napo'), ('016', 'Pastaza'), ('017', 'Pichincha'), ('018', 'Tungurahua'), ('019', 'Zamora Chinchipe'), ('020', 'Galápagos'), ('021', 'Sucumbíos'), ('022', 'Orellana'), ('023', 'Santo Domingo de los Tsáchilas'), ('024', 'Santa Elena')], help_text='Provincia del domicilio del beneficiario final dentro del Ecuador.', max_length=5, null=True, verbose_name='Provincia de residencia'),
        ),
    ]
