# Generated by Django 4.2.23 on 2026-02-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0022_nomina_alter_contratolaboral_horario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomina',
            options={'verbose_name': 'Nómina de trabajador', 'verbose_name_plural': 'Nómina de trabajadores: Instituto Ecuatoriano de Seguridad Social (IESS)'},
        ),
        migrations.AddField(
            model_name='nomina',
            name='decimo_primero',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional del décimo primero. 0 si no aplica.', max_digits=10, null=True, verbose_name='Décimo primero'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='decimo_segundo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional del décimo segundo. 0 si no aplica.', max_digits=10, null=True, verbose_name='Décimo segundo'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='descuentos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suma de descuentos legales y deducciones aplicadas al trabajador.', max_digits=10, null=True, verbose_name='Descuentos'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='recibe_bonificacion',
            field=models.BooleanField(default=False, help_text='Indica si el trabajador recibe bonificaciones. Si es False, el valor se considera 0.00.', verbose_name='Recibe bonificación'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='recibe_decimo_cuarto',
            field=models.BooleanField(default=True, help_text='Indica si aplica el décimo cuarto sueldo. Declarar al IESS.', verbose_name='Recibe décimo cuarto'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='recibe_decimo_primero',
            field=models.BooleanField(default=False, help_text='Indica si aplica el décimo primero sueldo. Declarar al IESS si corresponde.', verbose_name='Recibe décimo primero'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='recibe_decimo_segundo',
            field=models.BooleanField(default=False, help_text='Indica si aplica el décimo segundo sueldo. Declarar al IESS si corresponde.', verbose_name='Recibe décimo segundo'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='recibe_decimo_tercero',
            field=models.BooleanField(default=True, help_text='Indica si aplica el décimo tercero sueldo. Declarar al IESS.', verbose_name='Recibe décimo tercero'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='recibe_utilidades',
            field=models.BooleanField(default=False, help_text='Indica si recibe participación en utilidades. Declarar al IESS si corresponde.', verbose_name='Recibe utilidades'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='aporte_iess_trabajador',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='9.45 % del sueldo base, descontado al trabajador según IESS.', max_digits=10, null=True, verbose_name='Aporte IESS trabajador'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='decimo_cuarto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional del décimo cuarto. 0 si no aplica.', max_digits=10, null=True, verbose_name='Décimo cuarto'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='decimo_tercero',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional del décimo tercero. 0 si no aplica.', max_digits=10, null=True, verbose_name='Décimo tercero'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='otros_ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bonificaciones u otros ingresos gravados según IESS. Se coloca 0 si no aplica.', max_digits=10, null=True, verbose_name='Otros ingresos / Bonificaciones'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='sueldo_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor neto que recibe el trabajador luego de descuentos y aporte IESS.', max_digits=10, null=True, verbose_name='Sueldo a pagar'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='total_ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suma total de ingresos del trabajador en el mes, considerando bonificaciones, décimos y utilidades.', max_digits=10, null=True, verbose_name='Total ingresos'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='utilidades',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Participación en utilidades del trabajador. 0 si no aplica.', max_digits=10, null=True, verbose_name='Utilidades'),
        ),
    ]
