# Generated by Django 4.2.23 on 2026-03-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0023_sri_anexostributarios_bf_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartanombramiento',
            name='fecha_acta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartanombramiento',
            name='fecha_inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
