# Generated by Django 4.2.23 on 2026-02-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0023_alter_nomina_options_nomina_decimo_primero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='decimo_primero',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='decimo_segundo',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='recibe_decimo_primero',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='recibe_decimo_segundo',
        ),
        migrations.AddField(
            model_name='nomina',
            name='razon_descuento',
            field=models.CharField(blank=True, choices=[('PRESTAMOS_EMPLEADOR', 'Préstamos otorgados por el empleador'), ('PRESTAMOS_IESS', 'Préstamos del IESS (cesantía, hipotecarios, educativos)'), ('ANTICIPOS', 'Anticipos de sueldo'), ('APORTES_IESS', 'Aportes obligatorios al IESS'), ('IMPUESTO_RENTA', 'Retención de Impuesto a la Renta'), ('PENSION_ALIMENTICIA', 'Pensiones alimenticias'), ('EMBARGO_JUDICIAL', 'Embargos judiciales sobre salario'), ('SANCIONES_INTERNAS', 'Sanciones por incumplimiento de políticas internas, según reglamento de la empresa')], help_text='Motivo del descuento aplicado al trabajador.', max_length=50, null=True, verbose_name='Razón de descuento'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='recibe_descuento',
            field=models.BooleanField(default=False, help_text='Indica si aplica descuentos legales o deducciones al trabajador.', verbose_name='Aplica descuentos'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='recibe_decimo_cuarto',
            field=models.BooleanField(default=True, help_text='Indica si aplica el décimo cuarto sueldo. Aplica 15 agosto es un sueldo basico unificado.', verbose_name='Recibe décimo cuarto'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='recibe_decimo_tercero',
            field=models.BooleanField(default=True, help_text='Indica si aplica el décimo tercero sueldo. Aplica en Diciembre 1/2 sueldo anual. Declarar al IESS.', verbose_name='Recibe décimo tercero'),
        ),
    ]
