# Generated by Django 4.2.23 on 2026-02-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0024_remove_nomina_decimo_primero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratolaboral',
            name='ID_SUT_registro',
            field=models.CharField(blank=True, help_text='Identificador del registro del contrato en el Sistema Único de Trabajadores (SUT).', max_length=50, null=True, verbose_name='ID de registro SUT'),
        ),
        migrations.AddField(
            model_name='contratolaboral',
            name='legalizado',
            field=models.BooleanField(default=False, help_text='Indica si el contrato ha sido legalizado ante el Ministerio de Trabajo.', verbose_name='Contrato legalizado'),
        ),
    ]
