# Generated by Django 4.2.23 on 2026-02-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0025_contratolaboral_id_sut_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='apellidos',
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nombres',
            field=models.ForeignKey(blank=True, help_text='Trabajador.', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='smartbusinesslaw.contratolaboral', unique=True, verbose_name='Nombres'),
        ),
    ]
