# Generated by Django 4.2.23 on 2026-04-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0025_remove_scvsfinancialreport_accounts_payable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='administrative_expenses',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='cost_of_sales',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='financial_expenses',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='gross_profit',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='operating_revenue',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='other_expenses',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='other_income',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='selling_expenses',
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40101_venta_de_bienes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40101 - VENTA DE BIENES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010201_ingresos_por_asesoria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010201 - INGRESOS POR ASESORÍA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010202_ingresos_por_estructuracion_de_oferta_publica_de_valores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010202 - INGRESOS POR ESTRUCTURACIÓN DE OFERTA PÚBLICA DE VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010203_ingresos_por_estructuracion_de_negocios_fiduciarios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010203 - INGRESOS POR ESTRUCTURACIÓN DE NEGOCIOS FIDUCIARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010204_otros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010204 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40102_prestacion_de_servicios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40102 - PRESTACION DE SERVICIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40103_contratos_de_construccion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40103 - CONTRATOS DE CONSTRUCCION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40104_subvenciones_del_gobierno',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40104 - SUBVENCIONES DEL GOBIERNO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40105_regalias',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40105 - REGALÍAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010601_intereses_generados_por_ventas_a_credito',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010601 - INTERESES GENERADOS POR VENTAS A CREDITO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010602_intereses_y_rendimientos_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010602 - INTERESES Y RENDIMIENTOS FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010603_otros_intereses_generados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010603 - OTROS INTERESES GENERADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40106_intereses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40106 - INTERESES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40107_dividendos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40107 - DIVIDENDOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40108_ganancia_por_medicion_a_valor_razonable_de_activos_biologicos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40108 - GANANCIA POR MEDICION A VALOR RAZONABLE  DE ACTIVOS BIOLOGICOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090101_por_operaciones_bursatiles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090101 - POR OPERACIONES BURSATILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090103_por_contratos_de_underwriting',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090103 - POR CONTRATOS DE UNDERWRITING', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090104_por_comision_en_operaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090104 - POR COMISIÓN EN OPERACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090105_por_inscripciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090105 - POR INSCRIPCIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090106_por_mantenimiento_de_inscripcion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090106 - POR MANTENIMIENTO DE INSCRIPCIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010901_comisiones_ganadas_por_intermediacion_de_valores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010901 - COMISIONES GANADAS POR INTERMEDIACIÓN DE VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090201_portafolio_de_terceros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090201 - PORTAFOLIO DE TERCEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090202_fondos_administrados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090202 - FONDOS ADMINISTRADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090203_fondos_colectivos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090203 - FONDOS COLECTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090204_titularizacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090204 - TITULARIZACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090205_fideicomisos_mercantiles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090205 - FIDEICOMISOS MERCANTILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090206_encargos_fiduciarios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090206 - ENCARGOS FIDUCIARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090207_por_calificacion_de_riesgo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090207 - POR CALIFICACION DE RIESGO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090208_por_representacion_de_obligacionistas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090208 - POR REPRESENTACION DE OBLIGACIONISTAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010902_por_prestacion_de_servicios_de_administracion_y_manejo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010902 - POR PRESTACIÓN DE SERVICIOS DE ADMINISTRACIÓN Y MANEJO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090301_custodia_valores_materializados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090301 - CUSTODIA VALORES MATERIALIZADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090302_custodia_valores_desmaterializados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090302 - CUSTODIA VALORES DESMATERIALIZADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090303_compensacion_y_liquidacion_de_valores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090303 - COMPENSACIÓN Y LIQUIDACIÓN DE VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090304_otros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090304 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010903_custodia_registro_compensacion_y_liquidacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010903 - CUSTODIA, REGISTRO, COMPENSACIÓN Y LIQUIDACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40109_ingresos_por_comisiones_prestacion_de_servicios_custodia_registro_compensacion_y_liquidacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40109 - INGRESOS POR COMISIONES, PRESTACIÓN DE SERVICIOS, CUSTODIA, REGISTRO, COMPENSACIÓN Y LIQUIDACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011001_dividendos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011001 - DIVIDENDOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011002_intereses_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011002 - INTERESES FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011003_ganancia_en_inversiones_en_asociadas_subsidiarias_y_otras',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011003 - GANANCIA EN INVERSIONES EN ASOCIADAS / SUBSIDIARIAS Y OTRAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011004_valuacion_de_instrumentos_financieros_a_valor_razonable_con_cambio_en_resultados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011004 - VALUACION DE INSTRUMENTOS FINANCIEROS A VALOR RAZONABLE CON CAMBIO EN RESULTADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011005_ganancia_en_venta_de_titulos_valores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011005 - GANANCIA EN VENTA DE TITULOS VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011006_otros_ingresos_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011006 - OTROS INGRESOS  FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40110_ingresos_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40110 - INGRESOS  FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40112_descuento_en_ventas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40112 - (-) DESCUENTO EN VENTAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40113_devoluciones_en_ventas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40113 - (-) DEVOLUCIONES EN VENTAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40114_bonificacion_en_producto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40114 - (-) BONIFICACIÓN EN PRODUCTO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40115_otras_rebajas_comerciales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40115 - (-) OTRAS REBAJAS COMERCIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40116_utilidad_en_cambio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40116 - UTILIDAD EN CAMBIO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401_ingresos_de_actividades_ordinarias',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401 - INGRESOS DE ACTIVIDADES ORDINARIAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_402_ganancia_bruta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 402 - GANANCIA BRUTA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40301_ganancia_en_venta_de_propiedad_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40301 - GANANCIA EN VENTA DE PROPIEDAD, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40302_ganancia_en_venta_de_activos_biologicos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40302 - GANANCIA EN VENTA DE ACTIVOS BIOLÓGICOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40303_otros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40303 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_403_otros_ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 403 - OTROS INGRESOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010101_inventario_inicial_de_bienes_no_producidos_por_la_compania',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010101 - (+) INVENTARIO INICIAL DE BIENES NO PRODUCIDOS POR LA COMPAÑIA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010102_compras_netas_locales_de_bienes_no_producidos_por_la_compania',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010102 - (+) COMPRAS NETAS LOCALES DE BIENES NO PRODUCIDOS POR LA COMPAÑIA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010103_importaciones_de_bienes_no_producidos_por_la_compania',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010103 - (+) IMPORTACIONES DE BIENES NO PRODUCIDOS POR LA COMPAÑIA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010104_inventario_final_de_bienes_no_producidos_por_la_compania',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010104 - (-) INVENTARIO FINAL DE BIENES NO PRODUCIDOS POR LA COMPAÑIA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010105_inventario_inicial_de_materia_prima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010105 - (+) INVENTARIO INICIAL DE MATERIA PRIMA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010106_compras_netas_locales_de_materia_prima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010106 - (+) COMPRAS NETAS LOCALES DE MATERIA PRIMA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010107_importaciones_de_materia_prima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010107 - (+) IMPORTACIONES DE MATERIA PRIMA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010108_inventario_final_de_materia_prima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010108 - (-) INVENTARIO FINAL DE MATERIA PRIMA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010109_inventario_inicial_de_productos_en_proceso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010109 - (+) INVENTARIO INICIAL DE PRODUCTOS EN PROCESO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010110_inventario_final_de_productos_en_proceso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010110 - (-) INVENTARIO FINAL DE PRODUCTOS EN PROCESO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010111_inventario_inicial_productos_terminados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010111 - (+) INVENTARIO INICIAL PRODUCTOS TERMINADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010112_inventario_final_de_productos_terminados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010112 - (-) INVENTARIO FINAL DE PRODUCTOS TERMINADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50101_materiales_utilizados_o_productos_vendidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50101 - MATERIALES UTILIZADOS O PRODUCTOS VENDIDOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010201_sueldos_y_beneficios_sociales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010201 - SUELDOS Y BENEFICIOS SOCIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010202_gastos_planes_de_beneficios_a_empleados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010202 - GASTOS PLANES DE BENEFICIOS A EMPLEADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50102_mano_de_obra_directa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50102 - (+) MANO DE OBRA DIRECTA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010301_sueldos_y_beneficios_sociales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010301 - SUELDOS Y BENEFICIOS SOCIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010302_gasto_planes_de_beneficios_a_empleados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010302 - GASTO PLANES DE BENEFICIOS A EMPLEADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50103_mano_de_obra_indirecta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50103 - (+) MANO DE OBRA INDIRECTA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010401_depreciacion_propiedades_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010401 - DEPRECIACIÓN PROPIEDADES, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010402_deterioro_o_perdidas_de_activos_biologicos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010402 - DETERIORO O PERDIDAS DE ACTIVOS BIOLOGICOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010403_deterioro_de_propiedad_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010403 - DETERIORO DE PROPIEDAD, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010404_efecto_valor_neto_de_realizacion_de_inventarios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010404 - EFECTO VALOR NETO DE REALIZACION DE INVENTARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010405_gasto_por_garantias_en_venta_de_productos_o_servicios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010405 - GASTO POR GARANTIAS EN VENTA DE PRODUCTOS O SERVICIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010406_mantenimiento_y_reparaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010406 - MANTENIMIENTO Y REPARACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010407_suministros_materiales_y_repuestos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010407 - SUMINISTROS MATERIALES Y REPUESTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010408_otros_costos_de_produccion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010408 - OTROS COSTOS DE PRODUCCIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50104_otros_costos_indirectos_de_fabricacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50104 - (+) OTROS COSTOS INDIRECTOS DE FABRICACION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010501_costos_de_acuerdo_a_porcentajes_o_grados_de_terminacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010501 - COSTOS DE ACUERDO A PORCENTAJES O GRADOS DE TERMINACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50105_costos_de_contratos_de_construcciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50105 - COSTOS DE CONTRATOS DE CONSTRUCCIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_501_costo_de_ventas_y_produccion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 501 - COSTO DE VENTAS Y PRODUCCIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020101_sueldos_salarios_y_demas_remuneraciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020101 - SUELDOS, SALARIOS Y DEMÁS REMUNERACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020102_aportes_a_la_seguridad_social_incluido_fondo_de_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020102 - APORTES A LA SEGURIDAD SOCIAL (INCLUIDO FONDO DE RESERVA)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020103_beneficios_sociales_e_indemnizaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020103 - BENEFICIOS SOCIALES E INDEMNIZACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020104_gasto_planes_de_beneficios_a_empleados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020104 - GASTO PLANES DE BENEFICIOS A EMPLEADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020105_honorarios_comisiones_y_dietas_a_personas_naturales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020105 - HONORARIOS, COMISIONES Y DIETAS A PERSONAS NATURALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020106_remuneraciones_a_otros_trabajadores_autonomos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020106 - REMUNERACIONES A OTROS TRABAJADORES AUTÓNOMOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020107_honorarios_a_extranjeros_por_servicios_ocasionales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020107 - HONORARIOS A EXTRANJEROS POR SERVICIOS OCASIONALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020108_mantenimiento_y_reparaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020108 - MANTENIMIENTO Y REPARACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020109_arrendamiento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020109 - ARRENDAMIENTO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020110_comisiones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020110 - COMISIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020111_promocion_y_publicidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020111 - PROMOCIÓN Y PUBLICIDAD', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020112_combustibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020112 - COMBUSTIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020113_lubricantes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020113 - LUBRICANTES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020114_seguros_y_reaseguros_primas_y_cesiones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020114 - SEGUROS Y REASEGUROS (PRIMAS Y CESIONES)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020115_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020115 - TRANSPORTE', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020116_gastos_de_gestion_agasajos_a_accionistas_trabajadores_y_clientes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020116 - GASTOS DE GESTIÓN (AGASAJOS A ACCIONISTAS, TRABAJADORES Y CLIENTES)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020117_gastos_de_viaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020117 - GASTOS DE VIAJE', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020118_agua_energia_luz_y_telecomunicaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020118 - AGUA, ENERGÍA, LUZ, Y TELECOMUNICACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020119_notarios_y_registradores_de_la_propiedad_o_mercantiles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020119 - NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MERCANTILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012001_propiedades_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012001 - PROPIEDADES, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012002_propiedades_de_inversion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012002 - PROPIEDADES DE INVERSIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012003_activos_por_derecho_de_uso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012003 - ACTIVOS POR DERECHO DE USO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020120_depreciaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020120 - DEPRECIACIONES:', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012101_intangibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012101 - INTANGIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012102_otros_activos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012102 - OTROS ACTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020121_amortizaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020121 - AMORTIZACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012201_propiedades_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012201 - PROPIEDADES, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012202_inventarios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012202 - INVENTARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012203_instrumentos_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012203 - INSTRUMENTOS FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012204_intangibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012204 - INTANGIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012205_cuentas_por_cobrar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012205 - CUENTAS POR COBRAR', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012206_otros_activos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012206 - OTROS ACTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012207_derechos_de_uso_por_activos_arrendados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012207 - DERECHOS DE USO POR ACTIVOS ARRENDADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020122_gasto_deterioro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020122 - GASTO DETERIORO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012301_mano_de_obra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012301 - MANO DE OBRA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012302_materiales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012302 - MATERIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012303_costos_de_produccion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012303 - COSTOS DE PRODUCCION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020123_gastos_por_cantidades_anormales_de_utilizacion_en_el_proceso_de_produccion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020123 - GASTOS POR CANTIDADES ANORMALES DE UTILIZACION EN EL PROCESO DE PRODUCCIÓN:', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020124_gasto_por_reestructuracion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020124 - GASTO POR REESTRUCTURACION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020125_valor_neto_de_realizacion_de_inventarios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020125 - VALOR NETO DE REALIZACION DE INVENTARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020126_gasto_impuesto_a_la_renta_activos_y_pasivos_diferidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020126 - GASTO IMPUESTO A LA RENTA (ACTIVOS Y PASIVOS DIFERIDOS)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020127_suministros_y_materiales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020127 - SUMINISTROS Y MATERIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020128_otros_gastos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020128 - OTROS GASTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50201_gastos_de_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50201 - GASTOS DE VENTA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020201_sueldos_salarios_y_demas_remuneraciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020201 - SUELDOS, SALARIOS Y DEMÁS REMUNERACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020202_aportes_a_la_seguridad_social_incluido_fondo_de_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020202 - APORTES A LA SEGURIDAD SOCIAL (INCLUIDO FONDO DE RESERVA)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020203_beneficios_sociales_e_indemnizaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020203 - BENEFICIOS SOCIALES E INDEMNIZACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020204_gasto_planes_de_beneficios_a_empleados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020204 - GASTO PLANES DE BENEFICIOS A EMPLEADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020205_honorarios_comisiones_y_dietas_a_personas_naturales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020205 - HONORARIOS, COMISIONES Y DIETAS A PERSONAS NATURALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020206_remuneraciones_a_otros_trabajadores_autonomos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020206 - REMUNERACIONES A OTROS TRABAJADORES AUTÓNOMOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020207_honorarios_a_extranjeros_por_servicios_ocasionales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020207 - HONORARIOS A EXTRANJEROS POR SERVICIOS OCASIONALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020208_mantenimiento_y_reparaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020208 - MANTENIMIENTO Y REPARACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020209_arrendamiento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020209 - ARRENDAMIENTO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020210_comisiones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020210 - COMISIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020211_promocion_y_publicidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020211 - PROMOCIÓN Y PUBLICIDAD', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020212_combustibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020212 - COMBUSTIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020213_lubricantes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020213 - LUBRICANTES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020214_seguros_y_reaseguros_primas_y_cesiones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020214 - SEGUROS Y REASEGUROS (PRIMAS Y CESIONES)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020215_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020215 - TRANSPORTE', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020216_gastos_de_gestion_agasajos_a_accionistas_trabajadores_y_clientes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020216 - GASTOS DE GESTIÓN (AGASAJOS A ACCIONISTAS, TRABAJADORES Y CLIENTES)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020217_gastos_de_viaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020217 - GASTOS DE VIAJE', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020218_agua_energia_luz_y_telecomunicaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020218 - AGUA, ENERGÍA, LUZ, Y TELECOMUNICACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020219_notarios_y_registradores_de_la_propiedad_o_mercantiles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020219 - NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MERCANTILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020220_impuestos_contribuciones_y_otros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020220 - IMPUESTOS, CONTRIBUCIONES Y OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022101_propiedades_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022101 - PROPIEDADES, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022102_propiedades_de_inversion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022102 - PROPIEDADES DE INVERSIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022103_activos_por_derecho_de_uso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022103 - ACTIVOS POR DERECHO DE USO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020221_depreciaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020221 - DEPRECIACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022201_intangibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022201 - INTANGIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022202_otros_activos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022202 - OTROS ACTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020222_amortizaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020222 - AMORTIZACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022301_propiedades_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022301 - PROPIEDADES, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022302_inventarios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022302 - INVENTARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022303_instrumentos_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022303 - INSTRUMENTOS FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022304_intangibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022304 - INTANGIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022305_cuentas_por_cobrar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022305 - CUENTAS POR COBRAR', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022306_otros_activos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022306 - OTROS ACTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022307_derechos_de_uso_por_activos_arrendados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022307 - DERECHOS DE USO POR ACTIVOS ARRENDADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020223_gasto_deterioro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020223 - GASTO DETERIORO:', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022401_mano_de_obra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022401 - MANO DE OBRA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022402_materiales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022402 - MATERIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022403_costos_de_produccion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022403 - COSTOS DE PRODUCCION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020224_gastos_por_cantidades_anormales_de_utilizacion_en_el_proceso_de_produccion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020224 - GASTOS POR CANTIDADES ANORMALES DE UTILIZACION EN EL PROCESO DE PRODUCCIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020225_gasto_por_reestructuracion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020225 - GASTO POR REESTRUCTURACION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020226_valor_neto_de_realizacion_de_inventarios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020226 - VALOR NETO DE REALIZACION DE INVENTARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020227_gasto_impuesto_a_la_renta_activos_y_pasivos_diferidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020227 - GASTO IMPUESTO A LA RENTA (ACTIVOS Y PASIVOS DIFERIDOS)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020228_suministros_y_materiales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020228 - SUMINISTROS Y MATERIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020229_otros_gastos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020229 - OTROS GASTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50202_gastos_administrativos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50202 - GASTOS ADMINISTRATIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030101_intereses_por_prestamos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030101 - INTERESES POR PRESTAMOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030102_intereses_por_arrendamientos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030102 - INTERESES POR ARRENDAMIENTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030103_intereses_por_valores_emitidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030103 - INTERESES POR VALORES EMITIDOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030104_otros_intereses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030104 - OTROS INTERESES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020301_intereses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020301 - INTERESES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203020101_por_operaciones_bursatiles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203020101 - POR OPERACIONES BURSATILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203020103_por_contratos_de_underwriting',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203020103 - POR CONTRATOS DE UNDERWRITING', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203020104_por_comision_en_operaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203020104 - POR COMISIÓN EN OPERACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203020105_por_inscripciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203020105 - POR INSCRIPCIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203020106_por_mantenimiento_de_inscripcion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203020106 - POR MANTENIMIENTO DE INSCRIPCIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030201_comisiones_pagadas_por_intermediacion_de_valores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030201 - COMISIONES PAGADAS POR INTERMEDIACIÓN DE VALORES:', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020302_comisiones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020302 - COMISIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030301_portafolio_de_terceros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030301 - PORTAFOLIO DE TERCEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030302_fondos_administrados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030302 - FONDOS ADMINISTRADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030303_fondos_colectivos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030303 - FONDOS COLECTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030304_titularizacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030304 - TITULARIZACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030305_fideicomisos_mercantiles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030305 - FIDEICOMISOS MERCANTILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030306_encargos_fiduciarios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030306 - ENCARGOS FIDUCIARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030307_por_calificacion_de_riesgo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030307 - POR CALIFICACION DE RIESGO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030308_por_representacion_de_obligacionistas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030308 - POR REPRESENTACION DE OBLIGACIONISTAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020303_por_prestacion_de_servicios_de_administracion_y_manejo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020303 - POR PRESTACIÓN DE SERVICIOS DE ADMINISTRACIÓN Y MANEJO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030401_custodia_valores_materializados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030401 - CUSTODIA VALORES MATERIALIZADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030402_custodia_valores_desmaterializados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030402 - CUSTODIA VALORES DESMATERIALIZADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030403_compensacion_y_liquidacion_de_valores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030403 - COMPENSACIÓN Y LIQUIDACIÓN DE VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030404_otros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030404 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020304_custodia_registro_compensacion_y_liquidacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020304 - CUSTODIA, REGISTRO, COMPENSACIÓN Y LIQUIDACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030501_por_asesoria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030501 - POR ASESORÍA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030502_por_estructuracion_de_oferta_publica_de_valores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030502 - POR ESTRUCTURACIÓN DE OFERTA PÚBLICA DE VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030503_por_estructuracion_de_negocios_fiduciarios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030503 - POR ESTRUCTURACIÓN DE NEGOCIOS FIDUCIARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030504_otros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030504 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020305_gastos_por_servicios_de_asesoria_y_estructuracion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020305 - GASTOS POR SERVICIOS DE ASESORIA Y ESTRUCTURACION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020306_gastos_de_financiamiento_de_activos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020306 - GASTOS DE FINANCIAMIENTO DE ACTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020307_diferencia_en_cambio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020307 - DIFERENCIA EN CAMBIO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020308_valuacion_de_instrumentos_financieros_a_valor_razonable_con_cambio_en_resultados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020308 - VALUACION DE INSTRUMENTOS FINANCIEROS A VALOR RAZONABLE CON CAMBIO EN RESULTADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020309_perdida_en_venta_de_titulos_valores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020309 - PERDIDA EN VENTA DE TITULOS VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020310_perdida_en_venta_de_propiedad_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020310 - PERDIDA EN VENTA DE PROPIEDAD, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020311_perdida_en_venta_de_activos_biologicos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020311 - PERDIDA EN VENTA DE ACTIVOS BIOLOGICOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020312_otros_gastos_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020312 - OTROS GASTOS FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203_gastos_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203 - GASTOS FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020401_perdida_en_inversiones_en_asociadas_subsidiarias_y_otras',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020401 - PERDIDA EN INVERSIONES EN ASOCIADAS / SUBSIDIARIAS Y OTRAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020402_otros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020402 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50204_otros_gastos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50204 - OTROS GASTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502_gastos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502 - GASTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_600_ganancia_perdida_antes_de_15_a_trabajadores_e_impuesto_a_la_renta_de_operaciones_continuadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 600 - GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES E IMPUESTO A LA RENTA DE OPERACIONES CONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_601_15_participacion_trabajadores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 601 - 15% PARTICIPACIÓN TRABAJADORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_602_ganancia_perdida_antes_de_impuestos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 602 - GANANCIA (PÉRDIDA) ANTES DE IMPUESTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_603_impuesto_a_la_renta_causado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 603 - IMPUESTO A LA RENTA CAUSADO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_604_ganancia_perdida_de_operaciones_continuadas_antes_del_impuesto_diferido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 604 - GANANCIA (PÉRDIDA) DE OPERACIONES CONTINUADAS ANTES DEL IMPUESTO DIFERIDO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_605_gasto_por_impuesto_diferido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 605 - (-) GASTO POR IMPUESTO DIFERIDO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_606_ingreso_por_impuesto_diferido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 606 - (+) INGRESO POR IMPUESTO DIFERIDO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_607_ganancia_perdida_de_operaciones_continuadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 607 - GANANCIA (PERDIDA) DE OPERACIONES CONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_700_ingresos_por_operaciones_discontinuadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 700 - INGRESOS POR OPERACIONES DISCONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_701_gastos_por_operaciones_discontinuadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 701 - GASTOS POR OPERACIONES DISCONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_702_ganancia_perdida_antes_de_15_a_trabajadores_e_impuesto_a_la_renta_de_operaciones_discontinuadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 702 - GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES E IMPUESTO A LA RENTA DE OPERACIONES DISCONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_703_15_participacion_trabajadores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 703 - 15% PARTICIPACIÓN TRABAJADORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_704_ganancia_perdida_antes_de_impuestos_de_operaciones_discontinuadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 704 - GANANCIA (PÉRDIDA) ANTES DE IMPUESTOS DE OPERACIONES DISCONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_705_impuesto_a_la_renta_causado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 705 - IMPUESTO A LA RENTA CAUSADO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_706_ganancia_perdida_de_operaciones_discontinuadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 706 - GANANCIA (PÉRDIDA) DE OPERACIONES DISCONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_707_ganancia_perdida_neta_del_periodo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 707 - GANANCIA (PÉRDIDA) NETA DEL PERIODO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80001_componentes_del_otro_resultado_integral',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80001 - COMPONENTES DEL OTRO RESULTADO INTEGRAL', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80002_diferencia_de_cambio_por_conversion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80002 - DIFERENCIA DE CAMBIO POR CONVERSIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80003_valuacion_de_activos_financieros_a_valor_razonable_con_cambio_en_otro_resultado_integral',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80003 - VALUACIÓN DE ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIO EN OTRO RESULTADO INTEGRAL', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80004_ganancias_por_revaluacion_de_propiedades_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80004 - GANANCIAS POR REVALUACIÓN DE PROPIEDADES, PLANTA  Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80005_ganancias_perdidas_actuariales_por_planes_de_beneficios_definidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80005 - GANANCIAS (PÉRDIDAS) ACTUARIALES POR PLANES DE BENEFICIOS DEFINIDOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80006_reversion_del_deterioro_perdida_por_deterioro_de_un_activo_revaluado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80006 - REVERSION DEL DETERIORO (PÉRDIDA POR DETERIORO) DE UN ACTIVO REVALUADO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80007_participacion_de_otro_resultado_integral_de_asociadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80007 - PARTICIPACION DE OTRO RESULTADO INTEGRAL DE ASOCIADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80008_impuesto_sobre_las_ganancias_relativo_a_otro_resultado_integral',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80008 - IMPUESTO SOBRE LAS GANANCIAS RELATIVO A OTRO RESULTADO INTEGRAL', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80009_otros_detallar_en_notas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80009 - OTROS (DETALLAR EN NOTAS)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_800_otro_resultado_integral',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 800 - OTRO RESULTADO INTEGRAL', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80101_propietarios_de_la_controladora',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80101 - PROPIETARIOS DE LA CONTROLADORA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80102_participacion_no_controladora_informativo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80102 - PARTICIPACION NO CONTROLADORA (INFORMATIVO)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_801_resultado_integral_total_del_ano',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 801 - RESULTADO INTEGRAL TOTAL DEL AÑO', max_digits=20, null=True),
        ),
    ]
