# Generated by Django 4.2.23 on 2026-02-05 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0026_remove_nomina_apellidos_alter_nomina_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='recibe_vacaciones',
            field=models.BooleanField(default=False, help_text='Indica si el trabajador recibe pago de vacaciones proporcional.', verbose_name='Recibe vacaciones'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='vacaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional de vacaciones (15 días de sueldo base). 0 si no aplica.', max_digits=10, null=True, verbose_name='Valor vacaciones'),
        ),
        migrations.AlterField(
            model_name='contratolaboral',
            name='trabajador_nombres',
            field=models.CharField(help_text='Nombres y apellidos completos del trabajador.', max_length=255, verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='aporte_iess_empleador',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='11.15 % del sueldo base, asumido por el empleador.', max_digits=10, null=True, verbose_name='Aporte IESS-E'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='aporte_iess_trabajador',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='9.45 % del sueldo base, descontado al trabajador según IESS.', max_digits=10, null=True, verbose_name='Aporte IESS-T'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='decimo_cuarto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional del décimo cuarto. 0 si no aplica.', max_digits=10, null=True, verbose_name='Décimo 4'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='decimo_tercero',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional del décimo tercero. 0 si no aplica.', max_digits=10, null=True, verbose_name='Décimo 3'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nombres',
            field=models.ForeignKey(blank=True, help_text='Trabajador.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='smartbusinesslaw.contratolaboral', unique=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='otros_ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bonificaciones u otros ingresos gravados según IESS. Se coloca 0 si no aplica.', max_digits=10, null=True, verbose_name='Bonificaciones'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='sueldo_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor neto que recibe el trabajador luego de descuentos y aporte IESS.', max_digits=10, null=True, verbose_name='Sueldo'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='total_ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suma total de ingresos del trabajador en el mes, considerando bonificaciones, décimos, utilidades y vacaciones.', max_digits=10, null=True, verbose_name='Total ingresos'),
        ),
    ]
