# Generated by Django 4.2.23 on 2026-04-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0026_remove_scvsfinancialreport_administrative_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='cashflow_financing',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='cashflow_investing',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='cashflow_operating',
        ),
        migrations.RemoveField(
            model_name='scvsfinancialreport',
            name='net_cash_flow',
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010101_cobros_procedentes_de_las_ventas_de_bienes_y_prestacion_de_servicios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010101 - Cobros procedentes de las ventas de bienes y prestación de servicios', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010102_cobros_procedentes_de_regalias_cuotas_comisiones_y_otros_ingresos_de_actividades_ordinarias',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010102 - Cobros procedentes de regalías, cuotas, comisiones y otros ingresos de actividades ordinarias', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010103_cobros_procedentes_de_contratos_mantenidos_con_propositos_de_intermediacion_o_para_negociar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010103 - Cobros procedentes de contratos mantenidos con propósitos de intermediación o para negociar', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010104_cobros_procedentes_de_primas_y_prestaciones_anualidades_y_otros_beneficios_de_polizas_suscritas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010104 - Cobros procedentes de primas y prestaciones, anualidades y otros beneficios de pólizas suscritas', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010105_otros_cobros_por_actividades_de_operacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010105 - Otros cobros por actividades de operación', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950101_clases_de_cobros_por_actividades_de_operacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950101 - Clases de cobros por actividades de operación', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010201_pagos_a_proveedores_por_el_suministro_de_bienes_y_servicios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010201 - Pagos a proveedores por el suministro de bienes y servicios', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010202_pagos_procedentes_de_contratos_mantenidos_para_intermediacion_o_para_negociar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010202 - Pagos procedentes de contratos mantenidos para intermediación o para negociar', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010203_pagos_a_y_por_cuenta_de_los_empleados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010203 - Pagos a y por cuenta de los empleados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010204_pagos_por_primas_y_prestaciones_anualidades_y_otras_obligaciones_derivadas_de_las_polizas_suscritas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010204 - Pagos por primas y prestaciones, anualidades y otras obligaciones derivadas de las pólizas suscritas', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010205_otros_pagos_por_actividades_de_operacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010205 - Otros pagos por actividades de operación', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950102_clases_de_pagos_por_actividades_de_operacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950102 - Clases de pagos por actividades de operación', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950103_dividendos_pagados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950103 - Dividendos pagados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950104_dividendos_recibidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950104 - Dividendos recibidos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950105_intereses_pagados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950105 - Intereses pagados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950106_intereses_recibidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950106 - Intereses recibidos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950107_impuestos_a_las_ganancias_pagados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950107 - Impuestos a las ganancias pagados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950108_otras_entradas_salidas_de_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950108 - Otras entradas (salidas) de efectivo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9501_flujos_de_efectivo_procedentes_de_utilizados_en_actividades_de_operacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9501 - FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE OPERACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950201_efectivo_procedentes_de_la_venta_de_acciones_en_subsidiarias_u_otros_negocios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950201 - Efectivo procedentes de la venta de acciones en subsidiarias u otros negocios', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950202_efectivo_utilizado_para_adquirir_acciones_en_subsidiarias_u_otros_negocios_para_tener_el_control',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950202 - Efectivo utilizado para adquirir acciones en subsidiarias u otros negocios para tener el control', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950203_efectivo_utilizado_en_la_compra_de_participaciones_no_controladoras',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950203 - Efectivo utilizado en la compra de participaciones no controladoras', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950204_otros_cobros_por_la_venta_de_acciones_o_instrumentos_de_deuda_de_otras_entidades',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950204 - Otros cobros por la venta de acciones o instrumentos de deuda de otras entidades', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950205_otros_pagos_para_adquirir_acciones_o_instrumentos_de_deuda_de_otras_entidades',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950205 - Otros pagos para adquirir acciones o instrumentos de deuda de otras entidades', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950206_otros_cobros_por_la_venta_de_participaciones_en_negocios_conjuntos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950206 - Otros cobros por la venta de participaciones en negocios conjuntos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950207_otros_pagos_para_adquirir_participaciones_en_negocios_conjuntos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950207 - Otros pagos para adquirir participaciones en negocios conjuntos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950208_importes_procedentes_por_la_venta_de_propiedades_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950208 - Importes procedentes por la venta de propiedades, planta y equipo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950209_adquisiciones_de_propiedades_planta_y_equipo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950209 - Adquisiciones de propiedades, planta y equipo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950210_importes_procedentes_de_ventas_de_activos_intangibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950210 - Importes procedentes de ventas de activos intangibles', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950211_compras_de_activos_intangibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950211 - Compras de activos intangibles', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950212_importes_procedentes_de_otros_activos_a_largo_plazo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950212 - Importes procedentes de otros activos a largo plazo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950213_compras_de_otros_activos_a_largo_plazo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950213 - Compras de otros activos a largo plazo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950214_importes_procedentes_de_subvenciones_del_gobierno',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950214 - Importes procedentes de subvenciones del gobierno', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950215_anticipos_de_efectivo_efectuados_a_terceros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950215 - Anticipos de efectivo efectuados a terceros', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950216_cobros_procedentes_del_reembolso_de_anticipos_y_prestamos_concedidos_a_terceros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950216 - Cobros procedentes del reembolso de anticipos y préstamos concedidos a terceros', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950217_pagos_derivados_de_contratos_de_futuro_a_termino_de_opciones_y_de_permuta_financiera',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950217 - Pagos derivados de contratos de futuro, a término, de opciones y de permuta financiera', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950218_cobros_procedentes_de_contratos_de_futuro_a_termino_de_opciones_y_de_permuta_financiera',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950218 - Cobros procedentes de contratos de futuro, a término, de opciones y de permuta financiera', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950219_dividendos_recibidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950219 - Dividendos recibidos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950220_intereses_recibidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950220 - Intereses recibidos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950221_otras_entradas_salidas_de_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950221 - Otras entradas (salidas) de efectivo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9502_flujos_de_efectivo_procedentes_de_utilizados_en_actividades_de_inversion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9502 - FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE INVERSIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950301_aporte_en_efectivo_por_aumento_de_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950301 - Aporte en efectivo por aumento de capital', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950302_financiamiento_por_emision_de_titulos_valores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950302 - Financiamiento por emisión de títulos valores', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950303_pagos_por_adquirir_o_rescatar_las_acciones_de_la_entidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950303 - Pagos por adquirir o rescatar las acciones de la entidad', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950304_financiacion_por_prestamos_a_largo_plazo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950304 - Financiación por préstamos a largo plazo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950305_pagos_de_prestamos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950305 - Pagos de préstamos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950306_pagos_de_pasivos_por_arrendamientos_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950306 - Pagos de pasivos por arrendamientos financieros', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950307_importes_procedentes_de_subvenciones_del_gobierno',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950307 - Importes procedentes de subvenciones del gobierno', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950308_dividendos_pagados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950308 - Dividendos pagados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950309_intereses_recibidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950309 - Intereses recibidos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950310_otras_entradas_salidas_de_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950310 - Otras entradas (salidas) de efectivo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9503_flujos_de_efectivo_procedentes_de_utilizados_en_actividades_de_financiacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9503 - FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE FINANCIACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950401_efectos_de_la_variacion_en_la_tasa_de_cambio_sobre_el_efectivo_y_equivalentes_al_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950401 - Efectos de la variación en la tasa de cambio sobre el efectivo y equivalentes al efectivo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9504_efectos_de_la_variacion_en_la_tasa_de_cambio_sobre_el_efectivo_y_equivalentes_al_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9504 - EFECTOS DE LA VARIACION EN LA TASA DE CAMBIO SOBRE EL EFECTIVO Y EQUIVALENTES AL EFECTIVO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9505_incremento_disminucion_neto_de_efectivo_y_equivalentes_al_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9505 - INCREMENTO (DISMINUCIÓN) NETO DE EFECTIVO Y EQUIVALENTES AL EFECTIVO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9506_efectivo_y_equivalentes_al_efectivo_al_principio_del_periodo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9506 - EFECTIVO Y EQUIVALENTES AL EFECTIVO AL PRINCIPIO DEL PERIODO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9507_efectivo_y_equivalentes_al_efectivo_al_final_del_periodo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9507 - EFECTIVO Y EQUIVALENTES AL EFECTIVO AL FINAL DEL PERIODO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95_incremento_neto_disminucion_en_el_efectivo_y_equivalentes_al_efectivo_antes_del_efecto_de_los_cambios_en_la_tasa_de_cambio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95 - INCREMENTO NETO (DISMINUCIÓN) EN EL EFECTIVO Y EQUIVALENTES AL EFECTIVO, ANTES DEL EFECTO DE LOS CAMBIOS EN LA TASA DE CAMBIO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_96_ganancia_perdida_antes_de_15_a_trabajadores_e_impuesto_a_la_renta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 96 - GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES E IMPUESTO A LA RENTA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9701_ajustes_por_gasto_de_depreciacion_y_amortizacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9701 - Ajustes por gasto de depreciación y amortización', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9702_ajustes_por_gastos_por_deterioro_reversiones_por_deterioro_reconocidas_en_los_resultados_del_periodo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9702 - Ajustes por gastos por deterioro (reversiones por deterioro) reconocidas en los resultados del periodo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9703_perdida_ganancia_de_moneda_extranjera_no_realizada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9703 - Pérdida (ganancia) de moneda extranjera no realizada', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9704_perdidas_en_cambio_de_moneda_extranjera',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9704 - Pérdidas en cambio de moneda extranjera', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9705_ajustes_por_gastos_en_provisiones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9705 - Ajustes por gastos en provisiones', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9706_ajuste_por_participaciones_no_controladoras',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9706 - Ajuste por participaciones no controladoras', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9707_ajuste_por_pagos_basados_en_acciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9707 - Ajuste por pagos basados en acciones', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9708_ajustes_por_ganancias_perdidas_en_valor_razonable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9708 - Ajustes por ganancias (pérdidas) en valor razonable', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9709_ajustes_por_gasto_por_impuesto_a_la_renta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9709 - Ajustes por gasto por impuesto a la renta', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9710_ajustes_por_gasto_por_participacion_trabajadores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9710 - Ajustes por gasto por participación trabajadores', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9711_otros_ajustes_por_partidas_distintas_al_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9711 - Otros ajustes por partidas distintas al efectivo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_97_ajuste_por_partidas_distintas_al_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 97 - AJUSTE POR PARTIDAS DISTINTAS AL EFECTIVO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9801_incremento_disminucion_en_cuentas_por_cobrar_clientes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9801 - (Incremento) disminución en cuentas por cobrar clientes', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9802_incremento_disminucion_en_otras_cuentas_por_cobrar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9802 - (Incremento) disminución en otras cuentas por cobrar', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9803_incremento_disminucion_en_anticipos_de_proveedores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9803 - (Incremento) disminución en anticipos de proveedores', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9804_incremento_disminucion_en_inventarios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9804 - (Incremento) disminución en inventarios', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9805_incremento_disminucion_en_otros_activos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9805 - (Incremento) disminución en otros activos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9806_incremento_disminucion_en_cuentas_por_pagar_comerciales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9806 - Incremento  (disminución) en cuentas por pagar comerciales', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9807_incremento_disminucion_en_otras_cuentas_por_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9807 - Incremento  (disminución) en otras cuentas por pagar', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9808_incremento_disminucion_en_beneficios_empleados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9808 - Incremento  (disminución) en beneficios empleados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9809_incremento_disminucion_en_anticipos_de_clientes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9809 - Incremento  (disminución) en anticipos de clientes', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9810_incremento_disminucion_en_otros_pasivos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9810 - Incremento  (disminución) en otros pasivos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9820_flujos_de_efectivo_netos_procedentes_de_utilizados_en_actividades_de_operacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9820 - Flujos de efectivo netos procedentes de (utilizados en) actividades de operación', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_98_cambios_en_activos_y_pasivos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 98 - CAMBIOS EN ACTIVOS Y PASIVOS', max_digits=20, null=True),
        ),
    ]
