# Generated by Django 4.2.23 on 2026-02-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0027_nomina_recibe_vacaciones_nomina_vacaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='cedula_empleado',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='numero_contrato',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='tipo_contrato',
        ),
        migrations.AddField(
            model_name='nomina',
            name='contrato',
            field=models.ForeignKey(blank=True, help_text='Contrato del trabajador asociado a esta nómina.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='smartbusinesslaw.contratolaboral', unique=True, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='vacaciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional de vacaciones (15 días de sueldo base). 0 si no aplica.', max_digits=10, null=True, verbose_name='Vacaciones'),
        ),
    ]
