# Generated by Django 4.2.23 on 2026-04-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0031_scvsfinancialreport_c_990101_301_saldo_del_periodo_inmediato_anterior_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='direccion',
            field=models.CharField(blank=True, help_text='Calle principal e interseción,Numeracion, referencia', max_length=255, null=True, verbose_name='Dirección Administrativa'),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='fecha_incripcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inscripción'),
        ),
    ]
