# Generated by Django 4.2.23 on 2026-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0033_alter_scvsfinancialreport_economic_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Escriba el monto total suscrito', max_digits=20, null=True),
        ),
    ]
