# Generated by Django 4.2.23 on 2026-04-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0034_scvsfinancialreport_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitario por acciones', max_digits=20, null=True),
        ),
    ]
