# Generated by Django 4.2.23 on 2026-04-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0035_scvsfinancialreport_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scvsfinancialreport',
            name='economic_activity',
            field=models.TextField(blank=True, help_text='Código CIIU (Clasificación Internacional Industrial Uniforme) de la actividad económica principal de la empresa.', max_length=2000, null=True, verbose_name='Actividad económica'),
        ),
    ]
