# Generated by Django 4.2.23 on 2026-04-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0036_alter_scvsfinancialreport_economic_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='matricula_contador',
            field=models.CharField(blank=True, help_text='Matrícula de contador', max_length=255, null=True, verbose_name='Numero de matricula'),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='nombre_contador',
            field=models.CharField(blank=True, help_text='Nombre de contador responsable.', max_length=255, null=True, verbose_name='Contador'),
        ),
    ]
