# Generated by Django 4.2.23 on 2026-04-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0037_scvsfinancialreport_matricula_contador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1010201_activos_financieros_a_valor_razonable_con_cambios_en_resultados',
            new_name='c_1010201_activos_financieros',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1010202_activos_financieros_a_valor_razonable_con_cambios_en_otro_resultado_integral',
            new_name='c_1010202_activos_financieros',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_101020403_activos_financieros_a_valor_razonable_con_cambios_en_otro_resultado_integral',
            new_name='c_101020403_activos_financieros',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_10102050208_por_administracion_y_manejo_de_portafolios_de_terceros',
            new_name='c_10102050208_por_administracion',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_10102050209_por_administracion_y_manejo_de_fondos_administrados',
            new_name='c_10102050209_por_administracion',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_10102050210_por_administracion_y_manejo_de_negocios_fiduciarios',
            new_name='c_10102050210_por_administracion',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_10102050211_por_custodia_y_conservacion_de_valores_materializados',
            new_name='c_10102050211_por_custodia',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_10102050212_por_custodia_y_conservacion_de_valores_desmaterializados',
            new_name='c_10102050212_por_custodia',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1010205_deudores_comerciales_y_otras_cuentas_por_cobrar_no_relacionados',
            new_name='c_1010205_deudores_comerciales',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1010303_inventarios_de_suministros_o_materiales_a_ser_consumidos_en_el_proceso_de_produccion',
            new_name='c_1010303_inventarios',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1010304_inventarios_de_suministros_o_materiales_a_ser_consumidos_en_la_prestacion_del_servicio',
            new_name='c_1010304_inventarios_de_suministros',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1010305_inventarios_de_prod_term_y_mercad_en_almacen_producido_por_la_compania',
            new_name='c_1010305_inventarios',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1010306_inventarios_de_prod_term_y_mercad_en_almacen_comprado_a_terceros',
            new_name='c_1010306_inventarios',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1010313_provision_por_valor_neto_de_realizacion_y_otras_perdidas_en_inventario',
            new_name='c_1010313_provision',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_10106_activos_corrientes_mantenidos_para_la_venta_y_operaciones_discontinuadas',
            new_name='c_10106_activos_corrientes',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1020109_vehiculos_equipos_de_trasporte_y_equipo_caminero_movil',
            new_name='c_1020109_vehiculos',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_102011402_amortizacion_acumulada_de_activos_de_exploracion_y_explotacion',
            new_name='c_102011402_amortizacion',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_102011403_deterioro_acumulado_de_activos_de_exploracion_y_explotacion',
            new_name='c_102011403_deterioro_acumulado',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1020402_marcas_patentes_derechos_de_llave_cuotas_patrimoniales_y_otros_similares',
            new_name='c_1020402_marcas_patentes',
        ),
        migrations.RenameField(
            model_name='scvsfinancialreport',
            old_name='c_1020601_activos_financieros_a_valor_razonable_con_cambios_en_otro_resultado_integral',
            new_name='c_1020601_activos_financieros',
        ),
    ]
