# Generated by Django 4.2.23 on 2026-04-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0040_remove_scvsfinancialreport_c_40101_venta_de_bienes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401 - INGRESOS DE ACTIVIDADES ORDINARIAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40101 - VENTA DE BIENES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40102',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40102 - PRESTACION DE SERVICIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010201',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010201 - INGRESOS POR ASESORÍA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010202',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010202 - INGRESOS POR ESTRUCTURACIÓN DE OFERTA PÚBLICA DE VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010203',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010203 - INGRESOS POR ESTRUCTURACIÓN DE NEGOCIOS FIDUCIARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010204',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010204 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40103',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40103 - CONTRATOS DE CONSTRUCCION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40104',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40104 - SUBVENCIONES DEL GOBIERNO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40105',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40105 - REGALÍAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40106',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40106 - INTERESES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010601',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010601 - INTERESES GENERADOS POR VENTAS A CREDITO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010602',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010602 - INTERESES Y RENDIMIENTOS FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010603',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010603 - OTROS INTERESES GENERADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40107',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40107 - DIVIDENDOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40108',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40108 - GANANCIA POR MEDICION A VALOR RAZONABLE  DE ACTIVOS BIOLOGICOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40109',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40109 - INGRESOS POR COMISIONES, PRESTACIÓN DE SERVICIOS, CUSTODIA, REGISTRO, COMPENSACIÓN Y LIQUIDACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010901',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010901 - COMISIONES GANADAS POR INTERMEDIACIÓN DE VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090101 - POR OPERACIONES BURSATILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090103',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090103 - POR CONTRATOS DE UNDERWRITING', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090104',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090104 - POR COMISIÓN EN OPERACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090105',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090105 - POR INSCRIPCIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090106',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090106 - POR MANTENIMIENTO DE INSCRIPCIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010902',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010902 - POR PRESTACIÓN DE SERVICIOS DE ADMINISTRACIÓN Y MANEJO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090201',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090201 - PORTAFOLIO DE TERCEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090202',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090202 - FONDOS ADMINISTRADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090203',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090203 - FONDOS COLECTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090204',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090204 - TITULARIZACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090205',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090205 - FIDEICOMISOS MERCANTILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090206',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090206 - ENCARGOS FIDUCIARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090207',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090207 - POR CALIFICACION DE RIESGO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090208',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090208 - POR REPRESENTACION DE OBLIGACIONISTAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4010903',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4010903 - CUSTODIA, REGISTRO, COMPENSACIÓN Y LIQUIDACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090301',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090301 - CUSTODIA VALORES MATERIALIZADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090302',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090302 - CUSTODIA VALORES DESMATERIALIZADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090303',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090303 - COMPENSACIÓN Y LIQUIDACIÓN DE VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_401090304',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 401090304 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40110',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40110 - INGRESOS  FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011001',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011001 - DIVIDENDOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011002',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011002 - INTERESES FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011003',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011003 - GANANCIA EN INVERSIONES EN ASOCIADAS / SUBSIDIARIAS Y OTRAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011004',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011004 - VALUACION DE INSTRUMENTOS FINANCIEROS A VALOR RAZONABLE CON CAMBIO EN RESULTADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011005',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011005 - GANANCIA EN VENTA DE TITULOS VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_4011006',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 4011006 - OTROS INGRESOS  FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40112',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40112 - (-) DESCUENTO EN VENTAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40113',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40113 - (-) DEVOLUCIONES EN VENTAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40114',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40114 - (-) BONIFICACIÓN EN PRODUCTO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40115',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40115 - (-) OTRAS REBAJAS COMERCIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40116',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40116 - UTILIDAD EN CAMBIO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_402',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 402 - GANANCIA BRUTA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_403',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 403 - OTROS INGRESOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40301',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40301 - GANANCIA EN VENTA DE PROPIEDAD, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40302',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40302 - GANANCIA EN VENTA DE ACTIVOS BIOLÓGICOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_40303',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 40303 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_501',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 501 - COSTO DE VENTAS Y PRODUCCIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50101 - MATERIALES UTILIZADOS O PRODUCTOS VENDIDOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010101 - (+) INVENTARIO INICIAL DE BIENES NO PRODUCIDOS POR LA COMPAÑIA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010102',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010102 - (+) COMPRAS NETAS LOCALES DE BIENES NO PRODUCIDOS POR LA COMPAÑIA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010103',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010103 - (+) IMPORTACIONES DE BIENES NO PRODUCIDOS POR LA COMPAÑIA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010104',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010104 - (-) INVENTARIO FINAL DE BIENES NO PRODUCIDOS POR LA COMPAÑIA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010105',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010105 - (+) INVENTARIO INICIAL DE MATERIA PRIMA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010106',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010106 - (+) COMPRAS NETAS LOCALES DE MATERIA PRIMA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010107',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010107 - (+) IMPORTACIONES DE MATERIA PRIMA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010108',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010108 - (-) INVENTARIO FINAL DE MATERIA PRIMA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010109',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010109 - (+) INVENTARIO INICIAL DE PRODUCTOS EN PROCESO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010110',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010110 - (-) INVENTARIO FINAL DE PRODUCTOS EN PROCESO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010111',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010111 - (+) INVENTARIO INICIAL PRODUCTOS TERMINADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010112',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010112 - (-) INVENTARIO FINAL DE PRODUCTOS TERMINADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50102',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50102 - (+) MANO DE OBRA DIRECTA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010201',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010201 - SUELDOS Y BENEFICIOS SOCIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010202',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010202 - GASTOS PLANES DE BENEFICIOS A EMPLEADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50103',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50103 - (+) MANO DE OBRA INDIRECTA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010301',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010301 - SUELDOS Y BENEFICIOS SOCIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010302',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010302 - GASTO PLANES DE BENEFICIOS A EMPLEADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50104',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50104 - (+) OTROS COSTOS INDIRECTOS DE FABRICACION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010401',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010401 - DEPRECIACIÓN PROPIEDADES, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010402',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010402 - DETERIORO O PERDIDAS DE ACTIVOS BIOLOGICOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010403',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010403 - DETERIORO DE PROPIEDAD, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010404',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010404 - EFECTO VALOR NETO DE REALIZACION DE INVENTARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010405',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010405 - GASTO POR GARANTIAS EN VENTA DE PRODUCTOS O SERVICIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010406',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010406 - MANTENIMIENTO Y REPARACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010407',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010407 - SUMINISTROS MATERIALES Y REPUESTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010408',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010408 - OTROS COSTOS DE PRODUCCIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50105',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50105 - COSTOS DE CONTRATOS DE CONSTRUCCIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5010501',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5010501 - COSTOS DE ACUERDO A PORCENTAJES O GRADOS DE TERMINACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502 - GASTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50201',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50201 - GASTOS DE VENTA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020101 - SUELDOS, SALARIOS Y DEMÁS REMUNERACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020102',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020102 - APORTES A LA SEGURIDAD SOCIAL (INCLUIDO FONDO DE RESERVA)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020103',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020103 - BENEFICIOS SOCIALES E INDEMNIZACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020104',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020104 - GASTO PLANES DE BENEFICIOS A EMPLEADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020105',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020105 - HONORARIOS, COMISIONES Y DIETAS A PERSONAS NATURALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020106',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020106 - REMUNERACIONES A OTROS TRABAJADORES AUTÓNOMOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020107',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020107 - HONORARIOS A EXTRANJEROS POR SERVICIOS OCASIONALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020108',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020108 - MANTENIMIENTO Y REPARACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020109',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020109 - ARRENDAMIENTO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020110',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020110 - COMISIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020111',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020111 - PROMOCIÓN Y PUBLICIDAD', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020112',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020112 - COMBUSTIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020113',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020113 - LUBRICANTES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020114',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020114 - SEGUROS Y REASEGUROS (PRIMAS Y CESIONES)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020115',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020115 - TRANSPORTE', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020116',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020116 - GASTOS DE GESTIÓN (AGASAJOS A ACCIONISTAS, TRABAJADORES Y CLIENTES)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020117',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020117 - GASTOS DE VIAJE', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020118',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020118 - AGUA, ENERGÍA, LUZ, Y TELECOMUNICACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020119',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020119 - NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MERCANTILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020120',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020120 - DEPRECIACIONES:', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012001',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012001 - PROPIEDADES, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012002',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012002 - PROPIEDADES DE INVERSIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012003',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012003 - ACTIVOS POR DERECHO DE USO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020121',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020121 - AMORTIZACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012101 - INTANGIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012102',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012102 - OTROS ACTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020122',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020122 - GASTO DETERIORO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012201',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012201 - PROPIEDADES, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012202',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012202 - INVENTARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012203',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012203 - INSTRUMENTOS FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012204',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012204 - INTANGIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012205',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012205 - CUENTAS POR COBRAR', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012206',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012206 - OTROS ACTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012207',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012207 - DERECHOS DE USO POR ACTIVOS ARRENDADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020123',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020123 - GASTOS POR CANTIDADES ANORMALES DE UTILIZACION EN EL PROCESO DE PRODUCCIÓN:', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012301',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012301 - MANO DE OBRA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012302',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012302 - MATERIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502012303',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502012303 - COSTOS DE PRODUCCION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020124',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020124 - GASTO POR REESTRUCTURACION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020125',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020125 - VALOR NETO DE REALIZACION DE INVENTARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020126',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020126 - GASTO IMPUESTO A LA RENTA (ACTIVOS Y PASIVOS DIFERIDOS)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020127',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020127 - SUMINISTROS Y MATERIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020128',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020128 - OTROS GASTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50202',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50202 - GASTOS ADMINISTRATIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020201',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020201 - SUELDOS, SALARIOS Y DEMÁS REMUNERACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020202',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020202 - APORTES A LA SEGURIDAD SOCIAL (INCLUIDO FONDO DE RESERVA)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020203',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020203 - BENEFICIOS SOCIALES E INDEMNIZACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020204',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020204 - GASTO PLANES DE BENEFICIOS A EMPLEADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020205',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020205 - HONORARIOS, COMISIONES Y DIETAS A PERSONAS NATURALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020206',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020206 - REMUNERACIONES A OTROS TRABAJADORES AUTÓNOMOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020207',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020207 - HONORARIOS A EXTRANJEROS POR SERVICIOS OCASIONALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020208',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020208 - MANTENIMIENTO Y REPARACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020209',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020209 - ARRENDAMIENTO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020210',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020210 - COMISIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020211',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020211 - PROMOCIÓN Y PUBLICIDAD', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020212',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020212 - COMBUSTIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020213',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020213 - LUBRICANTES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020214',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020214 - SEGUROS Y REASEGUROS (PRIMAS Y CESIONES)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020215',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020215 - TRANSPORTE', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020216',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020216 - GASTOS DE GESTIÓN (AGASAJOS A ACCIONISTAS, TRABAJADORES Y CLIENTES)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020217',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020217 - GASTOS DE VIAJE', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020218',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020218 - AGUA, ENERGÍA, LUZ, Y TELECOMUNICACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020219',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020219 - NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MERCANTILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020220',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020220 - IMPUESTOS, CONTRIBUCIONES Y OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020221',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020221 - DEPRECIACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022101 - PROPIEDADES, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022102',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022102 - PROPIEDADES DE INVERSIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022103',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022103 - ACTIVOS POR DERECHO DE USO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020222',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020222 - AMORTIZACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022201',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022201 - INTANGIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022202',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022202 - OTROS ACTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020223',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020223 - GASTO DETERIORO:', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022301',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022301 - PROPIEDADES, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022302',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022302 - INVENTARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022303',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022303 - INSTRUMENTOS FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022304',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022304 - INTANGIBLES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022305',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022305 - CUENTAS POR COBRAR', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022306',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022306 - OTROS ACTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022307',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022307 - DERECHOS DE USO POR ACTIVOS ARRENDADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020224',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020224 - GASTOS POR CANTIDADES ANORMALES DE UTILIZACION EN EL PROCESO DE PRODUCCIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022401',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022401 - MANO DE OBRA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022402',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022402 - MATERIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502022403',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502022403 - COSTOS DE PRODUCCION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020225',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020225 - GASTO POR REESTRUCTURACION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020226',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020226 - VALOR NETO DE REALIZACION DE INVENTARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020227',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020227 - GASTO IMPUESTO A LA RENTA (ACTIVOS Y PASIVOS DIFERIDOS)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020228',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020228 - SUMINISTROS Y MATERIALES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020229',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020229 - OTROS GASTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203 - GASTOS FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020301',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020301 - INTERESES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030101 - INTERESES POR PRESTAMOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030102',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030102 - INTERESES POR ARRENDAMIENTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030103',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030103 - INTERESES POR VALORES EMITIDOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030104',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030104 - OTROS INTERESES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020302',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020302 - COMISIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030201',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030201 - COMISIONES PAGADAS POR INTERMEDIACIÓN DE VALORES:', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203020101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203020101 - POR OPERACIONES BURSATILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203020103',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203020103 - POR CONTRATOS DE UNDERWRITING', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203020104',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203020104 - POR COMISIÓN EN OPERACIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203020105',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203020105 - POR INSCRIPCIONES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50203020106',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50203020106 - POR MANTENIMIENTO DE INSCRIPCIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020303',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020303 - POR PRESTACIÓN DE SERVICIOS DE ADMINISTRACIÓN Y MANEJO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030301',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030301 - PORTAFOLIO DE TERCEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030302',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030302 - FONDOS ADMINISTRADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030303',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030303 - FONDOS COLECTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030304',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030304 - TITULARIZACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030305',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030305 - FIDEICOMISOS MERCANTILES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030306',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030306 - ENCARGOS FIDUCIARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030307',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030307 - POR CALIFICACION DE RIESGO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030308',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030308 - POR REPRESENTACION DE OBLIGACIONISTAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020304',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020304 - CUSTODIA, REGISTRO, COMPENSACIÓN Y LIQUIDACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030401',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030401 - CUSTODIA VALORES MATERIALIZADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030402',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030402 - CUSTODIA VALORES DESMATERIALIZADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030403',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030403 - COMPENSACIÓN Y LIQUIDACIÓN DE VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030404',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030404 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020305',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020305 - GASTOS POR SERVICIOS DE ASESORIA Y ESTRUCTURACION', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030501',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030501 - POR ASESORÍA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030502',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030502 - POR ESTRUCTURACIÓN DE OFERTA PÚBLICA DE VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030503',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030503 - POR ESTRUCTURACIÓN DE NEGOCIOS FIDUCIARIOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_502030504',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 502030504 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020306',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020306 - GASTOS DE FINANCIAMIENTO DE ACTIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020307',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020307 - DIFERENCIA EN CAMBIO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020308',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020308 - VALUACION DE INSTRUMENTOS FINANCIEROS A VALOR RAZONABLE CON CAMBIO EN RESULTADOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020309',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020309 - PERDIDA EN VENTA DE TITULOS VALORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020310',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020310 - PERDIDA EN VENTA DE PROPIEDAD, PLANTA Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020311',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020311 - PERDIDA EN VENTA DE ACTIVOS BIOLOGICOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020312',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020312 - OTROS GASTOS FINANCIEROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_50204',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 50204 - OTROS GASTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020401',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020401 - PERDIDA EN INVERSIONES EN ASOCIADAS / SUBSIDIARIAS Y OTRAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_5020402',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 5020402 - OTROS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_600',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 600 - GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES E IMPUESTO A LA RENTA DE OPERACIONES CONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_601',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 601 - 15% PARTICIPACIÓN TRABAJADORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_602',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 602 - GANANCIA (PÉRDIDA) ANTES DE IMPUESTOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_603',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 603 - IMPUESTO A LA RENTA CAUSADO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_604',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 604 - GANANCIA (PÉRDIDA) DE OPERACIONES CONTINUADAS ANTES DEL IMPUESTO DIFERIDO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_605',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 605 - (-) GASTO POR IMPUESTO DIFERIDO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_606',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 606 - (+) INGRESO POR IMPUESTO DIFERIDO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_607',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 607 - GANANCIA (PERDIDA) DE OPERACIONES CONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_700',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 700 - INGRESOS POR OPERACIONES DISCONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_701',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 701 - GASTOS POR OPERACIONES DISCONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_702',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 702 - GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES E IMPUESTO A LA RENTA DE OPERACIONES DISCONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_703',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 703 - 15% PARTICIPACIÓN TRABAJADORES', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_704',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 704 - GANANCIA (PÉRDIDA) ANTES DE IMPUESTOS DE OPERACIONES DISCONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_705',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 705 - IMPUESTO A LA RENTA CAUSADO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_706',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 706 - GANANCIA (PÉRDIDA) DE OPERACIONES DISCONTINUADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_707',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 707 - GANANCIA (PÉRDIDA) NETA DEL PERIODO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_800',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 800 - OTRO RESULTADO INTEGRAL', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80001',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80001 - COMPONENTES DEL OTRO RESULTADO INTEGRAL', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80002',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80002 - DIFERENCIA DE CAMBIO POR CONVERSIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80003',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80003 - VALUACIÓN DE ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIO EN OTRO RESULTADO INTEGRAL', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80004',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80004 - GANANCIAS POR REVALUACIÓN DE PROPIEDADES, PLANTA  Y EQUIPO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80005',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80005 - GANANCIAS (PÉRDIDAS) ACTUARIALES POR PLANES DE BENEFICIOS DEFINIDOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80006',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80006 - REVERSION DEL DETERIORO (PÉRDIDA POR DETERIORO) DE UN ACTIVO REVALUADO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80007',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80007 - PARTICIPACION DE OTRO RESULTADO INTEGRAL DE ASOCIADAS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80008',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80008 - IMPUESTO SOBRE LAS GANANCIAS RELATIVO A OTRO RESULTADO INTEGRAL', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80009',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80009 - OTROS (DETALLAR EN NOTAS)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_801',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 801 - RESULTADO INTEGRAL TOTAL DEL AÑO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80101 - PROPIETARIOS DE LA CONTROLADORA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_80102',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 80102 - PARTICIPACION NO CONTROLADORA (INFORMATIVO)', max_digits=20, null=True),
        ),
    ]
