# Generated by Django 4.2.23 on 2026-04-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbusinesslaw', '0041_scvsfinancialreport_c_401_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95 - INCREMENTO NETO (DISMINUCIÓN) EN EL EFECTIVO Y EQUIVALENTES AL EFECTIVO, ANTES DEL EFECTO DE LOS CAMBIOS EN LA TASA DE CAMBIO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9501',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9501 - FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE OPERACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950101 - Clases de cobros por actividades de operación', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010101',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010101 - Cobros procedentes de las ventas de bienes y prestación de servicios', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010102',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010102 - Cobros procedentes de regalías, cuotas, comisiones y otros ingresos de actividades ordinarias', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010103',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010103 - Cobros procedentes de contratos mantenidos con propósitos de intermediación o para negociar', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010104',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010104 - Cobros procedentes de primas y prestaciones, anualidades y otros beneficios de pólizas suscritas', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010105',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010105 - Otros cobros por actividades de operación', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950102',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950102 - Clases de pagos por actividades de operación', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010201',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010201 - Pagos a proveedores por el suministro de bienes y servicios', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010202',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010202 - Pagos procedentes de contratos mantenidos para intermediación o para negociar', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010203',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010203 - Pagos a y por cuenta de los empleados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010204',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010204 - Pagos por primas y prestaciones, anualidades y otras obligaciones derivadas de las pólizas suscritas', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_95010205',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 95010205 - Otros pagos por actividades de operación', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950103',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950103 - Dividendos pagados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950104',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950104 - Dividendos recibidos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950105',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950105 - Intereses pagados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950106',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950106 - Intereses recibidos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950107',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950107 - Impuestos a las ganancias pagados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950108',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950108 - Otras entradas (salidas) de efectivo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9502',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9502 - FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE INVERSIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950201',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950201 - Efectivo procedentes de la venta de acciones en subsidiarias u otros negocios', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950202',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950202 - Efectivo utilizado para adquirir acciones en subsidiarias u otros negocios para tener el control', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950203',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950203 - Efectivo utilizado en la compra de participaciones no controladoras', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950204',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950204 - Otros cobros por la venta de acciones o instrumentos de deuda de otras entidades', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950205',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950205 - Otros pagos para adquirir acciones o instrumentos de deuda de otras entidades', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950206',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950206 - Otros cobros por la venta de participaciones en negocios conjuntos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950207',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950207 - Otros pagos para adquirir participaciones en negocios conjuntos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950208',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950208 - Importes procedentes por la venta de propiedades, planta y equipo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950209',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950209 - Adquisiciones de propiedades, planta y equipo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950210',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950210 - Importes procedentes de ventas de activos intangibles', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950211',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950211 - Compras de activos intangibles', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950212',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950212 - Importes procedentes de otros activos a largo plazo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950213',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950213 - Compras de otros activos a largo plazo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950214',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950214 - Importes procedentes de subvenciones del gobierno', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950215',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950215 - Anticipos de efectivo efectuados a terceros', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950216',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950216 - Cobros procedentes del reembolso de anticipos y préstamos concedidos a terceros', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950217',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950217 - Pagos derivados de contratos de futuro, a término, de opciones y de permuta financiera', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950218',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950218 - Cobros procedentes de contratos de futuro, a término, de opciones y de permuta financiera', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950219',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950219 - Dividendos recibidos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950220',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950220 - Intereses recibidos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950221',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950221 - Otras entradas (salidas) de efectivo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9503',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9503 - FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE FINANCIACIÓN', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950301',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950301 - Aporte en efectivo por aumento de capital', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950302',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950302 - Financiamiento por emisión de títulos valores', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950303',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950303 - Pagos por adquirir o rescatar las acciones de la entidad', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950304',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950304 - Financiación por préstamos a largo plazo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950305',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950305 - Pagos de préstamos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950306',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950306 - Pagos de pasivos por arrendamientos financieros', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950307',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950307 - Importes procedentes de subvenciones del gobierno', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950308',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950308 - Dividendos pagados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950309',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950309 - Intereses recibidos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950310',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950310 - Otras entradas (salidas) de efectivo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9504',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9504 - EFECTOS DE LA VARIACION EN LA TASA DE CAMBIO SOBRE EL EFECTIVO Y EQUIVALENTES AL EFECTIVO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_950401',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 950401 - Efectos de la variación en la tasa de cambio sobre el efectivo y equivalentes al efectivo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9505',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9505 - INCREMENTO (DISMINUCIÓN) NETO DE EFECTIVO Y EQUIVALENTES AL EFECTIVO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9506',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9506 - EFECTIVO Y EQUIVALENTES AL EFECTIVO AL PRINCIPIO DEL PERIODO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9507',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9507 - EFECTIVO Y EQUIVALENTES AL EFECTIVO AL FINAL DEL PERIODO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_96',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 96 - GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES E IMPUESTO A LA RENTA', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_97',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 97 - AJUSTE POR PARTIDAS DISTINTAS AL EFECTIVO', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9701',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9701 - Ajustes por gasto de depreciación y amortización', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9702',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9702 - Ajustes por gastos por deterioro (reversiones por deterioro) reconocidas en los resultados del periodo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9703',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9703 - Pérdida (ganancia) de moneda extranjera no realizada', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9704',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9704 - Pérdidas en cambio de moneda extranjera', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9705',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9705 - Ajustes por gastos en provisiones', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9706',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9706 - Ajuste por participaciones no controladoras', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9707',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9707 - Ajuste por pagos basados en acciones', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9708',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9708 - Ajustes por ganancias (pérdidas) en valor razonable', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9709',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9709 - Ajustes por gasto por impuesto a la renta', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9710',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9710 - Ajustes por gasto por participación trabajadores', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9711',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9711 - Otros ajustes por partidas distintas al efectivo', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_98',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 98 - CAMBIOS EN ACTIVOS Y PASIVOS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9801',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9801 - (Incremento) disminución en cuentas por cobrar clientes', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9802',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9802 - (Incremento) disminución en otras cuentas por cobrar', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9803',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9803 - (Incremento) disminución en anticipos de proveedores', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9804',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9804 - (Incremento) disminución en inventarios', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9805',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9805 - (Incremento) disminución en otros activos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9806',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9806 - Incremento  (disminución) en cuentas por pagar comerciales', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9807',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9807 - Incremento  (disminución) en otras cuentas por pagar', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9808',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9808 - Incremento  (disminución) en beneficios empleados', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9809',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9809 - Incremento  (disminución) en anticipos de clientes', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9810',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9810 - Incremento  (disminución) en otros pasivos', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='scvsfinancialreport',
            name='c_9820',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Código 9820 - Flujos de efectivo netos procedentes de (utilizados en) actividades de operación', max_digits=20, null=True),
        ),
    ]
