# Generated by Django 4.2.23 on 2025-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('desired_date', models.DateTimeField(blank=True, null=True)),
                ('step', models.IntegerField(default=1)),
            ],
        ),
    ]
