# Generated by Django 4.2.20 on 2025-08-05 04:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sbmshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('project_name', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=50, null=True)),
                ('RUC', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono')),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expire', models.DateTimeField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('braintree_id', models.CharField(blank=True, max_length=150)),
                ('iva', models.PositiveSmallIntegerField(default=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Tarjeta de Crédito'), ('bank_transfer', 'Transferencia Bancaria'), ('paypal', 'PayPal'), ('amazon_pay', 'Amazon Pay')], max_length=500, null=True)),
                ('accept_terms_and_conditions', models.BooleanField(default=False, verbose_name='Acepta los términos y condiciones del contrato')),
                ('product_category', models.ForeignKey(blank=True, help_text='Número de usuarios en su Negocio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_items', to='sbmshop.category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sbmshop.category')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sbmorders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='sbmshop.sbmproduct')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('banco_pichincha', 'Banco de Pichincha'), ('produbanco', 'Banco Produbanco'), ('banco_internacional', 'Banco Internacional'), ('banco_guayaquil', 'Banco de Guayaquil'), ('banco_bolivariano', 'Banco Bolivariano'), ('banco_del_achira', 'Banco del Austro'), ('banco_de_los_andes', 'Banco de los Andes'), ('banco_comercial', 'Banco Comercial'), ('banco_territorial', 'Banco Territorial'), ('banco_nacional_de_fomento', 'Banco Nacional de Fomento'), ('banco_pacifico', 'Banco Pacífico'), ('banco_procredit', 'Banco ProCredit'), ('banco_machala', 'Banco de Machala'), ('banco_de_la_produccion', 'Banco de la Producción'), ('banco_davivienda', 'Banco Davivienda Ecuador'), ('banco_de_guayaquil_vision', 'Banco de Guayaquil Visión'), ('banco_union', 'Banco Unión'), ('banco_solidario', 'Banco Solidario'), ('banco_mercantil', 'Banco Mercantil'), ('banco_rural', 'Banco Rural'), ('banco_suramericano', 'Banco Suramericano')], max_length=500)),
                ('bank_id', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bank Transaction ID')),
                ('transfer_date', models.DateField(auto_now=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado de pago')),
                ('accept_terms_and_conditions', models.BooleanField(default=False, verbose_name='Acepta los términos y condiciones del contrato')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sbmorders.order')),
            ],
        ),
    ]
