# Generated by Django 4.2.23 on 2025-08-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='TS_info4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo-4 info'),
        ),
        migrations.AlterField(
            model_name='home',
            name='TS_info5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo-5 info'),
        ),
        migrations.AlterField(
            model_name='home',
            name='TS_info6',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo-6 info'),
        ),
        migrations.AlterField(
            model_name='home',
            name='info4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Info-4'),
        ),
        migrations.AlterField(
            model_name='home',
            name='info5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Info-5'),
        ),
        migrations.AlterField(
            model_name='home',
            name='info6',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Info-6'),
        ),
    ]
