# Generated by Django 4.2.23 on 2026-02-20 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='image_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 2'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 4'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='image_2_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 3'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='image_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 6'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='image_3_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 5'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='image_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 8'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='image_4_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 7'),
        ),
    ]
