# Generated by Django 4.2.23 on 2025-10-28 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriahome',
            name='image_9_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 100'),
        ),
        migrations.AddField(
            model_name='home',
            name='TS_info7',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo-7 info'),
        ),
    ]
