# Generated by Django 4.2.20 on 2025-08-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriahome',
            options={'ordering': ['sort_order']},
        ),
    ]
