# Generated by Django 4.2.20 on 2025-08-06 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_galeriahome_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeriahome',
            old_name='image',
            new_name='image_1',
        ),
    ]
