# Generated by Django 4.2.23 on 2026-02-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_formsubmission'),
        ('webapp', '0002_alter_galeriadeimagenes_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAutomationPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('prompt', models.TextField()),
                ('brand_voice', models.CharField(blank=True, max_length=255)),
                ('target_platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('both', 'Ambos')], default='both', max_length=50)),
                ('generated_caption', models.TextField(blank=True)),
                ('generated_image_url', models.URLField(blank=True)),
                ('meta_post_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('scheduled', 'Programado en Meta'), ('published', 'Publicado'), ('error', 'Error')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
