# Generated by Django 4.2.23 on 2025-08-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_home_ts_info4_alter_home_ts_info5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='info7',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='IT Business Analytics'),
        ),
        migrations.AlterField(
            model_name='home',
            name='info8',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='IT Business Cloud DevOps'),
        ),
        migrations.AlterField(
            model_name='home',
            name='info9',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='IT Business Media'),
        ),
    ]
