# Generated by Django 4.2.23 on 2025-08-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_home_info7_alter_home_info8_alter_home_info9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='info7',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='IT Business Analytics'),
        ),
        migrations.AlterField(
            model_name='home',
            name='info8',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='IT Business Cloud DevOps'),
        ),
        migrations.AlterField(
            model_name='home',
            name='info9',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='IT Business Media'),
        ),
    ]
