# Generated by Django 4.2.29 on 2026-06-08 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('webapp', '0003_galeriadeimagenessbt_carousell_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenessbm',
            name='carousell_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell 1'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenessbm',
            name='carousell_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  2'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenessbm',
            name='carousell_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  3'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenessbm',
            name='carousell_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  4'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenessbm',
            name='carousell_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  5'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenessbm',
            name='carousell_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  6'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenessbm',
            name='carousell_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  7'),
        ),
    ]
