# Generated by Django 4.2.23 on 2026-02-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_socialautomationpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialAutomationPost',
        ),
    ]
