# Generated by Django 4.2.20 on 2025-08-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_image_galeriahome_image_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeriahome',
            old_name='image_1',
            new_name='image',
        ),
    ]
