# Generated by Django 4.2.23 on 2026-03-19 20:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.forms.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_formsubmission'),
        ('webapp', '0004_delete_socialautomationpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsFormDetailOpeningPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('jobs_category', models.CharField(blank=True, choices=[('Community Manager Senior', 'Community Manager Senior'), ('Community Manager Junior', 'Community Manager Junior'), ('Content Designer Senior', 'Content Designer Senior'), ('Content Designer Junior', 'Content Designer Junior'), ('Project Manager Senior', 'Project Manager Senior'), ('Project Manager Junior', 'Project Manager Junior'), ('UI/UX Designer Senior', 'UI/UX Designer Senior'), ('UI/UX Designer Junior', 'UI/UX Designer Junior'), ('Django Developer Senior', 'Django Developer Senior'), ('Django Developer Junior', 'Django Developer Junior'), ('Site Reliability Engineer Senior', 'Site Reliability Engineer Senior'), ('Site Reliability Engineer Junior', 'Site Reliability Engineer Junior')], max_length=100, null=True)),
                ('city', models.CharField(blank=True, choices=[('Quito', 'Quito'), ('Guayaquil', 'Guayaquil'), ('Cuenca', 'Cuenca'), ('Buenos Aires', 'Buenos Aires'), ('Mendoza', 'Mendoza'), ('Paris', 'Paris'), ('Lausanne', 'Lausanne'), ('New York', 'New York')], max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('Ecuador', 'Ecuador'), ('Switzerland', 'Switzerland'), ('Argentina', 'Argentina'), ('France', 'France'), ('United States', 'United States')], max_length=100, null=True)),
                ('timejobs', models.CharField(blank=True, choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=100, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descripción corta')),
                ('uploadcv', models.FileField(blank=True, null=True, upload_to='CV_file/%Y/%m/%d')),
                ('comments', wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje para que nos dejen un comentario')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
                ('content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('list', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 5: ('wagtail.blocks.ListBlock', (4,), {})}, null=True)),
                ('uploaded_image_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
    ]
