# Generated by Django 4.2.20 on 2025-08-06 20:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0095_formsubmission'),
        ('webapp', '0004_rename_image_1_galeriahome_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProximamentePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descripcion', wagtail.fields.RichTextField(blank=True, verbose_name='Descripción')),
                ('fecha_lanzamiento', models.DateTimeField(verbose_name='Fecha y hora del lanzamiento')),
                ('enlace_redes', models.URLField(blank=True, null=True, verbose_name='Enlace a redes sociales o sitio temporal')),
                ('imagen_destacada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen destacada')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
