# Generated by Django 4.2.20 on 2025-08-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_proximamentepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='TS_info1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtítulo info'),
        ),
        migrations.AlterField(
            model_name='home',
            name='info1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Info'),
        ),
    ]
