# Generated by Django 4.2.29 on 2026-06-13 02:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        #('wagtailcore', '0097_delete_formsubmission'),
        ('wagtailimages', '0027_image_description'),
        ('webapp', '0005_galeriadeimagenessba_carousell_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='smartbusinessplatforms_info',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('bio2', wagtail.fields.RichTextField(blank=True, verbose_name='Frase relevante primer parrafo')),
                ('bio3', wagtail.fields.RichTextField(blank=True, verbose_name='Frase relevante segundo parrafo')),
                ('author_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de autor')),
                ('business_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo de autor en el negocio')),
                ('business_activiy', models.CharField(blank=True, max_length=150, null=True, verbose_name='Actividad de autor en el negocio')),
                ('business_experience', models.CharField(blank=True, max_length=150, null=True, verbose_name='años de experiencia de autor en el negocio')),
                ('updated', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fecha de ultima actualización')),
                ('banner_title4', wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-1 ')),
                ('TS_info1', models.CharField(blank=True, max_length=150, null=True, verbose_name='project_info')),
                ('TS_info2', models.CharField(blank=True, max_length=150, null=True, verbose_name='project_info2')),
                ('TS_info3', models.CharField(blank=True, max_length=150, null=True, verbose_name='project2_info')),
                ('info3', models.CharField(blank=True, max_length=150, null=True, verbose_name='project2_info2')),
                ('TS_info4', models.CharField(blank=True, max_length=150, null=True, verbose_name='project3_info')),
                ('info4', models.CharField(blank=True, max_length=150, null=True, verbose_name='project3_info2')),
                ('TS_info5', models.CharField(blank=True, max_length=150, null=True, verbose_name='project4_info')),
                ('info5', models.CharField(blank=True, max_length=150, null=True, verbose_name='project4_info2')),
                ('banner_title9', wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo')),
                ('TS_info6', models.CharField(blank=True, max_length=350, null=True, verbose_name='Subtitulo de parrafo')),
                ('info_title9', wagtail.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('banner_title10', wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo-2')),
                ('TS_info7', models.CharField(blank=True, max_length=350, null=True, verbose_name='Subtitulo de parrafo-2')),
                ('info_title10', wagtail.fields.RichTextField(blank=True, verbose_name='Texto-2')),
                ('banner_title11', wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo-3')),
                ('TS_info8', models.CharField(blank=True, max_length=350, null=True, verbose_name='Subtitulo de parrafo-3')),
                ('info_title11', wagtail.fields.RichTextField(blank=True, verbose_name='Texto-3')),
                ('info_title12', wagtail.fields.RichTextField(blank=True, verbose_name='Descripcion de producto')),
                ('banner_title13', wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo-3')),
                ('info_title13', wagtail.fields.RichTextField(blank=True, verbose_name='Descripcion de producto')),
                ('banner_title14', wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo-3')),
                ('info_title14', wagtail.fields.RichTextField(blank=True, verbose_name='Descripcion de producto')),
                ('banner_title15', wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo-3')),
                ('info_title15', wagtail.fields.RichTextField(blank=True, verbose_name='Descripcion de producto')),
                ('link1', wagtail.fields.RichTextField(blank=True, verbose_name='link-para empezar proyecto')),
                ('link2', wagtail.fields.RichTextField(blank=True, verbose_name='link-para contactos')),
                ('banner_title12', wagtail.fields.RichTextField(blank=True, verbose_name='invitacion a contactarnos')),
                ('custom_title', models.CharField(blank=True, help_text='Reescribe el  Titulo de la publicacion ', max_length=100, null=True)),
                ('consulta', wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje para que nos consulten por el formulario')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GlobalLinksSettingsSBP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacus', models.URLField(blank=True, null=True)),
                ('start_project_SBM', models.URLField(blank=True, null=True)),
                ('start_project_SBL', models.URLField(blank=True, null=True)),
                ('start_project_SBA', models.URLField(blank=True, null=True)),
                ('start_project_SBT', models.URLField(blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GaleriadeImagenesSBP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('banner_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Backgound en slide')),
                ('carousell_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell 1')),
                ('carousell_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  2')),
                ('carousell_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  3')),
                ('carousell_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  4')),
                ('carousell_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  5')),
                ('carousell_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  6')),
                ('carousell_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Carousell  7')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1')),
                ('image_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1')),
                ('image_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 2')),
                ('image_2_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1')),
                ('image_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 3')),
                ('image_3_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1')),
                ('image_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 4')),
                ('image_4_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo en texto ')),
                ('logo_slide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo en slide')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria_3', to='webapp.smartbusinessplatforms_info')),
                ('profile_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto de perfil')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
