# Generated by Django 4.2.23 on 2026-03-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_jobsformdetailopeningpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='to_address',
        ),
    ]
