# Generated by Django 4.2.23 on 2025-11-21 16:56

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_info_5_alter_galeriadeimagenes_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_3',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='info_4',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='info_5',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria_3', to='webapp.info'),
        ),
        migrations.DeleteModel(
            name='info_2',
        ),
        migrations.DeleteModel(
            name='info_3',
        ),
        migrations.DeleteModel(
            name='info_4',
        ),
        migrations.DeleteModel(
            name='info_5',
        ),
    ]
