# Generated by Django 4.2.23 on 2026-03-20 18:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('webapp', '0006_remove_jobsformdetailopeningpage_from_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('custom_title', models.CharField(help_text='Nombre', max_length=100)),
                ('porfolio_1', models.CharField(blank=True, choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100, null=True)),
                ('porfolio_2', models.CharField(blank=True, choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100, null=True)),
                ('porfolio_3', models.CharField(blank=True, choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100, null=True)),
                ('porfolio_4', models.CharField(blank=True, choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100, null=True)),
                ('aboutus', wagtail.fields.RichTextField(blank=True, verbose_name='Acerca de mi')),
                ('aboutus_1', wagtail.fields.RichTextField(blank=True, verbose_name='mensaje 1')),
                ('aboutus_2', wagtail.fields.RichTextField(blank=True, verbose_name='mensaje 2')),
                ('aboutus_3', wagtail.fields.RichTextField(blank=True, verbose_name='mensaje 3')),
                ('experience_message', models.CharField(blank=True, help_text='Describir un mensaje de experiencia', max_length=100, null=True)),
                ('educational_message', models.CharField(blank=True, help_text='Describir un mensaje de la educación', max_length=100, null=True)),
                ('comments', wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje para comentarios')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto de perfil')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='PorfolioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('porfolio_title', models.CharField(blank=True, help_text='Título de portfolio', max_length=100, null=True)),
                ('porfolio', models.CharField(blank=True, choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100, null=True)),
                ('image_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='porfolio_items', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperiencePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('business_title', models.CharField(blank=True, help_text='Empresa', max_length=100, null=True)),
                ('business_charge', models.CharField(blank=True, help_text='Cargo', max_length=100, null=True)),
                ('business_activity', models.TextField(blank=True, help_text='Descripción', null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_items', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('academy_title', models.CharField(blank=True, help_text='Institución', max_length=100, null=True)),
                ('title', models.CharField(blank=True, help_text='Título', max_length=100, null=True)),
                ('academy_activity', models.TextField(blank=True, help_text='Descripción', null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_items', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactFormResumePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
