# Generated by Django 4.2.23 on 2026-03-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_resumepage_porfoliopage_experiencepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfoliopage',
            name='porfolio',
            field=models.CharField(blank=True, choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence Engineer', 'Artificial Intelligence Engineer'), ('Site Reliability Engineer (SRE)', 'Site Reliability Engineer (SRE)'), ('Full-Stack Developer', 'Full-Stack Developer'), ('PhD Candidate in Physics and Data Science', 'PhD Candidate in Physics and Data Science'), ('Co-Founder', 'Co-Founder'), ('Chief Technology Officer', 'Chief Technology Officer'), ('Chief Administrative Officer', 'Chief Administrative Officer'), ('Senior Project Manager', 'Senior Project Manager'), ('Junior Project Manager', 'Junior Project Manager'), ('Frontend Software Developer', 'Frontend Software Developer'), ('Backend Software Developer', 'Backend Software Developer'), ('Senior Data Scientist', 'Senior Data Scientist'), ('Junior Data Scientist', 'Junior Data Scientist'), ('Community Manager', 'Community Manager'), ('Content Creator', 'Content Creator')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='porfolio_1',
            field=models.CharField(blank=True, choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence Engineer', 'Artificial Intelligence Engineer'), ('Site Reliability Engineer (SRE)', 'Site Reliability Engineer (SRE)'), ('Full-Stack Developer', 'Full-Stack Developer'), ('PhD Candidate in Physics and Data Science', 'PhD Candidate in Physics and Data Science'), ('Co-Founder', 'Co-Founder'), ('Chief Technology Officer', 'Chief Technology Officer'), ('Chief Administrative Officer', 'Chief Administrative Officer'), ('Senior Project Manager', 'Senior Project Manager'), ('Junior Project Manager', 'Junior Project Manager'), ('Frontend Software Developer', 'Frontend Software Developer'), ('Backend Software Developer', 'Backend Software Developer'), ('Senior Data Scientist', 'Senior Data Scientist'), ('Junior Data Scientist', 'Junior Data Scientist'), ('Community Manager', 'Community Manager'), ('Content Creator', 'Content Creator')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='porfolio_2',
            field=models.CharField(blank=True, choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence Engineer', 'Artificial Intelligence Engineer'), ('Site Reliability Engineer (SRE)', 'Site Reliability Engineer (SRE)'), ('Full-Stack Developer', 'Full-Stack Developer'), ('PhD Candidate in Physics and Data Science', 'PhD Candidate in Physics and Data Science'), ('Co-Founder', 'Co-Founder'), ('Chief Technology Officer', 'Chief Technology Officer'), ('Chief Administrative Officer', 'Chief Administrative Officer'), ('Senior Project Manager', 'Senior Project Manager'), ('Junior Project Manager', 'Junior Project Manager'), ('Frontend Software Developer', 'Frontend Software Developer'), ('Backend Software Developer', 'Backend Software Developer'), ('Senior Data Scientist', 'Senior Data Scientist'), ('Junior Data Scientist', 'Junior Data Scientist'), ('Community Manager', 'Community Manager'), ('Content Creator', 'Content Creator')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='porfolio_3',
            field=models.CharField(blank=True, choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence Engineer', 'Artificial Intelligence Engineer'), ('Site Reliability Engineer (SRE)', 'Site Reliability Engineer (SRE)'), ('Full-Stack Developer', 'Full-Stack Developer'), ('PhD Candidate in Physics and Data Science', 'PhD Candidate in Physics and Data Science'), ('Co-Founder', 'Co-Founder'), ('Chief Technology Officer', 'Chief Technology Officer'), ('Chief Administrative Officer', 'Chief Administrative Officer'), ('Senior Project Manager', 'Senior Project Manager'), ('Junior Project Manager', 'Junior Project Manager'), ('Frontend Software Developer', 'Frontend Software Developer'), ('Backend Software Developer', 'Backend Software Developer'), ('Senior Data Scientist', 'Senior Data Scientist'), ('Junior Data Scientist', 'Junior Data Scientist'), ('Community Manager', 'Community Manager'), ('Content Creator', 'Content Creator')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='porfolio_4',
            field=models.CharField(blank=True, choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence Engineer', 'Artificial Intelligence Engineer'), ('Site Reliability Engineer (SRE)', 'Site Reliability Engineer (SRE)'), ('Full-Stack Developer', 'Full-Stack Developer'), ('PhD Candidate in Physics and Data Science', 'PhD Candidate in Physics and Data Science'), ('Co-Founder', 'Co-Founder'), ('Chief Technology Officer', 'Chief Technology Officer'), ('Chief Administrative Officer', 'Chief Administrative Officer'), ('Senior Project Manager', 'Senior Project Manager'), ('Junior Project Manager', 'Junior Project Manager'), ('Frontend Software Developer', 'Frontend Software Developer'), ('Backend Software Developer', 'Backend Software Developer'), ('Senior Data Scientist', 'Senior Data Scientist'), ('Junior Data Scientist', 'Junior Data Scientist'), ('Community Manager', 'Community Manager'), ('Content Creator', 'Content Creator')], max_length=100, null=True),
        ),
    ]
