# Generated by Django 4.2.23 on 2026-01-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_info_2_galeriadeimagenesinfo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='numero_coffe',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Servicios IT Entregados'),
        ),
        migrations.AlterField(
            model_name='home',
            name='numero_experiencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seguridad'),
        ),
        migrations.AlterField(
            model_name='home',
            name='numero_horas',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Gobernanza IT'),
        ),
        migrations.AlterField(
            model_name='home',
            name='numero_wins',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Calidad de Servicio'),
        ),
    ]
