# Generated by Django 4.2.23 on 2026-01-25 19:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_home_numero_coffe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsFormDetailOpeningPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('jobs_category', models.CharField(blank=True, choices=[('Community Manager Senior', 'Community Manager Senior'), ('Community Manager Junior', 'Community Manager Junior'), ('Content Designer Senior', 'Content Designer Senior'), ('Content Designer Junior', 'Content Designer Junior'), ('Project Manager Senior', 'Project Manager Senior'), ('Project Manager Junior', 'Project Manager Junior'), ('UI/UX Designer Senior', 'UI/UX Designer Senior'), ('UI/UX Designer Junior', 'UI/UX Designer Junior'), ('Django Developer Senior', 'Django Developer Senior'), ('Django Developer Junior', 'Django Developer Junior'), ('Site Reliability Engineer Senior', 'Site Reliability Engineer Senior'), ('Site Reliability Engineer Junior', 'Site Reliability Engineer Junior')], max_length=100, null=True)),
                ('city', models.CharField(blank=True, choices=[('Quito', 'Quito'), ('Guayaquil', 'Guayaquil'), ('Cuenca', 'Cuenca'), ('Buenos Aires', 'Buenos Aires'), ('Mendoza', 'Mendoza'), ('Paris', 'Paris'), ('Lausanne', 'Lausanne'), ('New York', 'New York')], max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('Ecuador', 'Ecuador'), ('Switzerland', 'Switzerland'), ('Argentina', 'Argentina'), ('France', 'France'), ('United States', 'United States')], max_length=100, null=True)),
                ('timejobs', models.CharField(blank=True, choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=100, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descripción corta')),
                ('uploadcv', models.FileField(blank=True, null=True, upload_to='CV_file/%Y/%m/%d')),
                ('comments', wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje para que nos dejen un comentario')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
                ('content', wagtail.fields.StreamField([('title_and_text', 2), ('full_richtext', 1), ('simple_richtext', 1), ('image', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True)),
                ('uploaded_image_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='JobsListingOpeningPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(help_text='Overwrites the default title', max_length=100)),
                ('jobs_category', models.CharField(blank=True, choices=[('Marketing & Publishing', 'Marketing & Publishing'), ('UI/UX Developer', 'UI/UX Developer'), ('Python/Django Developer', 'Python/Django Developer'), ('Docker Developer', 'Docker Developer'), ('Kubernetes Developer', 'Kubernetes Developer'), ('FullStack Developer', 'FullStack Developer'), ('Chief Technology Officer', 'Chief Technology Officer'), ('Chief Officer', 'Chief Officer')], max_length=100, null=True)),
                ('benefits', wagtail.fields.RichTextField(blank=True, verbose_name='Beneficios')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JobsFormOpeningPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('image', 'Upload Image')], max_length=16)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='webapp.jobsformdetailopeningpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
