# Generated by Django 4.2.23 on 2026-01-25 22:12

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('webapp', '0010_jobsformdetailopeningpage_jobslistingopeningpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('custom_title', models.CharField(help_text='Nombre', max_length=100)),
                ('portfolio_1', models.CharField(choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100, null=True)),
                ('portfolio_2', models.CharField(choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100, null=True)),
                ('portfolio_3', models.CharField(choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100, null=True)),
                ('portfolio_4', models.CharField(choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('Web Content', 'Web Content'), ('Social Networks Content', 'Social Networks Content'), ('Web Design', 'Web Design'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100, null=True)),
                ('aboutus', wagtail.fields.RichTextField(blank=True, verbose_name='Acerca de mí')),
                ('aboutus_1', wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje 1')),
                ('aboutus_2', wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje 2')),
                ('aboutus_3', wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje 3')),
                ('experience_message', models.CharField(help_text='Mensaje de experiencia', max_length=100, null=True)),
                ('educational_message', models.CharField(help_text='Mensaje de educación', max_length=100, null=True)),
                ('comments', wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje para que nos dejen un comentario')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto de perfil')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ContactFormResumeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutUsPageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('team1_name', models.CharField(help_text='Team 1 Name', max_length=100)),
                ('team2_name', models.CharField(help_text='Team 2 Name', max_length=100)),
                ('team3_name', models.CharField(help_text='Team 3 Name', max_length=100)),
                ('team4_name', models.CharField(help_text='Team 4 Name', max_length=100)),
                ('team1_position', models.CharField(help_text='Team 1 Position', max_length=100)),
                ('team2_position', models.CharField(help_text='Team 2 Position', max_length=100)),
                ('team3_position', models.CharField(help_text='Team 3 Position', max_length=100)),
                ('team4_position', models.CharField(help_text='Team 4 Position', max_length=100)),
                ('image_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner')),
                ('image_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Profile Picture 1')),
                ('image_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Profile Picture 2')),
                ('image_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Profile Picture 3')),
                ('image_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Profile Picture 4')),
                ('image_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Profile Picture 5')),
                ('image_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Profile Picture 6')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutus_items', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
