# Generated by Django 4.2.23 on 2026-01-26 17:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('webapp', '0011_resumepage_contactformresumefield_aboutuspageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutusPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(help_text='Overwrites the default title', max_length=100)),
                ('aboutus', wagtail.fields.RichTextField(blank=True, verbose_name='SmartQuail Story')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='comments',
        ),
        migrations.AlterField(
            model_name='aboutuspageitem',
            name='team1_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuspageitem',
            name='team1_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuspageitem',
            name='team2_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuspageitem',
            name='team2_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuspageitem',
            name='team3_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuspageitem',
            name='team3_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuspageitem',
            name='team4_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuspageitem',
            name='team4_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='aboutus',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='aboutus_1',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='aboutus_2',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='aboutus_3',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='custom_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='educational_message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='experience_message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='aboutuspageitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutus_items', to='webapp.aboutuspage'),
        ),
    ]
