# Generated by Django 4.2.23 on 2026-01-26 20:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('webapp', '0012_aboutuspage_remove_resumepage_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumepage',
            old_name='image',
            new_name='hero_background',
        ),
        migrations.RenameField(
            model_name='resumepage',
            old_name='custom_title',
            new_name='hero_name',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='aboutus',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='aboutus_1',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='aboutus_2',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='aboutus_3',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='portfolio_1',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='portfolio_2',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='portfolio_3',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='portfolio_4',
        ),
        migrations.AddField(
            model_name='resumepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='about_title',
            field=models.CharField(blank=True, default='About Me', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='hero_rotating_text',
            field=models.CharField(blank=True, help_text='Ej: Creative | Designer | Front-end Developer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='educational_message',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='experience_message',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(help_text='Ej: icofont-facebook', max_length=50)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField(help_text='0 - 100')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_categories', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('period', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', wagtail.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('period', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('description', wagtail.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_items', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(help_text='Ej: icofont-clock-time', max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
