# Generated by Django 4.2.30 on 2026-09-14 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título / Asunto')),
                ('tipo_mailing', models.CharField(choices=[('informativo', 'Informativo'), ('comunicativo', 'Comunicativo'), ('financiero', 'Financiero'), ('publicitario', 'Publicitario')], default='informativo', max_length=50, verbose_name='Tipo de Mailing')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha y Hora de Programación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programado', 'Programado / Listo para enviar'), ('enviado', 'Enviado')], default='borrador', help_text='Guarda como borrador o cambia a programado/enviado.', max_length=20, verbose_name='Estado del Envío')),
                ('contenido', models.TextField(help_text='Puedes ingresar múltiples líneas o texto enriquecido según necesites.', verbose_name='Información del Mailing')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destinatario')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
            },
        ),
    ]
