# Generated by Django 4.2.30 on 2026-10-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingitem',
            name='idioma',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés')], default='es', max_length=10, verbose_name='Idioma del Mailing'),
        ),
        migrations.AlterField(
            model_name='mailingitem',
            name='tipo_mailing',
            field=models.CharField(choices=[('informativo', 'Informativo'), ('comunicativo', 'Comunicativo'), ('financiero', 'Financiero'), ('publicitario', 'Publicitario'), ('bienvenida', 'bienvenida'), ('soporte', 'soporte')], default='informativo', max_length=50, verbose_name='Tipo de Mailing'),
        ),
    ]
