# Generated by Django 4.2.30 on 2026-09-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingitem',
            name='idioma',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés')], default='es', max_length=10, verbose_name='Idioma del Mailing'),
        ),
    ]
