# Generated by Django 4.2.30 on 2026-09-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailingitem_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingitem',
            name='tipo_mailing',
            field=models.CharField(choices=[('informativo', 'Informativo'), ('comunicativo', 'Comunicativo'), ('financiero', 'Financiero'), ('publicitario', 'Publicitario'), ('bienvenida', 'bienvenida'), ('soporte', 'soporte')], default='informativo', max_length=50, verbose_name='Tipo de Mailing'),
        ),
    ]
